sudo: false

language: cpp

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
      - boost-latest

    packages:
      - libboost1.55-all-dev

matrix:
  exclude:
    - os: osx
      compiler: gcc

script:
  - mkdir build && cd build
  - cmake ..
  - make --jobs 2 check
