sudo: false

language: cpp

addons:
  apt:
    sources:
      - boost-latest

    packages:
      - doxygen
      - libboost-thread1.55-dev

matrix:
  include:
    - os: osx
      compiler: clang

    - os: osx
      compiler: clang
      osx_image: xcode6.4
      env: XCODE=6.4

    - os: osx
      compiler: clang
      osx_image: xcode7
      env: XCODE=7 OSX_SCRIPT="brew install cmake"

    - os: osx
      osx_image: xcode7
      compiler: gcc-5
      env: XCODE=7 OSX_SCRIPT="brew install cmake"

    - os: linux
      compiler: gcc

    - os: linux
      compiler: clang

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ];
    then
      wget http://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.tar.gz;
      tar -xzvf cmake-3.2.3-Linux-x86_64.tar.gz;
      export PATH=$PWD/cmake-3.2.3-Linux-x86_64/bin:$PATH;
   fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ];
    then
     brew update || brew update;
     $OSX_SCRIPT
    fi

script:
  - mkdir build && cd build
  - cmake ..
  - make --jobs 2

notifications:
  irc:
    channels:
      - "irc.freenode.org#haskell-lens"
    skip_join: true
    template:
      - "\x0313thc\x0f/\x0306%{branch}\x0f \x0314%{commit}\x0f %{message} \x0302\x1f%{build_url}\x0f"

# EOF
