sudo: false

language: cpp

os:
  - linux
  - osx

compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
      - boost-latest

    packages:
      - libboost1.55-all-dev

matrix:
  exclude:
    - os: osx
      compiler: gcc

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ];
    then
      wget http://www.cmake.org/files/v3.2/cmake-3.2.3-Linux-x86_64.tar.gz;
      tar -xzvf cmake-3.2.3-Linux-x86_64.tar.gz;
      export PATH=$PWD/cmake-3.2.3-Linux-x86_64/bin:$PATH;
   fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ];
    then
     brew update;
   fi

script:
  - mkdir build && cd build
  - cmake ..
  - make --jobs 2 check

