-- SPDX-FileCopyrightText: 2026 Edward Kmett
-- SPDX-License-Identifier: UPL-1.0 AND BSD-3-Clause

-- GHC 9.14.1 calling-convention evidence, kept separate from WHNF facts.
module THC.CBV (entryContract, existingMarks, eligible) where

import GHC.Plugins
import GHC.Core.Tidy (tidyCbvInfoTop)
import GHC.Types.Basic (isMarkedCbv)
import GHC.Types.Name.Set (emptyNameSet)

existingMarks :: Id -> Maybe [Bool]
existingMarks = fmap (map isMarkedCbv) . idCbvMarks_maybe

eligible :: Id -> Bool
eligible v = isWorkerLikeId v || isJoinId v

-- These are entry obligations, never a claim that a Core argument is WHNF.
-- Before Tidy, local CbvMark lists are intentionally empty. Use the pinned
-- compiler's own selection logic rather than interpreting demand strings:
-- it handles worker/join eligibility, join prefixes, single-register args,
-- absent/dead-end exclusions, and trimming to the function's value arity.
--
-- Passing emptyNameSet deliberately requests a THC-internal convention,
-- including where native boot-export restrictions might prohibit that ABI.
-- Every THC entry route must enforce it, including saturated PAPs and host
-- calls. It does not modify the Id, Core tree, native calling convention,
-- representation.evaluated, or the GHC output generated by this plugin.
entryContract :: Bool -> Id -> CoreExpr -> ([Bool], String)
entryContract derive v rhs
  | Just marks <- existingMarks v, or marks = (marks, "ghc-id")
  | derive, eligible v
  , let marks = maybe [] id (existingMarks (tidyCbvInfoTop emptyNameSet v rhs))
  , or marks = (marks, "ghc-tidy-proposal")
  | otherwise = ([], "none")
