-- SPDX-FileCopyrightText: 2026 Edward Kmett
-- SPDX-License-Identifier: UPL-1.0 AND BSD-3-Clause
{-# LANGUAGE OverloadedStrings #-}
module SimdAddressFixtures (prepareSimdAddresses) where

import Control.Monad (forM, unless, when)
import Data.Aeson (Value(..), eitherDecodeStrict', object, (.=))
import qualified Data.Aeson.KeyMap as KeyMap
import qualified Data.ByteString as BS
import qualified Data.ByteString.Char8 as BSC
import Data.Char (toLower)
import Data.List (intercalate, isPrefixOf, sort)
import qualified Data.Map.Strict as Map
import FixtureSupport
import System.Directory
import System.Environment (lookupEnv)
import System.Exit (die)
import System.FilePath
import System.Info (arch)

-- Existing vector representations only. The six newly introduced narrow-wide
-- representations and their memory primitives have a separate fixture owner.
data Shape = Shape String Int Int
shapes :: [Shape]
shapes = [Shape "Int32" 4 4, Shape "Word32" 4 4, Shape "Float" 4 4, Shape "Double" 2 8,
  Shape "Int16" 16 2, Shape "Word16" 16 2, Shape "Int32" 8 4, Shape "Word32" 8 4,
  Shape "Int32" 16 4, Shape "Word32" 16 4, Shape "Int64" 4 8, Shape "Word64" 4 8,
  Shape "Int64" 8 8, Shape "Word64" 8 8, Shape "Float" 8 4, Shape "Float" 16 4,
  Shape "Double" 4 8, Shape "Double" 8 8]
shapeName :: Shape -> String
shapeName (Shape scalar lanes _) = scalar ++ "X" ++ show lanes
vectorBytes :: Shape -> Int
vectorBytes (Shape _ lanes width) = lanes * width
data Entry = Entry Shape String Bool
entries :: [Entry]
entries = [Entry shape operation scalar | shape <- shapes,
  operation <- ["Index","Read","Write"], scalar <- [False,True]]
entryName :: Entry -> String
entryName (Entry shape operation scalar) = lower (shapeName shape) ++ operation ++ if scalar then "Scalar" else "Packed"
lower :: String -> String
lower [] = []
lower (c:cs) = toLower c : cs
primitive :: Entry -> String
primitive (Entry shape@(Shape scalar _ _) operation scalarOffset) = lower operation ++
  (if scalarOffset then scalar ++ "OffAddrAs" ++ shapeName shape else shapeName shape ++ "OffAddr") ++ "#"
seeds :: [Integer]
seeds = [-2^(63::Int),-129,-1,0,1,127,65535,2^(63::Int)-1]
requests :: [Entry] -> [String]
requests selected = [intercalate "\t" [entryName entry,show seed,show offset] |
  entry@(Entry (Shape _ lanes _) _ scalar) <- selected, seed <- seeds,
  offset <- if scalar then [0,1,2*lanes] else [0,1,2]]

number :: Int -> String
number value = show value ++ "#"
laneValue :: Shape -> String -> String
laneValue (Shape scalar _ width) value
  | scalar == "Float" || scalar == "Double" = "castWord" ++ show (width*8) ++ "To" ++ scalar ++
      "# (wordToWord" ++ show (width*8) ++ "# (int2Word# (" ++ value ++ ")))"
  | "Word" `isPrefixOf` scalar = "wordTo" ++ scalar ++ "# (int2Word# (" ++ value ++ "))"
  | otherwise = "intTo" ++ scalar ++ "# (" ++ value ++ ")"
laneInt :: Shape -> String -> String
laneInt (Shape scalar _ width) value
  | scalar == "Float" || scalar == "Double" = "word2Int# (word" ++ show (width*8) ++
      "ToWord# (cast" ++ scalar ++ "ToWord" ++ show (width*8) ++ "# " ++ value ++ "))"
  | "Word" `isPrefixOf` scalar = "word2Int# (" ++ lower scalar ++ "ToWord# " ++ value ++ ")"
  | otherwise = lower scalar ++ "ToInt# " ++ value
weighted :: Shape -> String
weighted shape@(Shape _ lanes _) = foldl1 (\a b -> "(" ++ a ++ " +# " ++ b ++ ")")
  ["((" ++ laneInt shape ("v" ++ show lane) ++ ") *# " ++ number (2*lane+1) ++ ")" | lane <- [0..lanes-1]]
header :: String -> String
header name = unlines ["-- Generated by the checked-in SimdAddressFixtures Haskell producer.",
  "{-# LANGUAGE MagicHash, UnboxedTuples #-}","module " ++ name ++ " where","import GHC.Exts"]

vectorFunction :: Entry -> String
vectorFunction entry@(Entry shape@(Shape _ lanes _) operation _) = unlines
  ["{-# OPAQUE " ++ name ++ " #-}", name ++ " :: Addr# -> Int# -> Int# -> Int#", name ++ " address offset seed = " ++ body]
  where
    name = entryName entry
    unpack = "case unpack" ++ shapeName shape ++ "# vector of { (# " ++
      intercalate ", " ["v" ++ show lane | lane <- [0..lanes-1]] ++ " #) -> " ++ weighted shape ++ " }"
    body = case operation of
      "Index" -> "case " ++ primitive entry ++ " address offset of { vector -> " ++ unpack ++ " }"
      "Read" -> "runRW# (\\s -> case " ++ primitive entry ++ " address offset s of { (# _, vector #) -> " ++ unpack ++ " })"
      _ -> "case pack" ++ shapeName shape ++ "# (# " ++ intercalate ", "
        [laneValue shape ("seed *# 23# +# " ++ number (lane*97)) | lane <- [0..lanes-1]] ++
        " #) of { vector -> runRW# (\\s -> case " ++ primitive entry ++ " address offset vector s of { _ -> 0# }) }"

-- Independent native reference uses scalar GHC address operations, not vectors
-- or the JVM implementation. It can run on hosts without AVX-512.
scalarFunction :: Entry -> String
scalarFunction entry@(Entry shape@(Shape scalar lanes _) operation scalarOffset) = unlines
  ["{-# NOINLINE " ++ name ++ " #-}", name ++ " :: Addr# -> Int# -> Int# -> Int#", name ++ " address offset seed = " ++ body]
  where
    name = entryName entry
    offset lane = "(" ++ (if scalarOffset then "offset" else "offset *# " ++ number lanes) ++ " +# " ++ number lane ++ ")"
    step lane rest = "case " ++ lower operation ++ scalar ++ "OffAddr# address " ++ offset lane ++
      (if operation == "Write" then " (" ++ laneValue shape ("seed *# 23# +# " ++ number (lane*97)) ++ ")" else "") ++
      (if operation == "Index" then "" else " s" ++ show lane) ++ " of { " ++
      (case operation of "Index" -> "v" ++ show lane; "Read" -> "(# s" ++ show (lane+1) ++ ", v" ++ show lane ++ " #)";
                         _ -> "s" ++ show (lane+1)) ++ " -> " ++ rest ++ " }"
    chain = foldr step (if operation == "Write" then "0#" else weighted shape) [0..lanes-1]
    body = if operation == "Index" then chain else "runRW# (\\s0 -> " ++ chain ++ ")"

nativeDriver :: String -> [Entry] -> String
nativeDriver moduleName selected = unlines
  ["{-# LANGUAGE MagicHash, UnboxedTuples #-}","module Main where","import GHC.Exts",
   "import qualified " ++ moduleName ++ " as Operation",
   "initialize bytes size seed i s = case i ==# size of",
   "  1# -> s",
   "  _ -> case writeWord8Array# bytes i (wordToWord8# (int2Word# (seed +# i *# 37#))) s of",
   "    s' -> initialize bytes size seed (i +# 1#) s'",
   "checksum bytes size i total s = case i ==# size of",
   "  1# -> (# s,total #)",
   "  _ -> case readWord8Array# bytes i s of",
   "    (# s',v #) -> checksum bytes size (i +# 1#) (total +# word2Int# (word8ToWord# v) *# (2# *# i +# 1#)) s'",
   "run name (I# seed) (I# offset) = runRW# (\\s -> case size name of { I# n ->",
   "  case newPinnedByteArray# n s of { (# s1,bytes #) -> case initialize bytes n seed 0# s1 of { s2 ->",
   "  case select name (mutableByteArrayContents# bytes) offset seed of { answer ->",
   "  case checksum bytes n 0# 0# s2 of { (# s3,digest #) -> keepAlive# bytes s3 (\\_ -> (I# answer,I# digest)) }}}}})",
   "size :: String -> Int","size name = case name of"] ++
  unlines ["  " ++ show (entryName entry) ++ " -> " ++ show (3*vectorBytes shape) | entry@(Entry shape _ _) <- selected] ++
  unlines ["  _ -> error \"Unknown vector address entry\"",
   "select :: String -> Addr# -> Int# -> Int# -> Int#","select name = case name of"] ++
  unlines ["  " ++ show (entryName entry) ++ " -> Operation." ++ entryName entry | entry <- selected] ++
  unlines ["  _ -> error \"Unknown vector address entry\"",
   "main :: IO ()","main = getContents >>= mapM_ emit . lines",
   "  where emit line = case words line of",
   "          [name,seed,offset] -> case run name (read seed) (read offset) of",
   "            (answer,digest) -> putStrLn (name ++ \"\\t\" ++ seed ++ \"\\t\" ++ offset ++ \"\\t\" ++ show answer ++ \"\\t\" ++ show digest)",
   "          _ -> fail \"Malformed vector address input\""]

prepareSimdAddresses :: FilePath -> IO ()
prepareSimdAddresses root = do
  let directory = "build/simd-address-families"
      sourceDir = directory </> "source"
      manifest = root </> directory </> "manifest.json"
      logs = directory </> "commands"
      execute = runLogged 300 root logs
      narrow = filter (\(Entry shape _ _) -> vectorBytes shape == 16) entries
      native128 = arch `notElem` ["arm64","aarch64"]
      emit name body = writeFile (root </> sourceDir </> name) body
  createDirectoryIfMissing True (root </> sourceDir)
  present <- doesFileExist manifest
  when present (removeFile manifest)
  ghc <- maybe "ghc" id <$> lookupEnv "GHC"
  version <- execute "ghc-version" [] ghc ["--numeric-version"]
  unless (commandStdout version == "9.14.1\n") (die "Vector addresses require GHC 9.14.1")
  emit "SimdAddressAudit.hs" (header "SimdAddressAudit" ++ concatMap vectorFunction entries)
  emit "SimdAddress128Audit.hs" (header "SimdAddress128Audit" ++ concatMap vectorFunction narrow)
  emit "SimdAddressScalar.hs" (header "SimdAddressScalar" ++ concatMap scalarFunction entries)
  emit "ScalarNative.hs" (nativeDriver "SimdAddressScalar" entries)
  emit "VectorNative.hs" (nativeDriver "SimdAddress128Audit" narrow)
  let native mode driver selected llvm = do
        let input = directory </> mode ++ "-inputs.tsv"
            destination = directory </> mode
            binary = destination </> "oracle"
            oracle = directory </> mode ++ "-oracle.tsv"
        createDirectoryIfMissing True (root </> destination)
        writeFile (root </> input) (unlines (requests selected))
        built <- execute (mode ++ "-build") [] ghc
          (["--make","-O2","-fforce-recomp","-dcore-lint","-dstg-lint","-i" ++ sourceDir,
            "-odir",destination,"-hidir",destination,sourceDir </> driver,"-o",binary] ++ ["-fllvm" | llvm])
        observed <- runLoggedWithInput input 120 root logs (mode ++ "-oracle") [] (root </> binary) []
        let rows = lines (BSC.unpack (commandStdout observed))
        unless (map (intercalate "\t" . take 3 . splitTab) rows == requests selected &&
          all ((==5) . length . splitTab) rows && BS.null (commandStderr observed)) (die "Native vector-address row domain changed")
        BS.writeFile (root </> oracle) (commandStdout observed)
        pure ([input,binary,oracle] ++ commandArtifacts built ++ commandArtifacts observed)
  scalarArtifacts <- native "scalar" "ScalarNative.hs" entries False
  vectorArtifacts <- if native128 then native "vector128" "VectorNative.hs" narrow True else pure []
  exported <- forM (("pre","SimdAddressAudit",entries,False) :
    [("post128","SimdAddress128Audit",narrow,True) | native128]) $ \(stage,moduleName,selected,post) -> do
      let coreDirectory = directory </> stage ++ "-core"
          core = coreDirectory </> moduleName <.> "json"
          audit = directory </> stage ++ "-audit.json"
      compiled <- execute (stage ++ "-export")
        [("THC_CORE_OUT",root </> coreDirectory),("THC_GHC_OUT",root </> directory </> stage ++ "-ghc")]
        "compiler/export.sh" ((if post then ["-fllvm","-fplugin-opt=THC.Plugin:post-tidy"]
          else ["-fno-code","-fwrite-if-simplified-core"]) ++ [sourceDir </> moduleName <.> "hs"])
      audited <- execute (stage ++ "-audit") [] "python3"
        (["scripts/audit-core.py",core,"--output",audit] ++ concatMap (\entry -> ["--entry",entryName entry]) selected)
      report <- BS.readFile (root </> audit) >>= either die pure . eitherDecodeStrict'
      case report of
        Object fields | KeyMap.lookup "accepted" fields == Just (Bool True),
          KeyMap.lookup "issues" fields == Just (Array mempty),
          KeyMap.lookup "missingGlobals" fields == Just (Array mempty) -> pure ()
        _ -> die "Strict vector address audit failed"
      pure (stage,object ["core" .= core,"audit" .= audit,"entries" .= map entryName selected],
        [core,audit] ++ commandArtifacts compiled ++ commandArtifacts audited)
  plugin <- listDirectory (root </> "compiler/THC")
  scripts <- listDirectory (root </> "scripts")
  inputHashes <- hashes root (sort $ ["test/haskell-fixtures/SimdAddressFixtures.hs",
    "test/haskell-fixtures/FixtureSupport.hs","test/haskell-fixtures/Main.hs","thc.cabal",
    "compiler/export.sh","compiler/build.sh","compiler/toolchain.sh","compiler/plugin.py",
    "scripts/audit-core.py","scripts/core-capabilities.json","scripts/simd-families.json",
    "src/main/resources/thc/scalar-primop-signatures.json"] ++
    ["compiler/THC" </> path | path <- plugin,takeExtension path == ".hs"] ++
    ["scripts" </> path | path <- scripts,"core_" `isPrefixOf` path,takeExtension path == ".py"])
  sources <- listDirectory (root </> sourceDir)
  artifactHashes <- hashes root ([sourceDir </> path | path <- sources,takeExtension path == ".hs"] ++
    scalarArtifacts ++ vectorArtifacts ++ commandArtifacts version ++ concat [files | (_,_,files) <- exported])
  writeJson manifest (object ["schema" .= (1::Int),"ghc" .= ("9.14.1"::String),
    "entries" .= map entryName entries,"primitives" .= map primitive entries,
    "scalarRows" .= length (requests entries),"nativeVector128Rows" .= (if native128 then length (requests narrow) else 0),
    "stages" .= Map.fromList [(stage,value) | (stage,value,_) <- exported],
    "inputHashes" .= inputHashes,"artifactHashes" .= artifactHashes])
  putStrLn "SIMD addresses: 108 operations, 2592 native scalar rows, native 128-bit vector comparison when supported"
