// SPDX-FileCopyrightText: 2026 Edward Kmett
// SPDX-License-Identifier: UPL-1.0
package com.oracle.truffle.runtime;

import com.oracle.truffle.api.Truffle;
import com.oracle.truffle.api.TruffleLanguage;
import com.oracle.truffle.api.OptimizationFailedException;
import com.oracle.truffle.api.frame.VirtualFrame;
import com.oracle.truffle.api.nodes.RootNode;
import com.oracle.truffle.api.nodes.ExplodeLoop;
import com.oracle.truffle.api.nodes.DirectCallNode;
import com.oracle.truffle.api.nodes.Node;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.RejectedExecutionException;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicReference;
import java.util.function.Supplier;
import org.graalvm.polyglot.Context;
import terminalprobe.TerminalLanguage;

public final class TerminalTargetProbe {
    static void check(boolean b, String why) { if (!b) throw new AssertionError(why); }
    static void await(CountDownLatch latch) {
        try { check(latch.await(10, TimeUnit.SECONDS), "latch timeout"); }
        catch (InterruptedException e) { throw new AssertionError(e); }
    }
    static final class ProbeRoot extends RootNode {
        final boolean heavy;
        final long[] data = new long[2048];
        final AtomicInteger preparations = new AtomicInteger();
        final AtomicInteger rewrites = new AtomicInteger();
        ProbeRoot(TerminalLanguage language, boolean heavy) {
            super(language); this.heavy = heavy;
            for (int i = 0; i < data.length; ++i) data[i] = i + 1;
        }
        @Override @ExplodeLoop public Object execute(VirtualFrame f) {
            long value = (Long) f.getArguments()[0];
            if (heavy) for (int i = 0; i < 2048; ++i) value = (value ^ data[i]) * 17L + i;
            return value;
        }
        @Override protected boolean prepareForCompilation(boolean root, int tier, boolean last) {
            preparations.incrementAndGet(); return true;
        }
        @Override public long getGraphBudgetGeneration() { return rewrites.get() > 0 ? 1 : 0; }
        @Override public long prepareGraphBudgetRetry(long failed) { rewrites.incrementAndGet(); return 1; }
        @Override public String getName() { return heavy ? "terminal oversized" : "terminal small"; }
    }
    static final class Events implements OptimizedTruffleRuntimeListener {
        final OptimizedCallTarget target;
        final AtomicReference<String> reason = new AtomicReference<>();
        final CountDownLatch queued = new CountDownLatch(1);
        @Override public void onCompilationQueued(OptimizedCallTarget t, int tier) { if (t == target) queued.countDown(); }
        final AtomicInteger starts = new AtomicInteger(), failures = new AtomicInteger(), dequeues = new AtomicInteger();
        Events(OptimizedCallTarget t) { target = t; }
        @Override public void onCompilationStarted(OptimizedCallTarget t, AbstractCompilationTask task) {
            if (t == target) starts.incrementAndGet();
        }
        @Override public void onCompilationFailed(OptimizedCallTarget t, String reason, boolean bailout,
                boolean permanent, int tier, Supplier<String> stack) { if (t == target) { this.reason.set(reason); failures.incrementAndGet(); } }
        @Override public void onCompilationDequeued(OptimizedCallTarget t, Object source, CharSequence reason, int tier) {
            if (t == target) dequeues.incrementAndGet();
        }
    }
    static OptimizedCallTarget target(TerminalLanguage language, boolean heavy) {
        var t = (OptimizedCallTarget) new ProbeRoot(language, heavy).getCallTarget();
        t.call(7L); return t;
    }
    static void retire(OptimizedCallTarget t) {
        t.onCompilationFailed(() -> "terminal regression control", true, true, true, false);
    }
    static void finish(OptimizedCallTarget t) {
        try { t.waitForCompilation(); } catch (OptimizationFailedException expected) {}
    }
    static void rejected(Runnable request) {
        try { request.run(); throw new AssertionError("terminal queue admission accepted"); }
        catch (RejectedExecutionException expected) {}
    }
    // Mirrors generated bytecode roots: cloning is always allowed by the root itself.
    static final class CloneRoot extends RootNode {
        final TerminalLanguage language;
        final boolean reduced;
        @Children private IdentityPart[] parts;
        CloneRoot(TerminalLanguage language, boolean reduced) {
            super(language); this.language = language; this.reduced = reduced;
            parts = new IdentityPart[reduced ? 1 : 8];
            for (int i = 0; i < parts.length; ++i) parts[i] = new IdentityPart();
        }
        @Override public Object execute(VirtualFrame f) {
            Object result = f.getArguments()[0];
            for (var part : parts) result = part.execute(result);
            return result;
        }
        @Override public boolean isCloningAllowed() { return true; }
        @Override protected boolean isCloneUninitializedSupported() { return true; }
        @Override protected CloneRoot cloneUninitialized() { return new CloneRoot(language, true); }
    }
    static final class IdentityPart extends Node {
        Object execute(Object value) { return value; }
    }
    static final class Caller extends RootNode {
        @Child OptimizedDirectCallNode call;
        Caller(TerminalLanguage language, OptimizedCallTarget target) {
            super(language); call = (OptimizedDirectCallNode) DirectCallNode.create(target);
        }
        @Override public Object execute(VirtualFrame f) { return call.call(f.getArguments()); }
    }
    static void splitting(TerminalLanguage language, String mode) {
        var root = new CloneRoot(language, false);
        var source = (OptimizedCallTarget) root.getCallTarget();
        var first = new Caller(language, source); var second = new Caller(language, source);
        first.getCallTarget().call(7L); second.getCallTarget().call(9L);
        source.polymorphicSpecialize(root);
        check(source.isNeedsSplit(), "real polymorphic split requested");
        check(root.isCloningAllowed(), "root alone still permits cloning");
        retire(source);
        if (mode.equals("split")) {
            check(!first.call.isCallTargetCloningAllowed(), "failed target not publicly cloneable");
            check(!first.call.cloneCallTarget(), "failed explicit split rejected");
        } else if (mode.equals("automatic")) {
            check(first.getCallTarget().call(7L).equals(7L), "retired source remains executable");
        } else {
            first.call.split(); // The final guarded boundary, after a stale strategy decision.
        }
        check(first.call.getCurrentCallTarget() == source && first.call.getClonedCallTarget() == null,
                "failed source did not escape through " + mode);

        var healthy = (OptimizedCallTarget) new CloneRoot(language, false).getCallTarget();
        var a = new Caller(language, healthy); var b = new Caller(language, healthy);
        a.getCallTarget().call(7L); b.getCallTarget().call(9L);
        if (mode.equals("automatic")) {
            healthy.polymorphicSpecialize(healthy.getRootNode());
            check(healthy.isNeedsSplit(), "healthy automatic split requested");
            a.getCallTarget().call(7L);
        } else check(a.call.cloneCallTarget(), "healthy explicit split allowed");
        check(a.call.getCurrentCallTarget() != healthy, "healthy splitting remains enabled");

        // This is deliberately language-owned recovery, not runtime splitting.
        var reduced = root.cloneUninitialized();
        check(reduced.reduced, "language constructs reduced shape");
        var recovered = (OptimizedCallTarget) reduced.getCallTarget();
        check(recovered.call(7L).equals(7L), "reduced recovery preserves result");
        check(recovered.getNonTrivialNodeCount() < source.getNonTrivialNodeCount(), "recovery really is smaller");
        recovered.compile(true); finish(recovered);
        check(recovered != source && recovered.isValid(), "fresh language-owned recovery compiles");
        System.out.println("PASS " + mode + " rejects failed source, permits healthy split and language recovery");
    }
    static void admission(TerminalLanguage lang, OptimizedTruffleRuntime runtime) throws Exception {
        var t = target(lang, false); retire(t);
        check(!t.acceptForCompilation(), "OSR admission rejected");
        for (int i = 0; i < 20; ++i) check(!t.compile(true), "explicit request rejected");
        t.submitOSRCompilation().finish();
        rejected(() -> runtime.submitForCompilation(t, true));
        rejected(() -> runtime.submitForCompilation(t, true, CompilationTask.SubmissionReason.EXPLICIT));
        check(((ProbeRoot)t.getRootNode()).preparations.get() == 0, "retired target never entered PE");
        var transientTarget = target(lang, false);
        transientTarget.onCompilationFailed(() -> "retryable control", true, true, false, false);
        check(!transientTarget.isCompilationFailed(), "ordinary transient bailout unchanged");
        transientTarget.compile(true); finish(transientTarget);
        check(transientTarget.isValid(), "independent eligible target still compiles");

        var race = target(lang, false);
        var error = new AtomicReference<Throwable>();
        Thread submitter = new Thread(() -> {
            try { check(!race.compile(true), "request waiting on target lock rejected"); }
            catch (Throwable e) { error.set(e); }
        });
        synchronized (race) {
            submitter.start();
            long deadline = System.nanoTime() + TimeUnit.SECONDS.toNanos(10);
            while (submitter.getState() != Thread.State.BLOCKED && submitter.isAlive() && System.nanoTime() < deadline) Thread.yield();
            check(submitter.getState() == Thread.State.BLOCKED, "request reached target lock");
            retire(race);
        }
        submitter.join(10000);
        check(!submitter.isAlive() && error.get() == null, "locked request completion: " + error.get());
        check(((ProbeRoot)race.getRootNode()).preparations.get() == 0, "locked request no PE");
        System.out.println("PASS explicit/OSR/direct queue admission, target-lock race, transient control");
    }
    static void queued(TerminalLanguage lang, OptimizedTruffleRuntime runtime) throws Exception {
        var t = target(lang, false);
        var entered = new CountDownLatch(1); var release = new CountDownLatch(1);
        var blocker = runtime.getCompileQueue().submitInitialization(t, ignored -> { entered.countDown(); await(release); });
        await(entered);
        var events = new Events(t); runtime.addListener(events);
        try {
            var error = new AtomicReference<Throwable>();
            var submitter = new Thread(() -> {
                try { t.compile(true); } catch (Throwable e) { error.set(e); }
            });
            submitter.start(); await(events.queued);
            retire(t); release.countDown();
            blocker.awaitCompletion(10, TimeUnit.SECONDS);
            submitter.join(10000); finish(t);
            check(!submitter.isAlive() && error.get() == null, "queued request completion: " + error.get());
            check(events.starts.get() == 0 && events.dequeues.get() == 1, "queued terminal work discarded before PE");
        } finally { release.countDown(); runtime.removeListener(events); }
        System.out.println("PASS queued-before-retirement work discarded");
    }
    static void real(TerminalLanguage lang, OptimizedTruffleRuntime runtime, boolean osr) {
        var t = target(lang, true); var root = (ProbeRoot)t.getRootNode();
        var events = new Events(t); runtime.addListener(events);
        try {
            try {
                if (osr) {
                    OptimizedCallTarget.OSRCompilation request;
                    synchronized (t) { request = t.submitOSRCompilation(); }
                    request.finish();
                } else t.compile(true);
            } catch (OptimizationFailedException expected) {}
            finish(t);
            check(t.isCompilationFailed(), "real graph failure terminal");
            check(events.reason.get() != null && events.reason.get().contains("GraphTooBig"), "actual graph-budget failure: " + events.reason.get());
            check(root.rewrites.get() == 0, "no old in-place rewrite callback");
            check(events.starts.get() == 1 && events.failures.get() == 1 && root.preparations.get() == 1,
                  "one compiler attempt, including diagnostics: " + events.starts + "/" + events.failures + "/" + root.preparations);
            for (int i = 0; i < 20; ++i) { t.call(7L); check(!t.compile(true), "failed graph cannot resubmit"); }
            check(events.starts.get() == 1, "no repeated real PE");
        } finally { runtime.removeListener(events); }
        System.out.println("PASS real 1000-node bailout, no rewrite/diagnostic/explicit retry");
    }
    public static void main(String[] args) throws Exception {
        Truffle.getRuntime();
        boolean background = Boolean.parseBoolean(args[1]);
        try (var c = Context.newBuilder("terminal-probe").allowExperimentalOptions(true)
                .option("engine.BackgroundCompilation", "" + background).option("engine.MultiTier", "false")
                .option("engine.CompilerThreads", "1").option("engine.SingleTierCompilationThreshold", "10000000")
                .option("engine.CompilationFailureAction", background && !args[0].equals("options") ? "Print" : "Throw").option("compiler.DiagnoseFailure", "false")
                .option("compiler.MaximumGraalGraphSize", "1000").build()) {
            c.initialize("terminal-probe"); c.enter();
            try {
                var lang = TruffleLanguage.LanguageReference.create(TerminalLanguage.class).get(null);
                var runtime = (OptimizedTruffleRuntime) Truffle.getRuntime();
                if (args[0].equals("options")) {
                    check("false".equals(target(lang, false).getCompilerOptions().get("compiler.DiagnoseFailure")), "explicit DiagnoseFailure=false retained");
                    System.out.println("PASS explicit diagnostic opt-out");
                } else if (args[0].equals("admission")) admission(lang, runtime);
                else if (args[0].equals("queued")) queued(lang, runtime);
                else if (args[0].equals("split") || args[0].equals("automatic") || args[0].equals("splitlate")) splitting(lang, args[0]);
                else real(lang, runtime, args[0].equals("osr"));
            } finally { c.leave(); }
        }
    }
}
