// SPDX-FileCopyrightText: 2026 Edward Kmett
// SPDX-License-Identifier: UPL-1.0 AND BSD-3-Clause
package thc.runtime;

import java.util.List;

public enum VectorMemoryOp {
    INDEX_INT8X32_ADDRESS("indexInt8X32OffAddr#", false, VectorMemoryFamily.INT8, 32, GeneratedVectors.proofInt8X32, true),
    INDEX_INT8X32_ADDRESS_SCALAR("indexInt8OffAddrAsInt8X32#", true, VectorMemoryFamily.INT8, 32, GeneratedVectors.proofInt8X32, true),
    READ_INT8X32_ADDRESS("readInt8X32OffAddr#", false, VectorMemoryFamily.INT8, 32, GeneratedVectors.proofInt8X32, true),
    READ_INT8X32_ADDRESS_SCALAR("readInt8OffAddrAsInt8X32#", true, VectorMemoryFamily.INT8, 32, GeneratedVectors.proofInt8X32, true),
    WRITE_INT8X32_ADDRESS("writeInt8X32OffAddr#", false, VectorMemoryFamily.INT8, 32, GeneratedVectors.proofInt8X32, true),
    WRITE_INT8X32_ADDRESS_SCALAR("writeInt8OffAddrAsInt8X32#", true, VectorMemoryFamily.INT8, 32, GeneratedVectors.proofInt8X32, true),
    INDEX_WORD8X32_ADDRESS("indexWord8X32OffAddr#", false, VectorMemoryFamily.WORD8, 32, GeneratedVectors.proofWord8X32, true),
    INDEX_WORD8X32_ADDRESS_SCALAR("indexWord8OffAddrAsWord8X32#", true, VectorMemoryFamily.WORD8, 32, GeneratedVectors.proofWord8X32, true),
    READ_WORD8X32_ADDRESS("readWord8X32OffAddr#", false, VectorMemoryFamily.WORD8, 32, GeneratedVectors.proofWord8X32, true),
    READ_WORD8X32_ADDRESS_SCALAR("readWord8OffAddrAsWord8X32#", true, VectorMemoryFamily.WORD8, 32, GeneratedVectors.proofWord8X32, true),
    WRITE_WORD8X32_ADDRESS("writeWord8X32OffAddr#", false, VectorMemoryFamily.WORD8, 32, GeneratedVectors.proofWord8X32, true),
    WRITE_WORD8X32_ADDRESS_SCALAR("writeWord8OffAddrAsWord8X32#", true, VectorMemoryFamily.WORD8, 32, GeneratedVectors.proofWord8X32, true),
    INDEX_INT8X64_ADDRESS("indexInt8X64OffAddr#", false, VectorMemoryFamily.INT8, 64, GeneratedVectors.proofInt8X64, true),
    INDEX_INT8X64_ADDRESS_SCALAR("indexInt8OffAddrAsInt8X64#", true, VectorMemoryFamily.INT8, 64, GeneratedVectors.proofInt8X64, true),
    READ_INT8X64_ADDRESS("readInt8X64OffAddr#", false, VectorMemoryFamily.INT8, 64, GeneratedVectors.proofInt8X64, true),
    READ_INT8X64_ADDRESS_SCALAR("readInt8OffAddrAsInt8X64#", true, VectorMemoryFamily.INT8, 64, GeneratedVectors.proofInt8X64, true),
    WRITE_INT8X64_ADDRESS("writeInt8X64OffAddr#", false, VectorMemoryFamily.INT8, 64, GeneratedVectors.proofInt8X64, true),
    WRITE_INT8X64_ADDRESS_SCALAR("writeInt8OffAddrAsInt8X64#", true, VectorMemoryFamily.INT8, 64, GeneratedVectors.proofInt8X64, true),
    INDEX_WORD8X64_ADDRESS("indexWord8X64OffAddr#", false, VectorMemoryFamily.WORD8, 64, GeneratedVectors.proofWord8X64, true),
    INDEX_WORD8X64_ADDRESS_SCALAR("indexWord8OffAddrAsWord8X64#", true, VectorMemoryFamily.WORD8, 64, GeneratedVectors.proofWord8X64, true),
    READ_WORD8X64_ADDRESS("readWord8X64OffAddr#", false, VectorMemoryFamily.WORD8, 64, GeneratedVectors.proofWord8X64, true),
    READ_WORD8X64_ADDRESS_SCALAR("readWord8OffAddrAsWord8X64#", true, VectorMemoryFamily.WORD8, 64, GeneratedVectors.proofWord8X64, true),
    WRITE_WORD8X64_ADDRESS("writeWord8X64OffAddr#", false, VectorMemoryFamily.WORD8, 64, GeneratedVectors.proofWord8X64, true),
    WRITE_WORD8X64_ADDRESS_SCALAR("writeWord8OffAddrAsWord8X64#", true, VectorMemoryFamily.WORD8, 64, GeneratedVectors.proofWord8X64, true),
    INDEX_INT16X32_ADDRESS("indexInt16X32OffAddr#", false, VectorMemoryFamily.INT16, 64, GeneratedVectors.proofInt16X32, true),
    INDEX_INT16X32_ADDRESS_SCALAR("indexInt16OffAddrAsInt16X32#", true, VectorMemoryFamily.INT16, 64, GeneratedVectors.proofInt16X32, true),
    READ_INT16X32_ADDRESS("readInt16X32OffAddr#", false, VectorMemoryFamily.INT16, 64, GeneratedVectors.proofInt16X32, true),
    READ_INT16X32_ADDRESS_SCALAR("readInt16OffAddrAsInt16X32#", true, VectorMemoryFamily.INT16, 64, GeneratedVectors.proofInt16X32, true),
    WRITE_INT16X32_ADDRESS("writeInt16X32OffAddr#", false, VectorMemoryFamily.INT16, 64, GeneratedVectors.proofInt16X32, true),
    WRITE_INT16X32_ADDRESS_SCALAR("writeInt16OffAddrAsInt16X32#", true, VectorMemoryFamily.INT16, 64, GeneratedVectors.proofInt16X32, true),
    INDEX_WORD16X32_ADDRESS("indexWord16X32OffAddr#", false, VectorMemoryFamily.WORD16, 64, GeneratedVectors.proofWord16X32, true),
    INDEX_WORD16X32_ADDRESS_SCALAR("indexWord16OffAddrAsWord16X32#", true, VectorMemoryFamily.WORD16, 64, GeneratedVectors.proofWord16X32, true),
    READ_WORD16X32_ADDRESS("readWord16X32OffAddr#", false, VectorMemoryFamily.WORD16, 64, GeneratedVectors.proofWord16X32, true),
    READ_WORD16X32_ADDRESS_SCALAR("readWord16OffAddrAsWord16X32#", true, VectorMemoryFamily.WORD16, 64, GeneratedVectors.proofWord16X32, true),
    WRITE_WORD16X32_ADDRESS("writeWord16X32OffAddr#", false, VectorMemoryFamily.WORD16, 64, GeneratedVectors.proofWord16X32, true),
    WRITE_WORD16X32_ADDRESS_SCALAR("writeWord16OffAddrAsWord16X32#", true, VectorMemoryFamily.WORD16, 64, GeneratedVectors.proofWord16X32, true),
    INDEX_INT8X32("indexInt8X32Array#", false, VectorMemoryFamily.INT8, 32, GeneratedVectors.proofInt8X32, false),
    INDEX_INT8X32_SCALAR("indexInt8ArrayAsInt8X32#", true, VectorMemoryFamily.INT8, 32, GeneratedVectors.proofInt8X32, false),
    READ_INT8X32("readInt8X32Array#", false, VectorMemoryFamily.INT8, 32, GeneratedVectors.proofInt8X32, false),
    READ_INT8X32_SCALAR("readInt8ArrayAsInt8X32#", true, VectorMemoryFamily.INT8, 32, GeneratedVectors.proofInt8X32, false),
    WRITE_INT8X32("writeInt8X32Array#", false, VectorMemoryFamily.INT8, 32, GeneratedVectors.proofInt8X32, false),
    WRITE_INT8X32_SCALAR("writeInt8ArrayAsInt8X32#", true, VectorMemoryFamily.INT8, 32, GeneratedVectors.proofInt8X32, false),
    INDEX_WORD8X32("indexWord8X32Array#", false, VectorMemoryFamily.WORD8, 32, GeneratedVectors.proofWord8X32, false),
    INDEX_WORD8X32_SCALAR("indexWord8ArrayAsWord8X32#", true, VectorMemoryFamily.WORD8, 32, GeneratedVectors.proofWord8X32, false),
    READ_WORD8X32("readWord8X32Array#", false, VectorMemoryFamily.WORD8, 32, GeneratedVectors.proofWord8X32, false),
    READ_WORD8X32_SCALAR("readWord8ArrayAsWord8X32#", true, VectorMemoryFamily.WORD8, 32, GeneratedVectors.proofWord8X32, false),
    WRITE_WORD8X32("writeWord8X32Array#", false, VectorMemoryFamily.WORD8, 32, GeneratedVectors.proofWord8X32, false),
    WRITE_WORD8X32_SCALAR("writeWord8ArrayAsWord8X32#", true, VectorMemoryFamily.WORD8, 32, GeneratedVectors.proofWord8X32, false),
    INDEX_INT8X64("indexInt8X64Array#", false, VectorMemoryFamily.INT8, 64, GeneratedVectors.proofInt8X64, false),
    INDEX_INT8X64_SCALAR("indexInt8ArrayAsInt8X64#", true, VectorMemoryFamily.INT8, 64, GeneratedVectors.proofInt8X64, false),
    READ_INT8X64("readInt8X64Array#", false, VectorMemoryFamily.INT8, 64, GeneratedVectors.proofInt8X64, false),
    READ_INT8X64_SCALAR("readInt8ArrayAsInt8X64#", true, VectorMemoryFamily.INT8, 64, GeneratedVectors.proofInt8X64, false),
    WRITE_INT8X64("writeInt8X64Array#", false, VectorMemoryFamily.INT8, 64, GeneratedVectors.proofInt8X64, false),
    WRITE_INT8X64_SCALAR("writeInt8ArrayAsInt8X64#", true, VectorMemoryFamily.INT8, 64, GeneratedVectors.proofInt8X64, false),
    INDEX_WORD8X64("indexWord8X64Array#", false, VectorMemoryFamily.WORD8, 64, GeneratedVectors.proofWord8X64, false),
    INDEX_WORD8X64_SCALAR("indexWord8ArrayAsWord8X64#", true, VectorMemoryFamily.WORD8, 64, GeneratedVectors.proofWord8X64, false),
    READ_WORD8X64("readWord8X64Array#", false, VectorMemoryFamily.WORD8, 64, GeneratedVectors.proofWord8X64, false),
    READ_WORD8X64_SCALAR("readWord8ArrayAsWord8X64#", true, VectorMemoryFamily.WORD8, 64, GeneratedVectors.proofWord8X64, false),
    WRITE_WORD8X64("writeWord8X64Array#", false, VectorMemoryFamily.WORD8, 64, GeneratedVectors.proofWord8X64, false),
    WRITE_WORD8X64_SCALAR("writeWord8ArrayAsWord8X64#", true, VectorMemoryFamily.WORD8, 64, GeneratedVectors.proofWord8X64, false),
    INDEX_INT16X32("indexInt16X32Array#", false, VectorMemoryFamily.INT16, 64, GeneratedVectors.proofInt16X32, false),
    INDEX_INT16X32_SCALAR("indexInt16ArrayAsInt16X32#", true, VectorMemoryFamily.INT16, 64, GeneratedVectors.proofInt16X32, false),
    READ_INT16X32("readInt16X32Array#", false, VectorMemoryFamily.INT16, 64, GeneratedVectors.proofInt16X32, false),
    READ_INT16X32_SCALAR("readInt16ArrayAsInt16X32#", true, VectorMemoryFamily.INT16, 64, GeneratedVectors.proofInt16X32, false),
    WRITE_INT16X32("writeInt16X32Array#", false, VectorMemoryFamily.INT16, 64, GeneratedVectors.proofInt16X32, false),
    WRITE_INT16X32_SCALAR("writeInt16ArrayAsInt16X32#", true, VectorMemoryFamily.INT16, 64, GeneratedVectors.proofInt16X32, false),
    INDEX_WORD16X32("indexWord16X32Array#", false, VectorMemoryFamily.WORD16, 64, GeneratedVectors.proofWord16X32, false),
    INDEX_WORD16X32_SCALAR("indexWord16ArrayAsWord16X32#", true, VectorMemoryFamily.WORD16, 64, GeneratedVectors.proofWord16X32, false),
    READ_WORD16X32("readWord16X32Array#", false, VectorMemoryFamily.WORD16, 64, GeneratedVectors.proofWord16X32, false),
    READ_WORD16X32_SCALAR("readWord16ArrayAsWord16X32#", true, VectorMemoryFamily.WORD16, 64, GeneratedVectors.proofWord16X32, false),
    WRITE_WORD16X32("writeWord16X32Array#", false, VectorMemoryFamily.WORD16, 64, GeneratedVectors.proofWord16X32, false),
    WRITE_WORD16X32_SCALAR("writeWord16ArrayAsWord16X32#", true, VectorMemoryFamily.WORD16, 64, GeneratedVectors.proofWord16X32, false),
    INDEX_INT32X4_ADDRESS("indexInt32X4OffAddr#", false, VectorMemoryFamily.INT32, 16, null, true),
    INDEX_INT32X4_ADDRESS_SCALAR("indexInt32OffAddrAsInt32X4#", true, VectorMemoryFamily.INT32, 16, null, true),
    READ_INT32X4_ADDRESS("readInt32X4OffAddr#", false, VectorMemoryFamily.INT32, 16, null, true),
    READ_INT32X4_ADDRESS_SCALAR("readInt32OffAddrAsInt32X4#", true, VectorMemoryFamily.INT32, 16, null, true),
    WRITE_INT32X4_ADDRESS("writeInt32X4OffAddr#", false, VectorMemoryFamily.INT32, 16, null, true),
    WRITE_INT32X4_ADDRESS_SCALAR("writeInt32OffAddrAsInt32X4#", true, VectorMemoryFamily.INT32, 16, null, true),
    INDEX_WORD32X4_ADDRESS("indexWord32X4OffAddr#", false, VectorMemoryFamily.WORD32, 16, null, true),
    INDEX_WORD32X4_ADDRESS_SCALAR("indexWord32OffAddrAsWord32X4#", true, VectorMemoryFamily.WORD32, 16, null, true),
    READ_WORD32X4_ADDRESS("readWord32X4OffAddr#", false, VectorMemoryFamily.WORD32, 16, null, true),
    READ_WORD32X4_ADDRESS_SCALAR("readWord32OffAddrAsWord32X4#", true, VectorMemoryFamily.WORD32, 16, null, true),
    WRITE_WORD32X4_ADDRESS("writeWord32X4OffAddr#", false, VectorMemoryFamily.WORD32, 16, null, true),
    WRITE_WORD32X4_ADDRESS_SCALAR("writeWord32OffAddrAsWord32X4#", true, VectorMemoryFamily.WORD32, 16, null, true),
    INDEX_FLOATX4_ADDRESS("indexFloatX4OffAddr#", false, VectorMemoryFamily.FLOAT32, 16, null, true),
    INDEX_FLOATX4_ADDRESS_SCALAR("indexFloatOffAddrAsFloatX4#", true, VectorMemoryFamily.FLOAT32, 16, null, true),
    READ_FLOATX4_ADDRESS("readFloatX4OffAddr#", false, VectorMemoryFamily.FLOAT32, 16, null, true),
    READ_FLOATX4_ADDRESS_SCALAR("readFloatOffAddrAsFloatX4#", true, VectorMemoryFamily.FLOAT32, 16, null, true),
    WRITE_FLOATX4_ADDRESS("writeFloatX4OffAddr#", false, VectorMemoryFamily.FLOAT32, 16, null, true),
    WRITE_FLOATX4_ADDRESS_SCALAR("writeFloatOffAddrAsFloatX4#", true, VectorMemoryFamily.FLOAT32, 16, null, true),
    INDEX_DOUBLEX2_ADDRESS("indexDoubleX2OffAddr#", false, VectorMemoryFamily.DOUBLE64, 16, null, true),
    INDEX_DOUBLEX2_ADDRESS_SCALAR("indexDoubleOffAddrAsDoubleX2#", true, VectorMemoryFamily.DOUBLE64, 16, null, true),
    READ_DOUBLEX2_ADDRESS("readDoubleX2OffAddr#", false, VectorMemoryFamily.DOUBLE64, 16, null, true),
    READ_DOUBLEX2_ADDRESS_SCALAR("readDoubleOffAddrAsDoubleX2#", true, VectorMemoryFamily.DOUBLE64, 16, null, true),
    WRITE_DOUBLEX2_ADDRESS("writeDoubleX2OffAddr#", false, VectorMemoryFamily.DOUBLE64, 16, null, true),
    WRITE_DOUBLEX2_ADDRESS_SCALAR("writeDoubleOffAddrAsDoubleX2#", true, VectorMemoryFamily.DOUBLE64, 16, null, true),
    INDEX_INT16X16_ADDRESS("indexInt16X16OffAddr#", false, VectorMemoryFamily.INT16, 32, GeneratedVectors.proofInt16X16, true),
    INDEX_INT16X16_ADDRESS_SCALAR("indexInt16OffAddrAsInt16X16#", true, VectorMemoryFamily.INT16, 32, GeneratedVectors.proofInt16X16, true),
    READ_INT16X16_ADDRESS("readInt16X16OffAddr#", false, VectorMemoryFamily.INT16, 32, GeneratedVectors.proofInt16X16, true),
    READ_INT16X16_ADDRESS_SCALAR("readInt16OffAddrAsInt16X16#", true, VectorMemoryFamily.INT16, 32, GeneratedVectors.proofInt16X16, true),
    WRITE_INT16X16_ADDRESS("writeInt16X16OffAddr#", false, VectorMemoryFamily.INT16, 32, GeneratedVectors.proofInt16X16, true),
    WRITE_INT16X16_ADDRESS_SCALAR("writeInt16OffAddrAsInt16X16#", true, VectorMemoryFamily.INT16, 32, GeneratedVectors.proofInt16X16, true),
    INDEX_WORD16X16_ADDRESS("indexWord16X16OffAddr#", false, VectorMemoryFamily.WORD16, 32, GeneratedVectors.proofWord16X16, true),
    INDEX_WORD16X16_ADDRESS_SCALAR("indexWord16OffAddrAsWord16X16#", true, VectorMemoryFamily.WORD16, 32, GeneratedVectors.proofWord16X16, true),
    READ_WORD16X16_ADDRESS("readWord16X16OffAddr#", false, VectorMemoryFamily.WORD16, 32, GeneratedVectors.proofWord16X16, true),
    READ_WORD16X16_ADDRESS_SCALAR("readWord16OffAddrAsWord16X16#", true, VectorMemoryFamily.WORD16, 32, GeneratedVectors.proofWord16X16, true),
    WRITE_WORD16X16_ADDRESS("writeWord16X16OffAddr#", false, VectorMemoryFamily.WORD16, 32, GeneratedVectors.proofWord16X16, true),
    WRITE_WORD16X16_ADDRESS_SCALAR("writeWord16OffAddrAsWord16X16#", true, VectorMemoryFamily.WORD16, 32, GeneratedVectors.proofWord16X16, true),
    INDEX_INT32X8_ADDRESS("indexInt32X8OffAddr#", false, VectorMemoryFamily.INT32, 32, GeneratedVectors.proofInt32X8, true),
    INDEX_INT32X8_ADDRESS_SCALAR("indexInt32OffAddrAsInt32X8#", true, VectorMemoryFamily.INT32, 32, GeneratedVectors.proofInt32X8, true),
    READ_INT32X8_ADDRESS("readInt32X8OffAddr#", false, VectorMemoryFamily.INT32, 32, GeneratedVectors.proofInt32X8, true),
    READ_INT32X8_ADDRESS_SCALAR("readInt32OffAddrAsInt32X8#", true, VectorMemoryFamily.INT32, 32, GeneratedVectors.proofInt32X8, true),
    WRITE_INT32X8_ADDRESS("writeInt32X8OffAddr#", false, VectorMemoryFamily.INT32, 32, GeneratedVectors.proofInt32X8, true),
    WRITE_INT32X8_ADDRESS_SCALAR("writeInt32OffAddrAsInt32X8#", true, VectorMemoryFamily.INT32, 32, GeneratedVectors.proofInt32X8, true),
    INDEX_WORD32X8_ADDRESS("indexWord32X8OffAddr#", false, VectorMemoryFamily.WORD32, 32, GeneratedVectors.proofWord32X8, true),
    INDEX_WORD32X8_ADDRESS_SCALAR("indexWord32OffAddrAsWord32X8#", true, VectorMemoryFamily.WORD32, 32, GeneratedVectors.proofWord32X8, true),
    READ_WORD32X8_ADDRESS("readWord32X8OffAddr#", false, VectorMemoryFamily.WORD32, 32, GeneratedVectors.proofWord32X8, true),
    READ_WORD32X8_ADDRESS_SCALAR("readWord32OffAddrAsWord32X8#", true, VectorMemoryFamily.WORD32, 32, GeneratedVectors.proofWord32X8, true),
    WRITE_WORD32X8_ADDRESS("writeWord32X8OffAddr#", false, VectorMemoryFamily.WORD32, 32, GeneratedVectors.proofWord32X8, true),
    WRITE_WORD32X8_ADDRESS_SCALAR("writeWord32OffAddrAsWord32X8#", true, VectorMemoryFamily.WORD32, 32, GeneratedVectors.proofWord32X8, true),
    INDEX_INT32X16_ADDRESS("indexInt32X16OffAddr#", false, VectorMemoryFamily.INT32, 64, GeneratedVectors.proofInt32X16, true),
    INDEX_INT32X16_ADDRESS_SCALAR("indexInt32OffAddrAsInt32X16#", true, VectorMemoryFamily.INT32, 64, GeneratedVectors.proofInt32X16, true),
    READ_INT32X16_ADDRESS("readInt32X16OffAddr#", false, VectorMemoryFamily.INT32, 64, GeneratedVectors.proofInt32X16, true),
    READ_INT32X16_ADDRESS_SCALAR("readInt32OffAddrAsInt32X16#", true, VectorMemoryFamily.INT32, 64, GeneratedVectors.proofInt32X16, true),
    WRITE_INT32X16_ADDRESS("writeInt32X16OffAddr#", false, VectorMemoryFamily.INT32, 64, GeneratedVectors.proofInt32X16, true),
    WRITE_INT32X16_ADDRESS_SCALAR("writeInt32OffAddrAsInt32X16#", true, VectorMemoryFamily.INT32, 64, GeneratedVectors.proofInt32X16, true),
    INDEX_WORD32X16_ADDRESS("indexWord32X16OffAddr#", false, VectorMemoryFamily.WORD32, 64, GeneratedVectors.proofWord32X16, true),
    INDEX_WORD32X16_ADDRESS_SCALAR("indexWord32OffAddrAsWord32X16#", true, VectorMemoryFamily.WORD32, 64, GeneratedVectors.proofWord32X16, true),
    READ_WORD32X16_ADDRESS("readWord32X16OffAddr#", false, VectorMemoryFamily.WORD32, 64, GeneratedVectors.proofWord32X16, true),
    READ_WORD32X16_ADDRESS_SCALAR("readWord32OffAddrAsWord32X16#", true, VectorMemoryFamily.WORD32, 64, GeneratedVectors.proofWord32X16, true),
    WRITE_WORD32X16_ADDRESS("writeWord32X16OffAddr#", false, VectorMemoryFamily.WORD32, 64, GeneratedVectors.proofWord32X16, true),
    WRITE_WORD32X16_ADDRESS_SCALAR("writeWord32OffAddrAsWord32X16#", true, VectorMemoryFamily.WORD32, 64, GeneratedVectors.proofWord32X16, true),
    INDEX_INT64X4_ADDRESS("indexInt64X4OffAddr#", false, VectorMemoryFamily.INT64, 32, GeneratedVectors.proofInt64X4, true),
    INDEX_INT64X4_ADDRESS_SCALAR("indexInt64OffAddrAsInt64X4#", true, VectorMemoryFamily.INT64, 32, GeneratedVectors.proofInt64X4, true),
    READ_INT64X4_ADDRESS("readInt64X4OffAddr#", false, VectorMemoryFamily.INT64, 32, GeneratedVectors.proofInt64X4, true),
    READ_INT64X4_ADDRESS_SCALAR("readInt64OffAddrAsInt64X4#", true, VectorMemoryFamily.INT64, 32, GeneratedVectors.proofInt64X4, true),
    WRITE_INT64X4_ADDRESS("writeInt64X4OffAddr#", false, VectorMemoryFamily.INT64, 32, GeneratedVectors.proofInt64X4, true),
    WRITE_INT64X4_ADDRESS_SCALAR("writeInt64OffAddrAsInt64X4#", true, VectorMemoryFamily.INT64, 32, GeneratedVectors.proofInt64X4, true),
    INDEX_WORD64X4_ADDRESS("indexWord64X4OffAddr#", false, VectorMemoryFamily.WORD64, 32, GeneratedVectors.proofWord64X4, true),
    INDEX_WORD64X4_ADDRESS_SCALAR("indexWord64OffAddrAsWord64X4#", true, VectorMemoryFamily.WORD64, 32, GeneratedVectors.proofWord64X4, true),
    READ_WORD64X4_ADDRESS("readWord64X4OffAddr#", false, VectorMemoryFamily.WORD64, 32, GeneratedVectors.proofWord64X4, true),
    READ_WORD64X4_ADDRESS_SCALAR("readWord64OffAddrAsWord64X4#", true, VectorMemoryFamily.WORD64, 32, GeneratedVectors.proofWord64X4, true),
    WRITE_WORD64X4_ADDRESS("writeWord64X4OffAddr#", false, VectorMemoryFamily.WORD64, 32, GeneratedVectors.proofWord64X4, true),
    WRITE_WORD64X4_ADDRESS_SCALAR("writeWord64OffAddrAsWord64X4#", true, VectorMemoryFamily.WORD64, 32, GeneratedVectors.proofWord64X4, true),
    INDEX_INT64X8_ADDRESS("indexInt64X8OffAddr#", false, VectorMemoryFamily.INT64, 64, GeneratedVectors.proofInt64X8, true),
    INDEX_INT64X8_ADDRESS_SCALAR("indexInt64OffAddrAsInt64X8#", true, VectorMemoryFamily.INT64, 64, GeneratedVectors.proofInt64X8, true),
    READ_INT64X8_ADDRESS("readInt64X8OffAddr#", false, VectorMemoryFamily.INT64, 64, GeneratedVectors.proofInt64X8, true),
    READ_INT64X8_ADDRESS_SCALAR("readInt64OffAddrAsInt64X8#", true, VectorMemoryFamily.INT64, 64, GeneratedVectors.proofInt64X8, true),
    WRITE_INT64X8_ADDRESS("writeInt64X8OffAddr#", false, VectorMemoryFamily.INT64, 64, GeneratedVectors.proofInt64X8, true),
    WRITE_INT64X8_ADDRESS_SCALAR("writeInt64OffAddrAsInt64X8#", true, VectorMemoryFamily.INT64, 64, GeneratedVectors.proofInt64X8, true),
    INDEX_WORD64X8_ADDRESS("indexWord64X8OffAddr#", false, VectorMemoryFamily.WORD64, 64, GeneratedVectors.proofWord64X8, true),
    INDEX_WORD64X8_ADDRESS_SCALAR("indexWord64OffAddrAsWord64X8#", true, VectorMemoryFamily.WORD64, 64, GeneratedVectors.proofWord64X8, true),
    READ_WORD64X8_ADDRESS("readWord64X8OffAddr#", false, VectorMemoryFamily.WORD64, 64, GeneratedVectors.proofWord64X8, true),
    READ_WORD64X8_ADDRESS_SCALAR("readWord64OffAddrAsWord64X8#", true, VectorMemoryFamily.WORD64, 64, GeneratedVectors.proofWord64X8, true),
    WRITE_WORD64X8_ADDRESS("writeWord64X8OffAddr#", false, VectorMemoryFamily.WORD64, 64, GeneratedVectors.proofWord64X8, true),
    WRITE_WORD64X8_ADDRESS_SCALAR("writeWord64OffAddrAsWord64X8#", true, VectorMemoryFamily.WORD64, 64, GeneratedVectors.proofWord64X8, true),
    INDEX_FLOATX8_ADDRESS("indexFloatX8OffAddr#", false, VectorMemoryFamily.FLOAT32, 32, GeneratedVectors.proofFloatX8, true),
    INDEX_FLOATX8_ADDRESS_SCALAR("indexFloatOffAddrAsFloatX8#", true, VectorMemoryFamily.FLOAT32, 32, GeneratedVectors.proofFloatX8, true),
    READ_FLOATX8_ADDRESS("readFloatX8OffAddr#", false, VectorMemoryFamily.FLOAT32, 32, GeneratedVectors.proofFloatX8, true),
    READ_FLOATX8_ADDRESS_SCALAR("readFloatOffAddrAsFloatX8#", true, VectorMemoryFamily.FLOAT32, 32, GeneratedVectors.proofFloatX8, true),
    WRITE_FLOATX8_ADDRESS("writeFloatX8OffAddr#", false, VectorMemoryFamily.FLOAT32, 32, GeneratedVectors.proofFloatX8, true),
    WRITE_FLOATX8_ADDRESS_SCALAR("writeFloatOffAddrAsFloatX8#", true, VectorMemoryFamily.FLOAT32, 32, GeneratedVectors.proofFloatX8, true),
    INDEX_FLOATX16_ADDRESS("indexFloatX16OffAddr#", false, VectorMemoryFamily.FLOAT32, 64, GeneratedVectors.proofFloatX16, true),
    INDEX_FLOATX16_ADDRESS_SCALAR("indexFloatOffAddrAsFloatX16#", true, VectorMemoryFamily.FLOAT32, 64, GeneratedVectors.proofFloatX16, true),
    READ_FLOATX16_ADDRESS("readFloatX16OffAddr#", false, VectorMemoryFamily.FLOAT32, 64, GeneratedVectors.proofFloatX16, true),
    READ_FLOATX16_ADDRESS_SCALAR("readFloatOffAddrAsFloatX16#", true, VectorMemoryFamily.FLOAT32, 64, GeneratedVectors.proofFloatX16, true),
    WRITE_FLOATX16_ADDRESS("writeFloatX16OffAddr#", false, VectorMemoryFamily.FLOAT32, 64, GeneratedVectors.proofFloatX16, true),
    WRITE_FLOATX16_ADDRESS_SCALAR("writeFloatOffAddrAsFloatX16#", true, VectorMemoryFamily.FLOAT32, 64, GeneratedVectors.proofFloatX16, true),
    INDEX_DOUBLEX4_ADDRESS("indexDoubleX4OffAddr#", false, VectorMemoryFamily.DOUBLE64, 32, GeneratedVectors.proofDoubleX4, true),
    INDEX_DOUBLEX4_ADDRESS_SCALAR("indexDoubleOffAddrAsDoubleX4#", true, VectorMemoryFamily.DOUBLE64, 32, GeneratedVectors.proofDoubleX4, true),
    READ_DOUBLEX4_ADDRESS("readDoubleX4OffAddr#", false, VectorMemoryFamily.DOUBLE64, 32, GeneratedVectors.proofDoubleX4, true),
    READ_DOUBLEX4_ADDRESS_SCALAR("readDoubleOffAddrAsDoubleX4#", true, VectorMemoryFamily.DOUBLE64, 32, GeneratedVectors.proofDoubleX4, true),
    WRITE_DOUBLEX4_ADDRESS("writeDoubleX4OffAddr#", false, VectorMemoryFamily.DOUBLE64, 32, GeneratedVectors.proofDoubleX4, true),
    WRITE_DOUBLEX4_ADDRESS_SCALAR("writeDoubleOffAddrAsDoubleX4#", true, VectorMemoryFamily.DOUBLE64, 32, GeneratedVectors.proofDoubleX4, true),
    INDEX_DOUBLEX8_ADDRESS("indexDoubleX8OffAddr#", false, VectorMemoryFamily.DOUBLE64, 64, GeneratedVectors.proofDoubleX8, true),
    INDEX_DOUBLEX8_ADDRESS_SCALAR("indexDoubleOffAddrAsDoubleX8#", true, VectorMemoryFamily.DOUBLE64, 64, GeneratedVectors.proofDoubleX8, true),
    READ_DOUBLEX8_ADDRESS("readDoubleX8OffAddr#", false, VectorMemoryFamily.DOUBLE64, 64, GeneratedVectors.proofDoubleX8, true),
    READ_DOUBLEX8_ADDRESS_SCALAR("readDoubleOffAddrAsDoubleX8#", true, VectorMemoryFamily.DOUBLE64, 64, GeneratedVectors.proofDoubleX8, true),
    WRITE_DOUBLEX8_ADDRESS("writeDoubleX8OffAddr#", false, VectorMemoryFamily.DOUBLE64, 64, GeneratedVectors.proofDoubleX8, true),
    WRITE_DOUBLEX8_ADDRESS_SCALAR("writeDoubleOffAddrAsDoubleX8#", true, VectorMemoryFamily.DOUBLE64, 64, GeneratedVectors.proofDoubleX8, true),
    INDEX_INT16X16("indexInt16X16Array#", false, VectorMemoryFamily.INT16, 32, GeneratedVectors.proofInt16X16, false),
    INDEX_INT16X16_SCALAR("indexInt16ArrayAsInt16X16#", true, VectorMemoryFamily.INT16, 32, GeneratedVectors.proofInt16X16, false),
    READ_INT16X16("readInt16X16Array#", false, VectorMemoryFamily.INT16, 32, GeneratedVectors.proofInt16X16, false),
    READ_INT16X16_SCALAR("readInt16ArrayAsInt16X16#", true, VectorMemoryFamily.INT16, 32, GeneratedVectors.proofInt16X16, false),
    WRITE_INT16X16("writeInt16X16Array#", false, VectorMemoryFamily.INT16, 32, GeneratedVectors.proofInt16X16, false),
    WRITE_INT16X16_SCALAR("writeInt16ArrayAsInt16X16#", true, VectorMemoryFamily.INT16, 32, GeneratedVectors.proofInt16X16, false),
    INDEX_WORD16X16("indexWord16X16Array#", false, VectorMemoryFamily.WORD16, 32, GeneratedVectors.proofWord16X16, false),
    INDEX_WORD16X16_SCALAR("indexWord16ArrayAsWord16X16#", true, VectorMemoryFamily.WORD16, 32, GeneratedVectors.proofWord16X16, false),
    READ_WORD16X16("readWord16X16Array#", false, VectorMemoryFamily.WORD16, 32, GeneratedVectors.proofWord16X16, false),
    READ_WORD16X16_SCALAR("readWord16ArrayAsWord16X16#", true, VectorMemoryFamily.WORD16, 32, GeneratedVectors.proofWord16X16, false),
    WRITE_WORD16X16("writeWord16X16Array#", false, VectorMemoryFamily.WORD16, 32, GeneratedVectors.proofWord16X16, false),
    WRITE_WORD16X16_SCALAR("writeWord16ArrayAsWord16X16#", true, VectorMemoryFamily.WORD16, 32, GeneratedVectors.proofWord16X16, false),
    INDEX_INT32X8("indexInt32X8Array#", false, VectorMemoryFamily.INT32, 32, GeneratedVectors.proofInt32X8, false),
    INDEX_INT32X8_SCALAR("indexInt32ArrayAsInt32X8#", true, VectorMemoryFamily.INT32, 32, GeneratedVectors.proofInt32X8, false),
    READ_INT32X8("readInt32X8Array#", false, VectorMemoryFamily.INT32, 32, GeneratedVectors.proofInt32X8, false),
    READ_INT32X8_SCALAR("readInt32ArrayAsInt32X8#", true, VectorMemoryFamily.INT32, 32, GeneratedVectors.proofInt32X8, false),
    WRITE_INT32X8("writeInt32X8Array#", false, VectorMemoryFamily.INT32, 32, GeneratedVectors.proofInt32X8, false),
    WRITE_INT32X8_SCALAR("writeInt32ArrayAsInt32X8#", true, VectorMemoryFamily.INT32, 32, GeneratedVectors.proofInt32X8, false),
    INDEX_WORD32X8("indexWord32X8Array#", false, VectorMemoryFamily.WORD32, 32, GeneratedVectors.proofWord32X8, false),
    INDEX_WORD32X8_SCALAR("indexWord32ArrayAsWord32X8#", true, VectorMemoryFamily.WORD32, 32, GeneratedVectors.proofWord32X8, false),
    READ_WORD32X8("readWord32X8Array#", false, VectorMemoryFamily.WORD32, 32, GeneratedVectors.proofWord32X8, false),
    READ_WORD32X8_SCALAR("readWord32ArrayAsWord32X8#", true, VectorMemoryFamily.WORD32, 32, GeneratedVectors.proofWord32X8, false),
    WRITE_WORD32X8("writeWord32X8Array#", false, VectorMemoryFamily.WORD32, 32, GeneratedVectors.proofWord32X8, false),
    WRITE_WORD32X8_SCALAR("writeWord32ArrayAsWord32X8#", true, VectorMemoryFamily.WORD32, 32, GeneratedVectors.proofWord32X8, false),
    INDEX_INT32X16("indexInt32X16Array#", false, VectorMemoryFamily.INT32, 64, GeneratedVectors.proofInt32X16, false),
    INDEX_INT32X16_SCALAR("indexInt32ArrayAsInt32X16#", true, VectorMemoryFamily.INT32, 64, GeneratedVectors.proofInt32X16, false),
    READ_INT32X16("readInt32X16Array#", false, VectorMemoryFamily.INT32, 64, GeneratedVectors.proofInt32X16, false),
    READ_INT32X16_SCALAR("readInt32ArrayAsInt32X16#", true, VectorMemoryFamily.INT32, 64, GeneratedVectors.proofInt32X16, false),
    WRITE_INT32X16("writeInt32X16Array#", false, VectorMemoryFamily.INT32, 64, GeneratedVectors.proofInt32X16, false),
    WRITE_INT32X16_SCALAR("writeInt32ArrayAsInt32X16#", true, VectorMemoryFamily.INT32, 64, GeneratedVectors.proofInt32X16, false),
    INDEX_WORD32X16("indexWord32X16Array#", false, VectorMemoryFamily.WORD32, 64, GeneratedVectors.proofWord32X16, false),
    INDEX_WORD32X16_SCALAR("indexWord32ArrayAsWord32X16#", true, VectorMemoryFamily.WORD32, 64, GeneratedVectors.proofWord32X16, false),
    READ_WORD32X16("readWord32X16Array#", false, VectorMemoryFamily.WORD32, 64, GeneratedVectors.proofWord32X16, false),
    READ_WORD32X16_SCALAR("readWord32ArrayAsWord32X16#", true, VectorMemoryFamily.WORD32, 64, GeneratedVectors.proofWord32X16, false),
    WRITE_WORD32X16("writeWord32X16Array#", false, VectorMemoryFamily.WORD32, 64, GeneratedVectors.proofWord32X16, false),
    WRITE_WORD32X16_SCALAR("writeWord32ArrayAsWord32X16#", true, VectorMemoryFamily.WORD32, 64, GeneratedVectors.proofWord32X16, false),
    INDEX_INT64X4("indexInt64X4Array#", false, VectorMemoryFamily.INT64, 32, GeneratedVectors.proofInt64X4, false),
    INDEX_INT64X4_SCALAR("indexInt64ArrayAsInt64X4#", true, VectorMemoryFamily.INT64, 32, GeneratedVectors.proofInt64X4, false),
    READ_INT64X4("readInt64X4Array#", false, VectorMemoryFamily.INT64, 32, GeneratedVectors.proofInt64X4, false),
    READ_INT64X4_SCALAR("readInt64ArrayAsInt64X4#", true, VectorMemoryFamily.INT64, 32, GeneratedVectors.proofInt64X4, false),
    WRITE_INT64X4("writeInt64X4Array#", false, VectorMemoryFamily.INT64, 32, GeneratedVectors.proofInt64X4, false),
    WRITE_INT64X4_SCALAR("writeInt64ArrayAsInt64X4#", true, VectorMemoryFamily.INT64, 32, GeneratedVectors.proofInt64X4, false),
    INDEX_WORD64X4("indexWord64X4Array#", false, VectorMemoryFamily.WORD64, 32, GeneratedVectors.proofWord64X4, false),
    INDEX_WORD64X4_SCALAR("indexWord64ArrayAsWord64X4#", true, VectorMemoryFamily.WORD64, 32, GeneratedVectors.proofWord64X4, false),
    READ_WORD64X4("readWord64X4Array#", false, VectorMemoryFamily.WORD64, 32, GeneratedVectors.proofWord64X4, false),
    READ_WORD64X4_SCALAR("readWord64ArrayAsWord64X4#", true, VectorMemoryFamily.WORD64, 32, GeneratedVectors.proofWord64X4, false),
    WRITE_WORD64X4("writeWord64X4Array#", false, VectorMemoryFamily.WORD64, 32, GeneratedVectors.proofWord64X4, false),
    WRITE_WORD64X4_SCALAR("writeWord64ArrayAsWord64X4#", true, VectorMemoryFamily.WORD64, 32, GeneratedVectors.proofWord64X4, false),
    INDEX_INT64X8("indexInt64X8Array#", false, VectorMemoryFamily.INT64, 64, GeneratedVectors.proofInt64X8, false),
    INDEX_INT64X8_SCALAR("indexInt64ArrayAsInt64X8#", true, VectorMemoryFamily.INT64, 64, GeneratedVectors.proofInt64X8, false),
    READ_INT64X8("readInt64X8Array#", false, VectorMemoryFamily.INT64, 64, GeneratedVectors.proofInt64X8, false),
    READ_INT64X8_SCALAR("readInt64ArrayAsInt64X8#", true, VectorMemoryFamily.INT64, 64, GeneratedVectors.proofInt64X8, false),
    WRITE_INT64X8("writeInt64X8Array#", false, VectorMemoryFamily.INT64, 64, GeneratedVectors.proofInt64X8, false),
    WRITE_INT64X8_SCALAR("writeInt64ArrayAsInt64X8#", true, VectorMemoryFamily.INT64, 64, GeneratedVectors.proofInt64X8, false),
    INDEX_WORD64X8("indexWord64X8Array#", false, VectorMemoryFamily.WORD64, 64, GeneratedVectors.proofWord64X8, false),
    INDEX_WORD64X8_SCALAR("indexWord64ArrayAsWord64X8#", true, VectorMemoryFamily.WORD64, 64, GeneratedVectors.proofWord64X8, false),
    READ_WORD64X8("readWord64X8Array#", false, VectorMemoryFamily.WORD64, 64, GeneratedVectors.proofWord64X8, false),
    READ_WORD64X8_SCALAR("readWord64ArrayAsWord64X8#", true, VectorMemoryFamily.WORD64, 64, GeneratedVectors.proofWord64X8, false),
    WRITE_WORD64X8("writeWord64X8Array#", false, VectorMemoryFamily.WORD64, 64, GeneratedVectors.proofWord64X8, false),
    WRITE_WORD64X8_SCALAR("writeWord64ArrayAsWord64X8#", true, VectorMemoryFamily.WORD64, 64, GeneratedVectors.proofWord64X8, false),
    INDEX_FLOATX8("indexFloatX8Array#", false, VectorMemoryFamily.FLOAT32, 32, GeneratedVectors.proofFloatX8, false),
    INDEX_FLOATX8_SCALAR("indexFloatArrayAsFloatX8#", true, VectorMemoryFamily.FLOAT32, 32, GeneratedVectors.proofFloatX8, false),
    READ_FLOATX8("readFloatX8Array#", false, VectorMemoryFamily.FLOAT32, 32, GeneratedVectors.proofFloatX8, false),
    READ_FLOATX8_SCALAR("readFloatArrayAsFloatX8#", true, VectorMemoryFamily.FLOAT32, 32, GeneratedVectors.proofFloatX8, false),
    WRITE_FLOATX8("writeFloatX8Array#", false, VectorMemoryFamily.FLOAT32, 32, GeneratedVectors.proofFloatX8, false),
    WRITE_FLOATX8_SCALAR("writeFloatArrayAsFloatX8#", true, VectorMemoryFamily.FLOAT32, 32, GeneratedVectors.proofFloatX8, false),
    INDEX_FLOATX16("indexFloatX16Array#", false, VectorMemoryFamily.FLOAT32, 64, GeneratedVectors.proofFloatX16, false),
    INDEX_FLOATX16_SCALAR("indexFloatArrayAsFloatX16#", true, VectorMemoryFamily.FLOAT32, 64, GeneratedVectors.proofFloatX16, false),
    READ_FLOATX16("readFloatX16Array#", false, VectorMemoryFamily.FLOAT32, 64, GeneratedVectors.proofFloatX16, false),
    READ_FLOATX16_SCALAR("readFloatArrayAsFloatX16#", true, VectorMemoryFamily.FLOAT32, 64, GeneratedVectors.proofFloatX16, false),
    WRITE_FLOATX16("writeFloatX16Array#", false, VectorMemoryFamily.FLOAT32, 64, GeneratedVectors.proofFloatX16, false),
    WRITE_FLOATX16_SCALAR("writeFloatArrayAsFloatX16#", true, VectorMemoryFamily.FLOAT32, 64, GeneratedVectors.proofFloatX16, false),
    INDEX_DOUBLEX4("indexDoubleX4Array#", false, VectorMemoryFamily.DOUBLE64, 32, GeneratedVectors.proofDoubleX4, false),
    INDEX_DOUBLEX4_SCALAR("indexDoubleArrayAsDoubleX4#", true, VectorMemoryFamily.DOUBLE64, 32, GeneratedVectors.proofDoubleX4, false),
    READ_DOUBLEX4("readDoubleX4Array#", false, VectorMemoryFamily.DOUBLE64, 32, GeneratedVectors.proofDoubleX4, false),
    READ_DOUBLEX4_SCALAR("readDoubleArrayAsDoubleX4#", true, VectorMemoryFamily.DOUBLE64, 32, GeneratedVectors.proofDoubleX4, false),
    WRITE_DOUBLEX4("writeDoubleX4Array#", false, VectorMemoryFamily.DOUBLE64, 32, GeneratedVectors.proofDoubleX4, false),
    WRITE_DOUBLEX4_SCALAR("writeDoubleArrayAsDoubleX4#", true, VectorMemoryFamily.DOUBLE64, 32, GeneratedVectors.proofDoubleX4, false),
    INDEX_DOUBLEX8("indexDoubleX8Array#", false, VectorMemoryFamily.DOUBLE64, 64, GeneratedVectors.proofDoubleX8, false),
    INDEX_DOUBLEX8_SCALAR("indexDoubleArrayAsDoubleX8#", true, VectorMemoryFamily.DOUBLE64, 64, GeneratedVectors.proofDoubleX8, false),
    READ_DOUBLEX8("readDoubleX8Array#", false, VectorMemoryFamily.DOUBLE64, 64, GeneratedVectors.proofDoubleX8, false),
    READ_DOUBLEX8_SCALAR("readDoubleArrayAsDoubleX8#", true, VectorMemoryFamily.DOUBLE64, 64, GeneratedVectors.proofDoubleX8, false),
    WRITE_DOUBLEX8("writeDoubleX8Array#", false, VectorMemoryFamily.DOUBLE64, 64, GeneratedVectors.proofDoubleX8, false),
    WRITE_DOUBLEX8_SCALAR("writeDoubleArrayAsDoubleX8#", true, VectorMemoryFamily.DOUBLE64, 64, GeneratedVectors.proofDoubleX8, false),
    INDEX_INT8_ADDRESS("indexInt8X16OffAddr#", false, VectorMemoryFamily.INT8, 16, null, true),
    INDEX_INT8_ADDRESS_SCALAR("indexInt8OffAddrAsInt8X16#", true, VectorMemoryFamily.INT8, 16, null, true),
    READ_INT8_ADDRESS("readInt8X16OffAddr#", false, VectorMemoryFamily.INT8, 16, null, true),
    READ_INT8_ADDRESS_SCALAR("readInt8OffAddrAsInt8X16#", true, VectorMemoryFamily.INT8, 16, null, true),
    WRITE_INT8_ADDRESS("writeInt8X16OffAddr#", false, VectorMemoryFamily.INT8, 16, null, true),
    WRITE_INT8_ADDRESS_SCALAR("writeInt8OffAddrAsInt8X16#", true, VectorMemoryFamily.INT8, 16, null, true),
    INDEX_WORD8_ADDRESS("indexWord8X16OffAddr#", false, VectorMemoryFamily.WORD8, 16, null, true),
    INDEX_WORD8_ADDRESS_SCALAR("indexWord8OffAddrAsWord8X16#", true, VectorMemoryFamily.WORD8, 16, null, true),
    READ_WORD8_ADDRESS("readWord8X16OffAddr#", false, VectorMemoryFamily.WORD8, 16, null, true),
    READ_WORD8_ADDRESS_SCALAR("readWord8OffAddrAsWord8X16#", true, VectorMemoryFamily.WORD8, 16, null, true),
    WRITE_WORD8_ADDRESS("writeWord8X16OffAddr#", false, VectorMemoryFamily.WORD8, 16, null, true),
    WRITE_WORD8_ADDRESS_SCALAR("writeWord8OffAddrAsWord8X16#", true, VectorMemoryFamily.WORD8, 16, null, true),
    INDEX_INT16_ADDRESS("indexInt16X8OffAddr#", false, VectorMemoryFamily.INT16, 16, null, true),
    INDEX_INT16_ADDRESS_SCALAR("indexInt16OffAddrAsInt16X8#", true, VectorMemoryFamily.INT16, 16, null, true),
    READ_INT16_ADDRESS("readInt16X8OffAddr#", false, VectorMemoryFamily.INT16, 16, null, true),
    READ_INT16_ADDRESS_SCALAR("readInt16OffAddrAsInt16X8#", true, VectorMemoryFamily.INT16, 16, null, true),
    WRITE_INT16_ADDRESS("writeInt16X8OffAddr#", false, VectorMemoryFamily.INT16, 16, null, true),
    WRITE_INT16_ADDRESS_SCALAR("writeInt16OffAddrAsInt16X8#", true, VectorMemoryFamily.INT16, 16, null, true),
    INDEX_WORD16_ADDRESS("indexWord16X8OffAddr#", false, VectorMemoryFamily.WORD16, 16, null, true),
    INDEX_WORD16_ADDRESS_SCALAR("indexWord16OffAddrAsWord16X8#", true, VectorMemoryFamily.WORD16, 16, null, true),
    READ_WORD16_ADDRESS("readWord16X8OffAddr#", false, VectorMemoryFamily.WORD16, 16, null, true),
    READ_WORD16_ADDRESS_SCALAR("readWord16OffAddrAsWord16X8#", true, VectorMemoryFamily.WORD16, 16, null, true),
    WRITE_WORD16_ADDRESS("writeWord16X8OffAddr#", false, VectorMemoryFamily.WORD16, 16, null, true),
    WRITE_WORD16_ADDRESS_SCALAR("writeWord16OffAddrAsWord16X8#", true, VectorMemoryFamily.WORD16, 16, null, true),
    INDEX_INT64_ADDRESS("indexInt64X2OffAddr#", false, VectorMemoryFamily.INT64, 16, null, true),
    INDEX_INT64_ADDRESS_SCALAR("indexInt64OffAddrAsInt64X2#", true, VectorMemoryFamily.INT64, 16, null, true),
    READ_INT64_ADDRESS("readInt64X2OffAddr#", false, VectorMemoryFamily.INT64, 16, null, true),
    READ_INT64_ADDRESS_SCALAR("readInt64OffAddrAsInt64X2#", true, VectorMemoryFamily.INT64, 16, null, true),
    WRITE_INT64_ADDRESS("writeInt64X2OffAddr#", false, VectorMemoryFamily.INT64, 16, null, true),
    WRITE_INT64_ADDRESS_SCALAR("writeInt64OffAddrAsInt64X2#", true, VectorMemoryFamily.INT64, 16, null, true),
    INDEX_WORD64_ADDRESS("indexWord64X2OffAddr#", false, VectorMemoryFamily.WORD64, 16, null, true),
    INDEX_WORD64_ADDRESS_SCALAR("indexWord64OffAddrAsWord64X2#", true, VectorMemoryFamily.WORD64, 16, null, true),
    READ_WORD64_ADDRESS("readWord64X2OffAddr#", false, VectorMemoryFamily.WORD64, 16, null, true),
    READ_WORD64_ADDRESS_SCALAR("readWord64OffAddrAsWord64X2#", true, VectorMemoryFamily.WORD64, 16, null, true),
    WRITE_WORD64_ADDRESS("writeWord64X2OffAddr#", false, VectorMemoryFamily.WORD64, 16, null, true),
    WRITE_WORD64_ADDRESS_SCALAR("writeWord64OffAddrAsWord64X2#", true, VectorMemoryFamily.WORD64, 16, null, true),
    INDEX_INT8("indexInt8X16Array#", false, VectorMemoryFamily.INT8, 16, null, false),
    INDEX_INT8_SCALAR("indexInt8ArrayAsInt8X16#", true, VectorMemoryFamily.INT8, 16, null, false),
    READ_INT8("readInt8X16Array#", false, VectorMemoryFamily.INT8, 16, null, false),
    READ_INT8_SCALAR("readInt8ArrayAsInt8X16#", true, VectorMemoryFamily.INT8, 16, null, false),
    WRITE_INT8("writeInt8X16Array#", false, VectorMemoryFamily.INT8, 16, null, false),
    WRITE_INT8_SCALAR("writeInt8ArrayAsInt8X16#", true, VectorMemoryFamily.INT8, 16, null, false),
    INDEX_WORD8("indexWord8X16Array#", false, VectorMemoryFamily.WORD8, 16, null, false),
    INDEX_WORD8_SCALAR("indexWord8ArrayAsWord8X16#", true, VectorMemoryFamily.WORD8, 16, null, false),
    READ_WORD8("readWord8X16Array#", false, VectorMemoryFamily.WORD8, 16, null, false),
    READ_WORD8_SCALAR("readWord8ArrayAsWord8X16#", true, VectorMemoryFamily.WORD8, 16, null, false),
    WRITE_WORD8("writeWord8X16Array#", false, VectorMemoryFamily.WORD8, 16, null, false),
    WRITE_WORD8_SCALAR("writeWord8ArrayAsWord8X16#", true, VectorMemoryFamily.WORD8, 16, null, false),
    INDEX_INT16("indexInt16X8Array#", false, VectorMemoryFamily.INT16, 16, null, false),
    INDEX_INT16_SCALAR("indexInt16ArrayAsInt16X8#", true, VectorMemoryFamily.INT16, 16, null, false),
    READ_INT16("readInt16X8Array#", false, VectorMemoryFamily.INT16, 16, null, false),
    READ_INT16_SCALAR("readInt16ArrayAsInt16X8#", true, VectorMemoryFamily.INT16, 16, null, false),
    WRITE_INT16("writeInt16X8Array#", false, VectorMemoryFamily.INT16, 16, null, false),
    WRITE_INT16_SCALAR("writeInt16ArrayAsInt16X8#", true, VectorMemoryFamily.INT16, 16, null, false),
    INDEX_WORD16("indexWord16X8Array#", false, VectorMemoryFamily.WORD16, 16, null, false),
    INDEX_WORD16_SCALAR("indexWord16ArrayAsWord16X8#", true, VectorMemoryFamily.WORD16, 16, null, false),
    READ_WORD16("readWord16X8Array#", false, VectorMemoryFamily.WORD16, 16, null, false),
    READ_WORD16_SCALAR("readWord16ArrayAsWord16X8#", true, VectorMemoryFamily.WORD16, 16, null, false),
    WRITE_WORD16("writeWord16X8Array#", false, VectorMemoryFamily.WORD16, 16, null, false),
    WRITE_WORD16_SCALAR("writeWord16ArrayAsWord16X8#", true, VectorMemoryFamily.WORD16, 16, null, false),
    INDEX_INT64("indexInt64X2Array#", false, VectorMemoryFamily.INT64, 16, null, false),
    INDEX_INT64_SCALAR("indexInt64ArrayAsInt64X2#", true, VectorMemoryFamily.INT64, 16, null, false),
    READ_INT64("readInt64X2Array#", false, VectorMemoryFamily.INT64, 16, null, false),
    READ_INT64_SCALAR("readInt64ArrayAsInt64X2#", true, VectorMemoryFamily.INT64, 16, null, false),
    WRITE_INT64("writeInt64X2Array#", false, VectorMemoryFamily.INT64, 16, null, false),
    WRITE_INT64_SCALAR("writeInt64ArrayAsInt64X2#", true, VectorMemoryFamily.INT64, 16, null, false),
    INDEX_WORD64("indexWord64X2Array#", false, VectorMemoryFamily.WORD64, 16, null, false),
    INDEX_WORD64_SCALAR("indexWord64ArrayAsWord64X2#", true, VectorMemoryFamily.WORD64, 16, null, false),
    READ_WORD64("readWord64X2Array#", false, VectorMemoryFamily.WORD64, 16, null, false),
    READ_WORD64_SCALAR("readWord64ArrayAsWord64X2#", true, VectorMemoryFamily.WORD64, 16, null, false),
    WRITE_WORD64("writeWord64X2Array#", false, VectorMemoryFamily.WORD64, 16, null, false),
    WRITE_WORD64_SCALAR("writeWord64ArrayAsWord64X2#", true, VectorMemoryFamily.WORD64, 16, null, false),
    INDEX("indexInt32X4Array#", false, VectorMemoryFamily.INT32, 16, null, false),
    INDEX_SCALAR("indexInt32ArrayAsInt32X4#", true, VectorMemoryFamily.INT32, 16, null, false),
    READ("readInt32X4Array#", false, VectorMemoryFamily.INT32, 16, null, false),
    READ_SCALAR("readInt32ArrayAsInt32X4#", true, VectorMemoryFamily.INT32, 16, null, false),
    WRITE("writeInt32X4Array#", false, VectorMemoryFamily.INT32, 16, null, false),
    WRITE_SCALAR("writeInt32ArrayAsInt32X4#", true, VectorMemoryFamily.INT32, 16, null, false),
    INDEX_WORD("indexWord32X4Array#", false, VectorMemoryFamily.WORD32, 16, null, false),
    INDEX_WORD_SCALAR("indexWord32ArrayAsWord32X4#", true, VectorMemoryFamily.WORD32, 16, null, false),
    READ_WORD("readWord32X4Array#", false, VectorMemoryFamily.WORD32, 16, null, false),
    READ_WORD_SCALAR("readWord32ArrayAsWord32X4#", true, VectorMemoryFamily.WORD32, 16, null, false),
    WRITE_WORD("writeWord32X4Array#", false, VectorMemoryFamily.WORD32, 16, null, false),
    WRITE_WORD_SCALAR("writeWord32ArrayAsWord32X4#", true, VectorMemoryFamily.WORD32, 16, null, false),
    INDEX_FLOAT("indexFloatX4Array#", false, VectorMemoryFamily.FLOAT32, 16, null, false),
    INDEX_FLOAT_SCALAR("indexFloatArrayAsFloatX4#", true, VectorMemoryFamily.FLOAT32, 16, null, false),
    READ_FLOAT("readFloatX4Array#", false, VectorMemoryFamily.FLOAT32, 16, null, false),
    READ_FLOAT_SCALAR("readFloatArrayAsFloatX4#", true, VectorMemoryFamily.FLOAT32, 16, null, false),
    WRITE_FLOAT("writeFloatX4Array#", false, VectorMemoryFamily.FLOAT32, 16, null, false),
    WRITE_FLOAT_SCALAR("writeFloatArrayAsFloatX4#", true, VectorMemoryFamily.FLOAT32, 16, null, false),
    INDEX_DOUBLE("indexDoubleX2Array#", false, VectorMemoryFamily.DOUBLE64, 16, null, false),
    INDEX_DOUBLE_SCALAR("indexDoubleArrayAsDoubleX2#", true, VectorMemoryFamily.DOUBLE64, 16, null, false),
    READ_DOUBLE("readDoubleX2Array#", false, VectorMemoryFamily.DOUBLE64, 16, null, false),
    READ_DOUBLE_SCALAR("readDoubleArrayAsDoubleX2#", true, VectorMemoryFamily.DOUBLE64, 16, null, false),
    WRITE_DOUBLE("writeDoubleX2Array#", false, VectorMemoryFamily.DOUBLE64, 16, null, false),
    WRITE_DOUBLE_SCALAR("writeDoubleArrayAsDoubleX2#", true, VectorMemoryFamily.DOUBLE64, 16, null, false);

    private final String primitive;
    private final boolean scalarOffset;
    private final VectorMemoryFamily family;
    private final int vectorBytes;
    private final CoreRepresentation wideProof;
    private final boolean address;
    private final boolean read;
    private final boolean write;
    private final boolean index;

    VectorMemoryOp(String primitive, boolean scalarOffset, VectorMemoryFamily family,
            int vectorBytes, CoreRepresentation wideProof, boolean address) {
        this.primitive = primitive;
        this.scalarOffset = scalarOffset;
        this.family = family;
        this.vectorBytes = vectorBytes;
        this.wideProof = wideProof;
        this.address = address;
        read = primitive.startsWith("read");
        write = primitive.startsWith("write");
        index = primitive.startsWith("index");
    }
    public String getPrimitive() { return primitive; }
    public boolean getScalarOffset() { return scalarOffset; }
    public VectorMemoryFamily getFamily() { return family; }
    public int getVectorBytes() { return vectorBytes; }
    public boolean isAddress() { return address; }
    public boolean isRead() { return read; }
    public boolean isWrite() { return write; }
    public boolean isIndex() { return index; }
    public CoreRepresentation getVectorProof() { return wideProof != null ? wideProof : family.getVectorProof(); }

    public void validateArguments(List<CoreRepresentation> actual, List<?> flags) {
        var storage = address ? CoreVectorMemory.addressProof : CoreVectorMemory.arrayProof;
        var expected = read ? List.of(storage, CoreVectorMemory.indexProof, CoreVectorMemory.stateProof)
            : write ? List.of(storage, CoreVectorMemory.indexProof, getVectorProof(), CoreVectorMemory.stateProof)
            : List.of(storage, CoreVectorMemory.indexProof);
        if (actual.size() != expected.size() || flags.size() != expected.size())
            throw new RuntimeFault("Vector memory primitive argument representation mismatch: " + primitive);
        for (Object flag : flags) if (!Boolean.FALSE.equals(flag))
            throw new RuntimeFault("Vector memory primitive argument representation mismatch: " + primitive);
        for (int i = 0; i < expected.size(); i++) {
            var proof = actual.get(i);
            boolean matches = address && i == 1
                ? proof.getPresent() && !proof.isAggregate() && proof.getKind() == CoreKind.LONG
                : CoreVectorMemory.exact(expected.get(i), proof);
            if (!matches)
                throw new RuntimeFault("Vector memory primitive argument representation mismatch: " + primitive);
        }
    }
    public void validate(List<CoreRepresentation> actual, List<?> flags, CoreRepresentation result) {
        if (read) throw new UnsupportedCore("Vector memory read requires an immediate exact case");
        validateArguments(actual, flags);
        if (!CoreVectorMemory.exact(write ? CoreVectorMemory.stateProof : getVectorProof(), result))
            throw new RuntimeFault("Vector memory primitive result representation mismatch: " + primitive);
    }
    public static VectorMemoryOp named(String name) {
        for (var operation : values()) if (operation.primitive.equals(name)) return operation;
        return null;
    }
}
