// SPDX-FileCopyrightText: 2026 Edward Kmett
// SPDX-License-Identifier: UPL-1.0 AND BSD-3-Clause
package thc.runtime;

import com.oracle.truffle.api.RootCallTarget;
import com.oracle.truffle.api.TruffleLanguage;
import com.oracle.truffle.api.Truffle;
import com.oracle.truffle.api.bytecode.BytecodeConfig;
import com.oracle.truffle.api.bytecode.ContinuationResult;
import com.oracle.truffle.api.frame.FrameDescriptor;
import com.oracle.truffle.api.frame.FrameSlotKind;
import com.oracle.truffle.api.frame.MaterializedFrame;
import com.oracle.truffle.api.frame.VirtualFrame;
import com.oracle.truffle.api.nodes.Node;
import com.oracle.truffle.api.nodes.NodeUtil;
import org.graalvm.polyglot.Context;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import thc.CoreModules;
import thc.EntryValue;
import thc.Json;
import thc.Language;
import java.io.File;
import java.nio.file.Files;
import java.security.MessageDigest;
import java.util.*;
import java.util.concurrent.atomic.AtomicReference;
import static org.junit.jupiter.api.Assertions.*;

@Timeout(120)
@SuppressWarnings("unchecked")
class DelimitedContinuationsTest {
    private final File root = new File(System.getProperty("thc.projectRoot"));
    private final List<String> entries = List.of("promptPure", "abortSuffix", "resumeTwice", "nestedPrompts", "sameTagNearest", "capturedCatch", "capturedMask", "escapedResume", "ambientMask", "resumedTail", "resumedJoin", "resumedScalar", "recapturedMask", "resumedApplication", "resumedScalarApplication", "polymorphicApplications", "polymorphicScalarApplications");
    private final Map<String, Long> calls = Map.ofEntries(Map.entry("promptPure", 3L), Map.entry("abortSuffix", 4L), Map.entry("resumeTwice", 6L), Map.entry("nestedPrompts", 7L), Map.entry("sameTagNearest", 5L), Map.entry("capturedCatch", 7L), Map.entry("capturedMask", 7L), Map.entry("escapedResume", 6L), Map.entry("ambientMask", 7L), Map.entry("resumedTail", 6L), Map.entry("resumedJoin", 5L), Map.entry("resumedScalar", 6L), Map.entry("recapturedMask", 10L), Map.entry("resumedApplication", 7L), Map.entry("resumedScalarApplication", 7L), Map.entry("polymorphicApplications", 22L), Map.entry("polymorphicScalarApplications", 22L));
    private static <T> T single(List<T> values) { if (values.isEmpty()) throw new NoSuchElementException("List is empty."); if (values.size() != 1) throw new IllegalArgumentException("List has more than one element."); return values.getFirst(); }
    private List<Long> provenance() throws Exception {
        var manifest = (Map<?, ?>) Json.parse(Files.readString(new File(root, "build/delimited-continuations/manifest.json").toPath())); assertEquals(entries, manifest.get("entries"));
        for (String group : List.of("inputHashes", "artifactHashes")) for (var row : ((Map<?, ?>) manifest.get(group)).entrySet()) { byte[] bytes = Files.readAllBytes(new File(root, (String) row.getKey()).toPath()); assertEquals(row.getValue(), HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(bytes)), (String) row.getKey()); }
        var nativeResults = new ArrayList<Long>(); for (var value : (List<?>) manifest.get("native")) nativeResults.add(((Number) value).longValue()); var model = new ArrayList<Long>(); for (long n : new long[]{-2, 0, 7}) for (String entry : entries) model.add(expected(entry, n)); assertEquals(model, nativeResults, "Independent arithmetic/state model agrees with actual native GHC"); return nativeResults;
    }
    private long expected(String entry, long n) { return switch (entry) {
        case "promptPure" -> n + 7; case "abortSuffix" -> n; case "resumeTwice" -> ((n + 1) * 100 + (n + 4)) * 10 + 3; case "nestedPrompts" -> n + 111; case "sameTagNearest" -> n + 100; case "capturedCatch" -> n + 17; case "capturedMask" -> n + 21; case "escapedResume" -> 2 * n + 14; case "ambientMask" -> n; case "resumedTail", "resumedJoin", "resumedScalar", "resumedApplication", "resumedScalarApplication" -> n + 117; case "polymorphicApplications", "polymorphicScalarApplications" -> 4 * n + 174; case "recapturedMask" -> n + 1; default -> throw new IllegalStateException(entry);
    }; }
    @Test void originalCoreRunsSavedSuffixesOnBothBackends() throws Exception { runEntries(entries, true); }
    @Test void unsplitFourTargetApplicationsExerciseBothGenericResultPaths() throws Exception { runEntries(List.of("polymorphicApplications", "polymorphicScalarApplications"), false); }
    private void runEntries(List<String> selected, boolean splitting) throws Exception {
        var nativeResults = provenance();
        for (String stage : List.of("pre", "post")) for (String backend : List.of("ast", "bytecode")) for (String entry : selected) try (var context = Context.newBuilder("thc").allowExperimentalOptions(true).option("engine.WarnInterpreterOnly", "false").option("compiler.Inlining", "false").option("engine.BackgroundCompilation", "false").option("engine.Splitting", Boolean.toString(splitting)).option("engine.MultiTier", "false").option("engine.SingleTierCompilationThreshold", "10000000").option("engine.CompilationFailureAction", "Throw").build()) {
            context.initialize("thc"); context.enter(); try {
                var module = (Map<String, Object>) Json.parse(Files.readString(new File(root, "build/delimited-continuations/" + stage + "/core/DelimitedContinuations.json").toPath())); var language = TruffleLanguage.LanguageReference.create(Language.class).get(null); var linked = CoreModules.reachable(module, entry); var source = new ArrayCoreEvidence(module, entry); var nodes = new ArrayList<List<?>>(); for (var binding : source.getBindings()) nodes.addAll(source.nodes(binding.get("expr"))); var joins = Collections.newSetFromMap(new IdentityHashMap<List<?>, Boolean>());
                for (var node : nodes) if (!node.isEmpty() && "let".equals(node.getFirst())) for (var raw : (List<?>) node.get(2)) { var binding = (Map<?, ?>) raw; if (!(binding.get("joinValueArity") instanceof Number arity)) continue; var rhs = (List<?>) binding.get("expr"); assertEquals("lam", rhs.get(0)); assertEquals(arity.intValue(), ((List<?>) rhs.get(1)).size()); joins.add(rhs); }
                var lambdas = new ArrayList<List<?>>(); for (var node : nodes) if (!node.isEmpty() && "lam".equals(node.getFirst()) && !joins.contains(node)) lambdas.add(node); boolean polymorphic = Set.of("polymorphicApplications", "polymorphicScalarApplications").contains(entry); assertEquals(polymorphic ? 19L : calls.get(entry), (long) lambdas.size(), "Every reachable lambda runs once, except applyWorker runs four times; resumes never restart them");
                // The exported runRW# wrapper is now beta-reduced during
                // lowering. Prove that exact single State# application from
                // original Core, independently of runtime target discovery.
                var entryLambda = (List<?>) source.getRoot().get("expr"); var stateCall = (List<?>) entryLambda.get(2); assertEquals("app", stateCall.get(0)); assertEquals(List.of(List.of(false), false, false), stateCall.subList(3, 6)); var stateLambda = (List<?>) stateCall.get(1); assertEquals("lam", stateLambda.get(0)); var stateFormal = (Map<?, ?>) single((List<?>) stateLambda.get(1)); var voidRep = Map.of("primReps", List.of(), "kind", "void", "evaluated", true); assertEquals("State# RealWorld", stateFormal.get("type")); assertEquals(false, stateFormal.get("lifted")); assertEquals(false, stateFormal.get("coercion")); assertEquals(voidRep, stateFormal.get("rep")); var stateArgument = (List<?>) single((List<?>) stateCall.get(2)); assertEquals("void", stateArgument.get(0)); assertEquals(voidRep, ((Map<?, ?>) stateArgument.getLast()).get("rep"));
                var immediateLambdas = new ArrayList<List<?>>(); for (var node : nodes) if (!node.isEmpty() && "app".equals(node.getFirst()) && node.size() > 1 && node.get(1) instanceof List<?> fn && !fn.isEmpty() && "lam".equals(fn.getFirst())) immediateLambdas.add(node); assertEquals(1, immediateLambdas.size(), "Exactly one immediate lambda can be eliminated"); assertSame(stateCall, single(immediateLambdas)); boolean containsState = false; for (var lambda : lambdas) if (lambda == stateLambda) { containsState = true; break; } assertTrue(containsState); var executableLambdas = new ArrayList<List<?>>(); for (var lambda : lambdas) if (lambda != stateLambda) executableLambdas.add(lambda);
                var workers = Set.of("applicationWorker", "applicationWorker2", "applicationWorker3", "applicationWorker4", "scalarApplicationWorker", "scalarApplicationWorker2", "scalarApplicationWorker3", "scalarApplicationWorker4");
                for (var worker : source.getBindings()) if (workers.contains(worker.get("name"))) { assertEquals(2, ((Number) worker.get("arity")).intValue(), "A genuine overapplication, not an eta-expanded worker"); var lambda = (List<?>) worker.get("expr"); assertEquals(2, ((List<?>) lambda.get(1)).size()); var body = (List<?>) lambda.get(2); assertEquals("case", body.get(0)); var returned = (List<?>) ((List<?>) single((List<?>) body.get(3))).get(3); assertEquals("lam", returned.get(0)); assertEquals(1, ((List<?>) returned.get(1)).size()); }
                if (polymorphic) {
                    var matching = new ArrayList<Map<String, Object>>(); for (var binding : source.getBindings()) if (Objects.equals(binding.get("name"), entry.equals("polymorphicApplications") ? "applyWorker" : "applyScalarWorker")) matching.add(binding); var apply = single(matching); var formals = (List<Map<?, ?>>) ((List<?>) apply.get("expr")).get(1); var names = new ArrayList<Object>(); for (var formal : formals) names.add(formal.get("name")); assertEquals(List.of("worker", "tag", "n", "s"), names); var body = (List<?>) ((List<?>) apply.get("expr")).get(2); var call = Objects.equals(body.get(0), "case") ? (List<?>) body.get(1) : body; var fn = (List<?>) call.get(1); assertEquals(Arrays.asList("var", formals.getFirst().get("id")), fn.subList(0, Math.min(2, fn.size()))); assertEquals(3, ((List<?>) call.get(2)).size()); int applications = 0; for (var node : nodes) if (!node.isEmpty() && "app".equals(node.getFirst()) && node.size() > 1 && node.get(1) instanceof List<?> function && function.subList(0, Math.min(2, function.size())).equals(Arrays.asList("var", apply.get("id")))) applications++; assertEquals(4, applications);
                }
                ExecutableProgram program = backend.equals("ast") ? new Program(language, linked) : new BytecodeProgram(language, linked); assertTrue(((GuestRoot) program.entryTarget(entry).getRootNode()).getDelimitedControlEnabled(), stage + "/" + backend + "/" + entry + ": root policy is prepared before the first guest call"); var function = context.asValue(new EntryValue(program, entry, 1)); long[] inputs = {-2, 0, 7};
                for (int index = 0; index < inputs.length; index++) { long n = inputs[index]; assertEquals(nativeResults.get(index * entries.size() + entries.indexOf(entry)), function.execute(n).asLong(), stage + "/" + backend + "/" + entry + "/" + n); var handoff = language.getHandoffState().get(); assertEquals(0, handoff.getArguments().getDepth()); assertEquals(0, handoff.getResults().getDepth()); assertEquals(0, handoff.getArguments().retainedReferences()); assertEquals(0, handoff.getResults().retainedReferences()); assertNull(handoff.getPending()); assertEquals(MaskingState.UNMASKED, Language.currentState(null).getMaskingState().get()); }
                // Megamorphic calls do not retain the fourth target in a
                // DirectCallNode. Seed all actual global lambdas, as the
                // thread inventory's floated-child proof already does.
                var seen = Collections.newSetFromMap(new IdentityHashMap<RootCallTarget, Boolean>()); var targets = new ArrayList<RootCallTarget>(); for (var binding : source.getBindings()) if (Objects.equals(((List<?>) binding.get("expr")).get(0), "lam")) for (var target : ThreadInventoryCoreEvidence.targets(program.entryTarget((String) binding.get("id")))) if ((target.getRootNode() instanceof FunctionRoot || target.getRootNode() instanceof BytecodeRoot) && seen.add(target)) targets.add(target);
                var labels = new ArrayList<String>(); for (var lambda : executableLambdas) { var names = new ArrayList<String>(); for (var formal : (List<?>) lambda.get(1)) names.add(Objects.toString(((Map<?, ?>) formal).get("name"))); labels.add("lambda " + String.join(", ", names)); } Collections.sort(labels); var functions = new ArrayList<RootCallTarget>(); for (var target : targets) if (target.getRootNode().getName().startsWith("lambda ")) functions.add(target);
                // Truffle may split the higher-order helper at its four
                // callers. Install every clone, but compare source bodies
                // using the runtime's existing exact clone identity.
                var bodies = new ArrayList<RootCallTarget>(); for (var target : functions) { boolean duplicate = false; for (var body : bodies) if (((GuestRoot) body.getRootNode()).isSelf(target)) { duplicate = true; break; } if (!duplicate) bodies.add(target); }
                var bodyLabels = new ArrayList<String>(); for (var body : bodies) bodyLabels.add(body.getRootNode().getName()); Collections.sort(bodyLabels); assertEquals(labels, bodyLabels, stage + "/" + backend + "/" + entry + " exact source function bodies"); var cafLabels = new LinkedHashSet<Object>(); for (var binding : source.getBindings()) if (!Objects.equals(((List<?>) binding.get("expr")).get(0), "lam")) cafLabels.add(binding.get("name")); for (var target : targets) if (!functions.contains(target)) assertTrue(cafLabels.contains(target.getRootNode().getName()), "Only already-forced source CAFs may accompany the exact function inventory");
                long before = ((Number) program.diagnostics().get("compiledEntries")).longValue(); var interpreted = ThreadInventoryCoreEvidence.interpretedCalls(targets); try { ThreadInventoryCoreEvidence.install(targets); } catch (Throwable failure) { throw new AssertionError(stage + "/" + backend + "/" + entry + " first installation", failure); } assertTrue(function.invokeMember("compile").asBoolean()); assertEquals(before, ((Number) program.diagnostics().get("compiledEntries")).longValue()); var handoff = language.getHandoffState().get(); var allocations = List.of(handoff.getArguments().getAllocations(), handoff.getResults().getAllocations()); assertEquals(expected(entry, 11), function.execute(11L).asLong(), stage + "/" + backend + "/" + entry + " first installed call"); assertEquals(calls.get(entry) - 1, ((Number) program.diagnostics().get("compiledEntries")).longValue() - before, stage + "/" + backend + "/" + entry + ": resumes do not restart original Core roots"); assertEquals(interpreted, ThreadInventoryCoreEvidence.interpretedCalls(targets), "No interpreted settling call"); ThreadInventoryCoreEvidence.released(language); assertEquals(allocations, List.of(handoff.getArguments().getAllocations(), handoff.getResults().getAllocations())); assertEquals(MaskingState.UNMASKED, Language.currentState(null).getMaskingState().get());
            } finally { context.leave(); }
        }
    }
    @Test void rootPoliciesArePreparedWithoutExecutingBodiesAndRetainedByClones() {
        try (var context = Context.newBuilder("thc").build()) { context.initialize("thc"); context.enter(); try {
            var language = TruffleLanguage.LanguageReference.create(Language.class).get(null);
            for (boolean enabled : new boolean[]{false, true}) {
                var body = new Expr() { @Override public Object execute(VirtualFrame frame) { throw new IllegalStateException("Metadata preparation executed guest code"); } }; var source = new FunctionRoot(language, new FrameLayout().build(), "unexecuted policy", null, new int[0], new int[0], new int[0], body, new Metrics(false), new CoreRepresentation[0], body.getRepresentation(), body.getCoreSourceLocation(), new boolean[0], null, null, new int[0], null, false, new int[0][], enabled, FunctionRootRole.FUNCTION, false); var clone = NodeUtil.cloneNode(source);
                for (var root : List.of(source, clone)) { assertSame(root, root.getCallTarget().getRootNode()); assertEquals(enabled, root.getDelimitedControlEnabled()); assertEquals(enabled, DelimitedControl.enabled(root)); }
            }
            var other = new GuestRoot(language, FrameDescriptor.newBuilder().build()) { @Override public long bloom(VirtualFrame frame) { return 0L; } @Override public Object execute(VirtualFrame frame) { throw new IllegalStateException("Metadata preparation executed guest code"); } }; other.getCallTarget(); assertFalse(DelimitedControl.enabled(other), "Unrecognized roots do not gain continuation authority"); var state = new CoreRepresentation(CoreKind.VOID, false, false, List.of(), null, null, null, null, null); var value = new CoreRepresentation(CoreKind.OBJECT, false, false, List.of("BoxedRep (Just Lifted)"), null, null, null, null, null); var shape = new TupleShape(new CoreRepresentation(CoreKind.UNKNOWN, false, false, value.getPrimReps(), List.of(state, value), null, null, null, null), language);
            var cut = new DelimitedCut(new PromptTag(Language.currentState(null)), null, shape, MaskingState.UNMASKED, other); var continuation = (GuestRoot) new DelimitedStack(cut, shape).closure(language, new Metrics(false)).target.getRootNode(); assertTrue(continuation.getDelimitedControlEnabled()); assertTrue(DelimitedControl.enabled(continuation)); ThreadInventoryCoreEvidence.released(language);
        } finally { context.leave(); } }
    }
    @Test void liveAndSavedCatchAcknowledgeEachSelfRequestAndKeepItsPayloadLazy() {
        try (var context = Context.newBuilder("thc").build()) { context.initialize("thc"); context.enter(); try {
            var language = TruffleLanguage.LanguageReference.create(Language.class).get(null); var threads = Language.currentState().getThreads(); var state = new CoreRepresentation(CoreKind.VOID, false, false, List.of(), null, null, null, null, null); var value = new CoreRepresentation(CoreKind.OBJECT, false, false, List.of("BoxedRep (Just Lifted)"), null, null, null, null, null); var shape = new TupleShape(new CoreRepresentation(CoreKind.UNKNOWN, false, false, value.getPrimReps(), List.of(state, value), null, null, null, null), language); var payload = new Thunk(new GuestRoot(language, new FrameLayout().build()) { @Override public long bloom(VirtualFrame frame) { return 0L; } @Override public Object execute(VirtualFrame frame) { throw new IllegalStateException("Delimited catch forced the payload"); } }.getCallTarget(), null); var deliveryTarget = new AtomicReference<GuestThreadId>(); var seen = new AtomicReference<AsyncRequest>();
            class Model { int calls; MaskingState handlerMask = MaskingState.UNMASKED; boolean failHandler, redeliver; } var model = new Model(); var handlerFailure = new RuntimeFault("handler failure");
            var action = new Closure(null, 1, new GuestRoot(language, new FrameLayout().build()) { { configureEntry(new boolean[]{false}, false); configureTupleResult(shape); } @Override public long bloom(VirtualFrame frame) { return 0L; } @Override public Object execute(VirtualFrame frame) { try { return GuestThreadOps.killSelf(this, deliveryTarget.get(), payload); } catch (AsyncDelivery delivered) { seen.set(delivered.getRequest()); throw delivered; /* Preserve the real async-origin control object. */ } } }.getCallTarget());
            var handler = new Closure(null, 2, new GuestRoot(language, new FrameLayout().build()) {
                { configureEntry(new boolean[]{false, false}, false); configureTupleResult(shape); } @Override public long bloom(VirtualFrame frame) { return 0L; }
                @Override public Object execute(VirtualFrame frame) { model.calls++; assertSame(payload, frame.getArguments()[1]); assertSame(payload, seen.get().getPayload()); assertEquals(AsyncRequestState.ACKNOWLEDGED, seen.get().getState()); assertEquals(model.handlerMask, SynchronousMasking.current(this)); if (model.failHandler) throw handlerFailure; if (model.redeliver) { model.redeliver = false; try { GuestThreadOps.killSelf(this, deliveryTarget.get(), payload); } catch (AsyncDelivery delivered) { seen.set(delivered.getRequest()); throw delivered; } } var result = shape.getLayout().create(); shape.getLayout().setObject(result, 0, payload); return result; }
            }.getCallTarget());
            class CatchRoot extends GuestRoot {
                @Child private DelimitedActionSite site = new DelimitedActionSite(language, new Metrics(false));
                CatchRoot() { super(language, new FrameLayout().build()); } @Override public long bloom(VirtualFrame frame) { return 0L; } @Override public Object execute(VirtualFrame frame) { return site.caught(frame, action, handler, thc.runtime.Unit.INSTANCE, shape); }
                DelimitedStack save() { return save(1); }
                DelimitedStack save(int catches) { var frame = Truffle.getRuntime().createMaterializedFrame(new Object[]{0L}, getFrameDescriptor()); var cut = new DelimitedCut(new PromptTag(Language.currentState(this)), null, shape, SynchronousMasking.current(this), this); for (int i = 0; i < catches; i++) cut.getFrames().add(new DelimitedFrame(frame, new DelimitedCatchStep(site, handler, shape))); return new DelimitedStack(cut, shape); }
                Object resumeSaved(DelimitedStack stack) { var frame = Truffle.getRuntime().createMaterializedFrame(new Object[]{0L}, getFrameDescriptor()); return stack.resume(site, frame, action); }
            }
            var root = new CatchRoot(); threads.enterCurrent(null, false, false, null);
            try {
                var self = threads.currentIdentity(); deliveryTarget.set(self);
                for (var mask : MaskingState.values()) { SynchronousMasking.set(root, mask); model.handlerMask = mask == MaskingState.UNMASKED ? MaskingState.MASKED_INTERRUPTIBLE : mask; var result = (HandoffStorage) Calls.target(root.getCallTarget(), new Object[]{0L}); assertSame(payload, shape.getLayout().getObject(result, 0)); assertTrue(seen.get().getForceSelf()); assertEquals(self.getLogicalId(), seen.get().getTargetId()); assertEquals(mask, SynchronousMasking.current(root)); assertNull(threads.poll(root, false)); assertEquals(0, payload.getState()); }
                assertEquals(3, model.calls, "Exactly one handler invocation per self request"); SynchronousMasking.set(root, MaskingState.UNMASKED); model.handlerMask = MaskingState.MASKED_INTERRUPTIBLE; model.failHandler = true; assertSame(handlerFailure, assertThrows(RuntimeFault.class, () -> Calls.target(root.getCallTarget(), new Object[]{0L}))); assertEquals(MaskingState.UNMASKED, SynchronousMasking.current(root)); assertEquals(4, model.calls);
                // Reuse the SAME immutable image, never the one-shot request.
                model.failHandler = false; var saved = root.save(); var previous = seen.get();
                for (var mask : MaskingState.values()) { SynchronousMasking.set(root, mask); model.handlerMask = mask == MaskingState.UNMASKED ? MaskingState.MASKED_INTERRUPTIBLE : mask; for (int i = 0; i < 2; i++) { var result = (HandoffStorage) root.resumeSaved(saved); assertSame(payload, shape.getLayout().getObject(result, 0)); assertNotSame(previous, seen.get(), "Every self send owns a fresh request"); assertEquals(AsyncRequestState.ACKNOWLEDGED, previous.getState()); assertEquals(AsyncRequestState.ACKNOWLEDGED, seen.get().getState()); assertEquals(self.getLogicalId(), seen.get().getTargetId()); assertTrue(seen.get().getForceSelf()); assertEquals(mask, SynchronousMasking.current(root)); assertNull(threads.poll(root, false)); assertEquals(0, payload.getState()); previous = seen.get(); } } assertEquals(10, model.calls);
                // The inner saved handler acknowledges its request before
                // throwing a new self request to the outer saved handler.
                SynchronousMasking.set(root, MaskingState.UNMASKED); model.handlerMask = MaskingState.MASKED_INTERRUPTIBLE; model.redeliver = true; assertSame(payload, shape.getLayout().getObject((HandoffStorage) root.resumeSaved(root.save(2)), 0)); assertEquals(12, model.calls); assertEquals(AsyncRequestState.ACKNOWLEDGED, seen.get().getState()); assertEquals(MaskingState.UNMASKED, SynchronousMasking.current(root));
                // With no saved catch, preserve the original delivery for an
                // outer handler; neither the image nor its runner may ACK it.
                SynchronousMasking.set(root, MaskingState.MASKED_UNINTERRUPTIBLE); var escaped = assertThrows(AsyncDelivery.class, () -> root.resumeSaved(root.save(0))); assertSame(seen.get(), escaped.getRequest()); assertTrue(escaped.getRequest().getForceSelf()); assertEquals(AsyncRequestState.CLAIMED, escaped.getRequest().getState()); assertEquals(12, model.calls, "Uncaught delivery must not become GuestException"); assertEquals(MaskingState.MASKED_UNINTERRUPTIBLE, SynchronousMasking.current(root)); escaped.getRequest().acknowledge(); SynchronousMasking.set(root, MaskingState.UNMASKED);
                // The same carrier may host a distinct callback identity.
                // Its external send must not enter the caller's mailbox or handler.
                var foreign = threads.enterForeign(ForeignSafety.SAFE); try { threads.enterCurrent(null, false, false, null); try { assertNotSame(self, threads.currentIdentity()); assertThrows(UnsupportedCore.class, () -> Calls.target(root.getCallTarget(), new Object[]{0L})); assertEquals(12, model.calls); } finally { threads.leaveCurrent(GuestThreadStatus.FINISHED); } } finally { threads.leaveForeign(foreign); }
                assertSame(self, threads.currentIdentity()); assertNull(threads.poll(root, false), "Rejected external send never entered the mailbox"); assertEquals(0, payload.getState()); ThreadInventoryCoreEvidence.released(language);
            } finally { threads.leaveCurrent(GuestThreadStatus.FINISHED); }
        } finally { context.leave(); } }
    }
    private static void joinSender(Thread sender) {
        try { sender.join(5000); } catch (InterruptedException failure) { DelimitedContinuationsTest.<RuntimeException>rethrow(failure); }
    }
    @SuppressWarnings("unchecked") private static <T extends Throwable> void rethrow(Throwable failure) throws T { throw (T) failure; }
    @Test void savedExternalDeliveryKeepsTheAbandonedChildOneShotAndTheImageReusable() {
        try (var context = Context.create("thc")) { context.initialize("thc"); context.enter(); try {
            var language = TruffleLanguage.LanguageReference.create(Language.class).get(null); var threads = Language.currentState().getThreads(); var state = new CoreRepresentation(CoreKind.VOID, false, false, List.of(), null, null, null, null, null); var value = new CoreRepresentation(CoreKind.OBJECT, false, false, List.of("BoxedRep (Just Lifted)"), null, null, null, null, null); var shape = new TupleShape(new CoreRepresentation(CoreKind.UNKNOWN, false, false, value.getPrimReps(), List.of(state, value), null, null, null, null), language); var payload = new Object(); var requests = new ArrayList<AsyncRequest>(); var children = new ArrayList<AstContinuation>(); int[] resumedChildren = {0}, handled = {0};
            var action = new Closure(null, 1, new GuestRoot(language, new FrameLayout().build()) {
                { configureEntry(new boolean[]{false}, false); configureTupleResult(shape); } @Override public long bloom(VirtualFrame frame) { return 0L; }
                @Override public Object execute(VirtualFrame frame) { long target = threads.currentId(); var submitted = new AtomicReference<AsyncRequest>(); var sender = new Thread(() -> submitted.set(threads.send(target, payload))); sender.start(); joinSender(sender); assertFalse(sender.isAlive()); var request = Objects.requireNonNull(threads.poll(this, true)); assertSame(submitted.get(), request); assertFalse(request.getForceSelf()); requests.add(request);
                    var child = new AstCapture(request, SynchronousMasking.current(this)).append(new AstResumeStep() { @Override public Object resume(VirtualFrame frame, Object input) { assertSame(thc.runtime.Unit.INSTANCE, input); resumedChildren[0]++; return thc.runtime.Unit.INSTANCE; } }).freeze(this, frame.materialize()); children.add(child); return child;
                }
            }.getCallTarget());
            var handler = new Closure(null, 2, new GuestRoot(language, new FrameLayout().build()) {
                { configureEntry(new boolean[]{false, false}, false); configureTupleResult(shape); } @Override public long bloom(VirtualFrame frame) { return 0L; }
                @Override public Object execute(VirtualFrame frame) { handled[0]++; assertSame(payload, frame.getArguments()[1]); assertEquals(AsyncRequestState.ACKNOWLEDGED, requests.getLast().getState()); assertEquals(MaskingState.MASKED_INTERRUPTIBLE, SynchronousMasking.current(this)); var result = shape.getLayout().create(); shape.getLayout().setObject(result, 0, payload); return result; }
            }.getCallTarget());
            class ImageRoot extends GuestRoot {
                @Child private DelimitedActionSite site = new DelimitedActionSite(language, new Metrics(false));
                ImageRoot() { super(language, new FrameLayout().build()); } @Override public long bloom(VirtualFrame frame) { return 0L; } @Override public Object execute(VirtualFrame frame) { throw new IllegalStateException("model root is not an action"); }
                DelimitedStack image() { return image(true); }
                DelimitedStack image(boolean caught) { var frame = Truffle.getRuntime().createMaterializedFrame(new Object[]{0L}, getFrameDescriptor()); var cut = new DelimitedCut(new PromptTag(Language.currentState(this)), null, shape, MaskingState.UNMASKED, this); if (caught) cut.getFrames().add(new DelimitedFrame(frame, new DelimitedCatchStep(site, handler, shape))); return new DelimitedStack(cut, shape); }
                Object resume(DelimitedStack image) { return image.resume(site, Truffle.getRuntime().createMaterializedFrame(new Object[]{0L}, getFrameDescriptor()), action); }
                Object deliver(AsyncRequest request) { return site.handleException(Truffle.getRuntime().createMaterializedFrame(new Object[]{0L}, getFrameDescriptor()), handler, new AsyncDelivery(request, this), shape); }
            }
            var root = new ImageRoot(); threads.enterCurrent(null, false, true, null);
            try {
                var image = root.image(); for (int i = 0; i < 2; i++) { var result = (HandoffStorage) root.resume(image); assertSame(payload, shape.getLayout().getObject(result, 0)); assertEquals(MaskingState.UNMASKED, SynchronousMasking.current(root)); }
                assertEquals(2, handled[0]); assertNotSame(requests.get(0), requests.get(1)); assertNotSame(children.get(0), children.get(1)); assertEquals(0, resumedChildren[0], "Catch abandons each interrupted child, not the reusable image"); assertThrows(IllegalStateException.class, () -> root.deliver(requests.get(0))); Calls.target(action.target, new Object[]{0L, thc.runtime.Unit.INSTANCE}); var pending = requests.getLast(); var foreign = threads.enterForeign(ForeignSafety.SAFE);
                try { threads.enterCurrent(null, false, true, null); try { assertNotEquals(pending.getTargetId(), threads.currentId()); assertThrows(IllegalStateException.class, () -> root.deliver(pending)); assertEquals(AsyncRequestState.CLAIMED, pending.getState()); } finally { threads.leaveCurrent(GuestThreadStatus.FINISHED); } } finally { threads.leaveForeign(foreign); }
                root.deliver(pending); assertEquals(AsyncRequestState.ACKNOWLEDGED, pending.getState()); var escaped = assertThrows(AsyncDelivery.class, () -> root.resume(root.image(false))); assertSame(requests.getLast(), escaped.getRequest()); assertEquals(AsyncRequestState.CLAIMED, escaped.getRequest().getState()); assertEquals(3, handled[0], "Only a reached catch acknowledges the original delivery"); escaped.getRequest().acknowledge();
                for (var child : children) { assertSame(thc.runtime.Unit.INSTANCE, child.continueWith(thc.runtime.Unit.INSTANCE)); assertThrows(RuntimeFault.class, () -> child.continueWith(thc.runtime.Unit.INSTANCE)); } assertEquals(4, resumedChildren[0], "An independent owner may resume each child once only"); assertEquals(3, handled[0]); assertNull(threads.poll(root, false));
            } finally { threads.leaveCurrent(GuestThreadStatus.FINISHED); }
        } finally { context.leave(); } }
    }
    @Test void eachImageInvocationDrainsItsOwnCutsAndNeverStoresTheirOwners() {
        try (var context = Context.newBuilder("thc").allowExperimentalOptions(true).option("engine.Compilation", "false").build()) { context.initialize("thc"); context.enter(); try {
            var language = TruffleLanguage.LanguageReference.create(Language.class).get(null); var threads = Language.currentState().getThreads(); var state = new CoreRepresentation(CoreKind.VOID, false, false, List.of(), null, null, null, null, null); var value = new CoreRepresentation(CoreKind.OBJECT, false, false, List.of("BoxedRep (Just Lifted)"), null, null, null, null, null); var shape = new TupleShape(new CoreRepresentation(CoreKind.UNKNOWN, false, false, value.getPrimReps(), List.of(state, value), null, null, null, null), language); var payload = new Object(); var children = new ArrayList<AstContinuation>(); var requests = new ArrayList<AsyncRequest>(); int[] effects = {0}, handled = {0}, mode = {0};
            var handler = new Closure(null, 2, new GuestRoot(language, new FrameLayout().build()) {
                { configureEntry(new boolean[]{false, false}, false); configureTupleResult(shape); } @Override public long bloom(VirtualFrame frame) { return 0L; }
                @Override public Object execute(VirtualFrame frame) { handled[0]++; assertSame(payload, frame.getArguments()[1]); assertEquals(AsyncRequestState.ACKNOWLEDGED, requests.getLast().getState()); assertEquals(MaskingState.MASKED_INTERRUPTIBLE, SynchronousMasking.current(this)); var result = shape.getLayout().create(); shape.getLayout().setObject(result, 0, payload); return result; }
            }.getCallTarget());
            class ImageRoot extends GuestRoot {
                @Child private DelimitedActionSite site = new DelimitedActionSite(language, new Metrics(false));
                ImageRoot() { super(language, new FrameLayout().build()); configureEntry(new boolean[]{false}, false); configureTupleResult(shape); } @Override public long bloom(VirtualFrame frame) { return 0L; }
                AstContinuation cut(VirtualFrame frame, Object marker, java.util.function.Supplier<Object> next) { var child = new AstCapture(marker, SynchronousMasking.current(this)).append(new AstResumeStep() { @Override public Object resume(VirtualFrame frame, Object input) { assertSame(thc.runtime.Unit.INSTANCE, input); effects[0]++; return next.get(); } }).freeze(this, frame.materialize()); children.add(child); return child; }
                @Override public Object execute(VirtualFrame frame) { return cut(frame, AstStackSpill.INSTANCE, () -> switch (mode[0]) {
                    case 0 -> cut(frame, thc.runtime.Unit.INSTANCE, () -> { var result = shape.getLayout().create(); shape.getLayout().setObject(result, 0, payload); return result; });
                    case 1 -> { var submitted = new AtomicReference<AsyncRequest>(); long target = threads.currentId(); var sender = new Thread(() -> submitted.set(threads.send(target, payload))); sender.start(); joinSender(sender); assertFalse(sender.isAlive()); var request = Objects.requireNonNull(threads.poll(this, true)); assertSame(submitted.get(), request); requests.add(request); yield cut(frame, request, () -> { throw new IllegalStateException("A reached catch must not resume its abandoned child"); }); }
                    case 2 -> throw new DelimitedCut(new PromptTag(Language.currentState(this)), null, shape, SynchronousMasking.current(this), this);
                    default -> cut(frame, new DelimitedCut(new PromptTag(Language.currentState(this)), null, shape, SynchronousMasking.current(this), this), () -> { throw new IllegalStateException("A recapture marker is not a Unit cut"); });
                }); }
                DelimitedStack image() {
                    var node = this; var frame = Truffle.getRuntime().createMaterializedFrame(new Object[]{0L}, getFrameDescriptor()); var cut = new DelimitedCut(new PromptTag(Language.currentState(this)), null, shape, MaskingState.UNMASKED, this);
                    cut.getFrames().add(new DelimitedFrame(frame, new DelimitedStep() { @Override public Object resume(MaterializedFrame frame, DelimitedResume input, MaskingState ambient, DelimitedStep outerMask) { var result = input.get(); throw new AstCapture(AstStackSpill.INSTANCE, SynchronousMasking.current(node)).append(new AstResumeStep() { @Override public Object resume(VirtualFrame frame, Object input) { assertSame(thc.runtime.Unit.INSTANCE, input); effects[0]++; return result; } }); } })); cut.getFrames().add(new DelimitedFrame(frame, new DelimitedCatchStep(site, handler, shape))); return new DelimitedStack(cut, shape);
                }
                Object resume(DelimitedStack image) { return image.resume(site, Truffle.getRuntime().createMaterializedFrame(new Object[]{0L}, getFrameDescriptor()), new Closure(null, 1, getCallTarget())); }
            }
            var root = new ImageRoot(); threads.enterCurrent(null, false, true, null);
            try {
                var image = root.image(); for (int i = 0; i < 2; i++) { var answer = (HandoffStorage) root.resume(image); assertSame(payload, shape.getLayout().getObject(answer, 0)); } assertEquals(6, effects[0], "Two action cuts and the saved suffix run once per invocation"); assertEquals(4, children.size()); for (var child : children) assertThrows(RuntimeFault.class, () -> child.continueWith(thc.runtime.Unit.INSTANCE)); mode[0] = 1; for (int i = 0; i < 2; i++) assertSame(payload, shape.getLayout().getObject((HandoffStorage) root.resume(image), 0)); assertEquals(8, effects[0], "Delivery must not replay or resume the interrupted action"); assertEquals(2, handled[0]); assertNotSame(requests.get(0), requests.get(1)); boolean allAcknowledged = true; for (var request : requests) if (request.getState() != AsyncRequestState.ACKNOWLEDGED) { allAcknowledged = false; break; } assertTrue(allAcknowledged);
                for (int recapture = 2; recapture <= 3; recapture++) { mode[0] = recapture; assertEquals("control0# cannot recapture a parked one-shot invocation chain", assertThrows(UnsupportedCore.class, () -> root.resume(image)).getMessage()); } mode[0] = 0; assertSame(payload, shape.getLayout().getObject((HandoffStorage) root.resume(image), 0)); assertEquals(MaskingState.UNMASKED, SynchronousMasking.current(root)); assertEquals(0, AstStacks.astStackScope(root).getDepth()); assertNull(threads.poll(root, false));
            } finally { threads.leaveCurrent(GuestThreadStatus.FINISHED); }
        } finally { context.leave(); } }
    }
    @Test void savedBytecodeSuffixDrainsRepeatedUnitCutsInFreshOwners() {
        try (var context = Context.newBuilder("thc").allowExperimentalOptions(true).option("engine.Compilation", "false").build()) { context.initialize("thc"); context.enter(); try {
            var language = TruffleLanguage.LanguageReference.create(Language.class).get(null); var state = new CoreRepresentation(CoreKind.VOID, false, false, List.of(), null, null, null, null, null); var value = new CoreRepresentation(CoreKind.OBJECT, false, false, List.of("BoxedRep (Just Lifted)"), null, null, null, null, null); var shape = new TupleShape(new CoreRepresentation(CoreKind.UNKNOWN, false, false, value.getPrimReps(), List.of(state, value), null, null, null, null), language); var marker = new Object(); var answer = shape.getLayout().create(); shape.getLayout().setObject(answer, 0, marker);
            class Owner extends GuestRoot {
                @Child private DelimitedActionSite site = new DelimitedActionSite(language, new Metrics(false));
                Owner() { super(language, new FrameLayout().build()); configureEntry(new boolean[]{false}, false); configureTupleResult(shape); } @Override public long bloom(VirtualFrame frame) { return 0L; } @Override public Object execute(VirtualFrame frame) { return answer; }
                Object resume(DelimitedStack image) { return resume(image, new Closure(null, 1, getCallTarget())); }
                Object resume(DelimitedStack image, Object action) { return image.resume(site, Truffle.getRuntime().createMaterializedFrame(new Object[]{0L}, getFrameDescriptor()), action); }
                Object finish(Object result, RootCallTarget target) { return site.finish(result, shape, target); }
            }
            var owner = new Owner(); var cut = new DelimitedCut(new PromptTag(Language.currentState()), null, shape, MaskingState.UNMASKED, owner);
            var bytecode = BytecodeRootGen.create(language, BytecodeConfig.DEFAULT, b -> { b.beginRoot(); b.beginYield(); b.emitLoadConstant(cut); b.endYield(); for (int i = 0; i < 2; i++) { b.beginYield(); b.emitLoadConstant(thc.runtime.Unit.INSTANCE); b.endYield(); } b.beginReturn(); b.emitLoadConstant(answer); b.endReturn(); b.endRoot(); }).getNode(0); bytecode.configureTupleResult(shape); var saved = (ContinuationResult) Calls.target(bytecode.getCallTarget(), new Object[]{0L}); assertSame(cut, saved.getResult()); cut.append(saved.getFrame(), new DelimitedBytecodeStep(saved, shape)); var image = new DelimitedStack(cut, shape); for (int i = 0; i < 2; i++) assertSame(marker, shape.getLayout().getObject((HandoffStorage) owner.resume(image), 0));
            var closure = new Closure(null, 1, owner.getCallTarget()); var head = BytecodeRootGen.create(language, BytecodeConfig.DEFAULT, b -> { b.beginRoot(); for (int i = 0; i < 2; i++) { b.beginYield(); b.emitLoadConstant(thc.runtime.Unit.INSTANCE); b.endYield(); } b.beginReturn(); b.emitLoadConstant(closure); b.endReturn(); b.endRoot(); }).getNode(0); var lazyAction = new Thunk(head.getCallTarget(), null);
            for (int i = 0; i < 2; i++) { assertSame(marker, shape.getLayout().getObject((HandoffStorage) owner.resume(image, lazyAction), 0)); assertEquals(2, lazyAction.getState()); assertSame(closure, lazyAction.getValue()); assertNull(lazyAction.getOwner()); }
            var unrelated = saved.continueWith(new DelimitedResume(answer)); assertEquals("Delimited invocation returned an unrelated continuation", assertThrows(RuntimeFault.class, () -> owner.finish(unrelated, owner.getCallTarget())).getMessage()); assertEquals(MaskingState.UNMASKED, SynchronousMasking.current(owner)); assertEquals(0, language.getHandoffState().get().getResults().getDepth());
        } finally { context.leave(); } }
    }
    @Test void savedScalarJoinTransferRetainsCompletionAfterScheduling() { scheduledJoinTransfer(false, false); }
    @Test void savedTupleJoinTransferRetainsCompletionAfterScheduling() { scheduledJoinTransfer(true, false); }
    @Test void savedScalarJoinTransferRetainsItsNextLexicalJump() { scheduledJoinTransfer(false, true); }
    @Test void savedTupleJoinTransferRetainsItsNextLexicalJump() { scheduledJoinTransfer(true, true); }
    private void scheduledJoinTransfer(boolean tupleResult, boolean nextJump) {
        try (var context = Context.newBuilder("thc").allowExperimentalOptions(true).option("engine.Compilation", "false").build()) { context.initialize("thc"); context.enter(); try {
            var language = TruffleLanguage.LanguageReference.create(Language.class).get(null); var longRep = new CoreRepresentation(CoreKind.LONG, true, true, List.of("IntRep"), null, null, null, null, null); var tupleProof = new CoreRepresentation(CoreKind.UNKNOWN, true, true, longRep.getPrimReps(), List.of(longRep), null, null, null, null); var shape = new TupleShape(tupleProof, language); var layout = new FrameLayout(); int selector = layout.bind("join selector"), result = layout.bind("join scalar result"), source = layout.bind("join private tuple"), destination = layout.bind("join caller tuple"); var group = new Object(); var targets = new ArrayList<LocalJoinTarget>(); for (int i = 1; i <= 2; i++) targets.add(new LocalJoinTarget(group, i, new int[0], new CoreRepresentation[0])); var events = new ArrayList<String>();
            var initial = new Expr() {
                @Override public Object execute(VirtualFrame frame) { events.add("capture"); throw new DelimitedCut(new PromptTag(Language.currentState()), null, shape, SynchronousMasking.current(this), this).append(frame, new DelimitedStep() { @Override public Object resume(MaterializedFrame frame, DelimitedResume input, MaskingState ambient, DelimitedStep outerMask) { input.get(); throw targets.get(0).getJump(); } }); }
                @Override public long executeLong(VirtualFrame frame) { return (Long) execute(frame); }
                @Override public Object executeTuple(VirtualFrame frame, int[] slots, int offset) { return execute(frame); }
            };
            var scheduled = new Expr() {
                private Object cut(int[] slots, int offset) { events.add("join prefix"); throw new AstCapture(AstStackSpill.INSTANCE, SynchronousMasking.current(this)).append(new AstResumeStep() { @Override public Object resume(VirtualFrame frame, Object input) { assertSame(thc.runtime.Unit.INSTANCE, input); events.add("join suffix"); if (nextJump) throw targets.get(1).getJump(); if (slots == null) return 42L; FrameAccess.writeLong(frame, slots[offset], 42L); return null; } }); }
                @Override public Object execute(VirtualFrame frame) { return cut(null, 0); }
                @Override public long executeLong(VirtualFrame frame) { return (Long) cut(null, 0); }
                @Override public Object executeTuple(VirtualFrame frame, int[] slots, int offset) { return cut(slots, offset); }
            };
            var after = new Expr() { @Override public Object execute(VirtualFrame frame) { return executeLong(frame); } @Override public long executeLong(VirtualFrame frame) { events.add("second join"); return 43L; } @Override public Object executeTuple(VirtualFrame frame, int[] slots, int offset) { FrameAccess.writeLong(frame, slots[offset], executeLong(frame)); return null; } };
            class Owner extends GuestRoot {
                @Child private LocalJoinRegion region = new LocalJoinRegion(group, selector, result, new Expr[]{initial, scheduled, after}, tupleResult ? tupleProof : longRep, nextJump, tupleResult ? shape : null, tupleResult ? new int[]{source} : new int[0], true);
                @Child private DelimitedActionSite site = new DelimitedActionSite(language, new Metrics(false));
                Owner() { super(language, layout.build()); } @Override public long bloom(VirtualFrame frame) { return 0L; }
                @Override public Object execute(VirtualFrame frame) { FrameAccess.writeLong(frame, destination, -99L); return tupleResult ? region.executeTuple(frame, new int[]{destination}, 0) : region.execute(frame); }
                Object resume(DelimitedStack image, Closure action) { return image.resume(site, Truffle.getRuntime().createMaterializedFrame(new Object[]{0L}, getFrameDescriptor()), action); }
            }
            var owner = new Owner(); var cut = assertThrows(DelimitedCut.class, () -> Calls.target(owner.getCallTarget(), new Object[]{0L})); if (tupleResult) cut.getFrames().add(new DelimitedFrame(cut.getFrames().getLast().getFrame(), new DelimitedStep() { @Override public Object resume(MaterializedFrame frame, DelimitedResume input, MaskingState ambient, DelimitedStep outerMask) { input.get(); return frame.getLong(destination); } })); var image = new DelimitedStack(cut, shape);
            var action = new Closure(null, 1, new GuestRoot(language, new FrameLayout().build()) { { configureEntry(new boolean[]{false}, false); configureTupleResult(shape); } @Override public long bloom(VirtualFrame frame) { return 0L; } @Override public Object execute(VirtualFrame frame) { var result = shape.getLayout().create(); shape.getLayout().setLong(result, 0, 7L); return result; } }.getCallTarget());
            for (int i = 0; i < 2; i++) assertEquals(nextJump ? 43L : 42L, owner.resume(image, action)); var one = new ArrayList<>(List.of("join prefix", "join suffix")); if (nextJump) one.add("second join"); var expected = new ArrayList<>(List.of("capture")); expected.addAll(one); expected.addAll(one); assertEquals(expected, events); assertEquals(MaskingState.UNMASKED, SynchronousMasking.current(owner)); assertEquals(0, language.getHandoffState().get().getResults().getDepth());
        } finally { context.leave(); } }
    }
    @Test void savedRootTransferDetachesItsTupleBeforeTheNextSavedStep() {
        try (var context = Context.newBuilder("thc").allowExperimentalOptions(true).option("engine.Compilation", "false").build()) { context.initialize("thc"); context.enter(); try {
            var language = TruffleLanguage.LanguageReference.create(Language.class).get(null); var longRep = new CoreRepresentation(CoreKind.LONG, true, true, List.of("IntRep"), null, null, null, null, null); var proof = new CoreRepresentation(CoreKind.UNKNOWN, true, true, longRep.getPrimReps(), List.of(longRep), null, null, null, null); var shape = new TupleShape(proof, language); var layout = new FrameLayout(); int slot = layout.bind("root tuple result"); int[] effects = {0};
            var body = new Expr() {
                { setRepresentation(proof); } @Override public Object execute(VirtualFrame frame) { throw new IllegalStateException("tuple-only model"); }
                @Override public Object executeTuple(VirtualFrame frame, int[] slots, int offset) { effects[0]++; throw new AstCapture(AstStackSpill.INSTANCE, SynchronousMasking.current(this)).append(new AstResumeStep() { @Override public Object resume(VirtualFrame frame, Object input) { assertSame(thc.runtime.Unit.INSTANCE, input); FrameAccess.writeLong(frame, slots[offset], 42L); return null; } }); }
            };
            var function = new FunctionRoot(language, layout.build(), "saved tuple root", null, new int[0], new int[0], new int[0], body, new Metrics(false), new CoreRepresentation[0], proof, body.getCoreSourceLocation(), new boolean[0], null, shape, new int[]{slot}, null, true, new int[0][], true, FunctionRootRole.FUNCTION, false); function.getCallTarget(); // Adopt the real FunctionBody and its completion step.
            class Owner extends GuestRoot {
                @Child private DelimitedActionSite site = new DelimitedActionSite(language, new Metrics(false));
                Owner() { super(language, new FrameLayout().build()); configureEntry(new boolean[]{false}, false); configureTupleResult(shape); } @Override public long bloom(VirtualFrame frame) { return 0L; }
                @Override public Object execute(VirtualFrame frame) { var result = shape.getLayout().create(); shape.getLayout().setLong(result, 0, 7L); return result; }
                Object resume(DelimitedStack image) { return image.resume(site, Truffle.getRuntime().createMaterializedFrame(new Object[]{0L}, getFrameDescriptor()), new Closure(null, 1, getCallTarget())); }
            }
            var owner = new Owner(); var frame = Truffle.getRuntime().createMaterializedFrame(new Object[]{0L}, function.getFrameDescriptor()); var cut = new DelimitedCut(new PromptTag(Language.currentState()), null, shape, MaskingState.UNMASKED, owner);
            cut.getFrames().add(new DelimitedFrame(frame, new DelimitedStep() { @Override public Object resume(MaterializedFrame frame, DelimitedResume input, MaskingState ambient, DelimitedStep outerMask) { input.get(); throw AstSelfCall.INSTANCE; } })); cut.getFrames().add(new DelimitedFrame(frame, new DelimitedRootStep(function)));
            cut.getFrames().add(new DelimitedFrame(frame, new DelimitedStep() { @Override public Object resume(MaterializedFrame frame, DelimitedResume input, MaskingState ambient, DelimitedStep outerMask) { var answer = input.get(); assertEquals(0, language.getHandoffState().get().getResults().getDepth(), "The transferred root must detach its tuple before another saved step runs"); FrameAccess.writeLong(frame, slot, 99L); TupleResults.ownedTupleResult(shape.finish(frame, new int[]{slot}), shape); return shape.getLayout().getLong((HandoffStorage) answer, 0); } })); var image = new DelimitedStack(cut, shape);
            for (int i = 0; i < 2; i++) assertEquals(42L, owner.resume(image)); assertEquals(2, effects[0]); assertEquals(0, language.getHandoffState().get().getResults().getDepth());
        } finally { context.leave(); } }
    }
    @Test void frameImagesCopyControlLocalsButShareHeapReferences() {
        var builder = FrameDescriptor.newBuilder(); int scalar = builder.addSlot(FrameSlotKind.Long, null, null), reference = builder.addSlot(FrameSlotKind.Object, null, null), floating = builder.addSlot(FrameSlotKind.Double, null, null); var descriptor = builder.build(); int auxiliary = descriptor.findOrAddAuxiliarySlot("continuation-test"); var heap = new ArrayList<>(List.of(1L)); var original = Truffle.getRuntime().createMaterializedFrame(new Object[]{heap, 7L}, descriptor); original.setLong(scalar, Long.MIN_VALUE); original.setObject(reference, heap); original.setDouble(floating, Double.longBitsToDouble(0x7ff8000000000042L)); original.setAuxiliarySlot(auxiliary, heap); var image = DelimitedContinuations.copyContinuationFrame(original); original.setLong(scalar, 11); original.getArguments()[1] = 12L; var first = DelimitedContinuations.copyContinuationFrame(image); var second = DelimitedContinuations.copyContinuationFrame(image); first.setLong(scalar, 13); first.getArguments()[1] = 14L;
        assertEquals(Long.MIN_VALUE, second.getLong(scalar)); assertEquals(7L, second.getArguments()[1]); assertEquals(0x7ff8000000000042L, Double.doubleToRawLongBits(second.getDouble(floating))); assertSame(heap, second.getObject(reference)); assertSame(heap, second.getAuxiliarySlot(auxiliary)); heap.set(0, 15L); assertEquals(List.of(15L), second.getObject(reference)); first.setObject(reference, null); assertSame(heap, image.getObject(reference));
    }
    @Test void scalarEntryRejectsTupleOnlyOperationsBeforeEvaluatingOperands() {
        try (var context = Context.newBuilder("thc").option("engine.WarnInterpreterOnly", "false").build()) { context.initialize("thc"); context.enter(); try {
            var language = TruffleLanguage.LanguageReference.create(Language.class).get(null); var state = new CoreRepresentation(CoreKind.VOID, false, false, List.of(), null, null, null, null, null); var value = new CoreRepresentation(CoreKind.OBJECT, false, false, List.of("BoxedRep (Just Lifted)"), null, null, null, null, null); var shape = new TupleShape(new CoreRepresentation(CoreKind.UNKNOWN, false, false, value.getPrimReps(), List.of(state, value), null, null, null, null), language); var frame = Truffle.getRuntime().createVirtualFrame(new Object[0], FrameDescriptor.newBuilder().build());
            java.util.function.Supplier<Expr[]> operands = () -> { Expr[] result = new Expr[3]; for (int i = 0; i < result.length; i++) result[i] = new Expr() { @Override public Object execute(VirtualFrame frame) { throw new IllegalStateException("scalar rejection evaluated an operand"); } }; return result; };
            for (String name : List.of("newPromptTag#", "prompt#", "control0#")) { var node = new DelimitedPrimitive(name, shape, operands.get(), language, new Metrics(false)); assertEquals(name + " requires a tuple destination", assertThrows(RuntimeFault.class, () -> node.execute(frame)).getMessage()); }
            for (String name : List.of("catch#", "maskAsyncExceptions#", "maskUninterruptible#", "unmaskAsyncExceptions#")) { var node = new DelimitedIOBoundary(name, shape, operands.get(), language, new Metrics(false)); assertEquals(name + " requires a tuple destination", assertThrows(RuntimeFault.class, () -> node.execute(frame)).getMessage()); }
        } finally { context.leave(); } }
    }
    private CoreRepresentation tuple(CoreRepresentation... fields) { var reps = new ArrayList<String>(); for (var field : fields) reps.addAll(Objects.requireNonNull(field.getPrimReps())); return new CoreRepresentation(CoreKind.UNKNOWN, false, false, reps, Arrays.asList(fields), null, null, null, null); }
    @Test void continuationLoweringRejectsWrongCarrierAndTupleContracts() {
        var state = new CoreRepresentation(CoreKind.VOID, false, false, List.of(), null, null, null, null, null); var tag = new CoreRepresentation(CoreKind.OBJECT, false, false, List.of("BoxedRep (Just Unlifted)"), null, null, null, null, null); var closure = new CoreRepresentation(CoreKind.CLOSURE, false, false, List.of("BoxedRep (Just Lifted)"), null, null, null, null, null); var integer = new CoreRepresentation(CoreKind.LONG, false, false, List.of("IntRep"), null, null, null, null, null);
        DelimitedControl.validate("newPromptTag#", List.of(state), List.of(false), tuple(state, tag)); assertThrows(RuntimeFault.class, () -> DelimitedControl.validate("newPromptTag#", List.of(state), List.of(false), tuple(state, integer)));
        for (String name : List.of("prompt#", "control0#")) { DelimitedControl.validate(name, List.of(tag, closure, state), List.of(false, true, false), tuple(state, tag)); assertThrows(RuntimeFault.class, () -> DelimitedControl.validate(name, List.of(integer, closure, state), List.of(false, true, false), tuple(state, tag))); assertThrows(RuntimeFault.class, () -> DelimitedControl.validate(name, List.of(tag, tag, state), List.of(false, true, false), tuple(state, tag))); assertThrows(RuntimeFault.class, () -> DelimitedControl.validate(name, List.of(tag, closure, state), List.of(false, true, false), tuple(tag, state))); }
    }
    @Test void closedContextPromptAndContinuationCannotEnterAnotherContext() {
        PromptTag foreignTag; DelimitedStack foreignStack;
        try (var first = Context.newBuilder("thc").option("engine.WarnInterpreterOnly", "false").build()) { first.initialize("thc"); first.enter(); try {
            var language = TruffleLanguage.LanguageReference.create(Language.class).get(null); foreignTag = new PromptTag(Language.currentState(null)); assertNotSame(foreignTag, new PromptTag(Language.currentState(null))); var state = new CoreRepresentation(CoreKind.VOID, false, false, List.of(), null, null, null, null, null); var value = new CoreRepresentation(CoreKind.OBJECT, false, false, List.of("BoxedRep (Just Lifted)"), null, null, null, null, null); var shape = new TupleShape(new CoreRepresentation(CoreKind.UNKNOWN, false, false, value.getPrimReps(), List.of(state, value), null, null, null, null), language); foreignStack = new DelimitedStack(new DelimitedCut(foreignTag, null, shape, MaskingState.UNMASKED, new Node() {}), shape);
        } finally { first.leave(); } }
        try (var second = Context.newBuilder("thc").option("engine.WarnInterpreterOnly", "false").build()) { second.initialize("thc"); second.enter(); try {
            var language = TruffleLanguage.LanguageReference.create(Language.class).get(null); var local = new PromptTag(Language.currentState(null)); var probe = new GuestRoot(language, FrameDescriptor.newBuilder().build()) {
                @Child private DelimitedActionSite site = new DelimitedActionSite(language, new Metrics(false)); @Override public long bloom(VirtualFrame frame) { return 0L; }
                @Override public Object execute(VirtualFrame frame) { var operation = frame.getArguments()[0]; if (Objects.equals(operation, 0)) return DelimitedControl.tag(this, local); if (Objects.equals(operation, 1)) return DelimitedControl.tag(this, foreignTag); if (Objects.equals(operation, 2)) return foreignStack.resume(site, frame.materialize(), null); return DelimitedControl.tag(this, 0L); }
            }.getCallTarget(); assertSame(local, probe.call(0)); for (int i = 1; i <= 3; i++) { int operation = i; assertThrows(RuntimeFault.class, () -> probe.call(operation)); } ThreadInventoryCoreEvidence.released(language); assertEquals(MaskingState.UNMASKED, Language.currentState(null).getMaskingState().get());
        } finally { second.leave(); } }
    }
}
