// SPDX-FileCopyrightText: 2026 Edward Kmett
// SPDX-License-Identifier: UPL-1.0 AND BSD-3-Clause
package thc.runtime;

import com.oracle.truffle.api.RootCallTarget;
import com.oracle.truffle.api.Truffle;
import com.oracle.truffle.api.TruffleLanguage;
import com.oracle.truffle.api.bytecode.ContinuationResult;
import com.oracle.truffle.api.frame.VirtualFrame;
import com.oracle.truffle.api.nodes.RootNode;
import org.graalvm.polyglot.Context;
import org.junit.jupiter.api.Test;
import thc.Language;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicReference;
import static org.junit.jupiter.api.Assertions.*;
import static thc.Main.executionContext;

/** A test-only DSL continuation across nested mask and genuine guest catch scopes. */
class MaskContinuationProofTest {
    private static class Driver extends RootNode {
        @Child private Force force = new Force(new Metrics(true));
        Driver() { super(null); }
        @Override public Object execute(VirtualFrame frame) { return force.execute(frame, frame.getArguments()[0]); }
        Object force(Thunk thunk) { return Calls.target(getCallTarget(), new Object[]{thunk}); }
        Object deliver(Thunk thunk, Thunk child, Object payload) { return force.deliverAtCapturedHandler(thunk, child, payload); }
    }
    @FunctionalInterface private interface Action<T> { T run() throws Exception; }
    private <T> T entered(Context context, Action<T> action) throws Exception { context.enter(); try { return action.run(); } finally { context.leave(); } }
    private void compile(RootCallTarget target) throws ReflectiveOperationException {
        var type = Class.forName("com.oracle.truffle.runtime.OptimizedCallTarget"); assertTrue(type.isInstance(target)); type.getMethod("compile", boolean.class).invoke(target, true); type.getMethod("waitForCompilation").invoke(target); assertEquals(true, type.getMethod("isValidLastTier").invoke(target));
        // Match EntryValue.compile: valid guest code alone does not restore a
        // retired HotSpot boundary. Repairing it during entry loses that call.
        var runtime = Truffle.getRuntime(); runtime.getClass().getMethod("bypassedInstalledCode", type).invoke(runtime, target); assertEquals(true, type.getMethod("isValidLastTier").invoke(target));
    }
    private record Chain(Thunk child, Thunk inner, Thunk outer) {}
    @Test void privateAsyncCutRunsNearestCapturedHandlerAndLeavesSharedChildResumable() throws Exception {
        try (var context = executionContext()) { context.initialize("thc"); var language = entered(context, () -> TruffleLanguage.LanguageReference.create(Language.class).get(null)); var driver = entered(context, Driver::new); var payload = new Object(); var childEffects = new AtomicInteger(); var innerEffects = new AtomicInteger(); var outerEffects = new AtomicInteger(); var innerProbe = new ThunkYieldProofRoot.MaskProbe(); var outerProbe = new ThunkYieldProofRoot.MaskProbe();
            var chain = entered(context, () -> { var child = new Thunk(ThunkYieldProofRoot.target(language, childEffects, new AtomicInteger(), new ThunkYieldProofRoot.Gate(), new Object()), null); var inner = new Thunk(ThunkYieldProofRoot.privateAsyncHandlerCaller(language, new AtomicReference<>(child), innerEffects, new AtomicInteger(), MaskingState.MASKED_INTERRUPTIBLE, MaskingState.UNMASKED, innerProbe), null); var outer = new Thunk(ThunkYieldProofRoot.maskedCaller(language, new AtomicReference<>(inner), outerEffects, new AtomicInteger(), MaskingState.MASKED_UNINTERRUPTIBLE, MaskingState.MASKED_INTERRUPTIBLE, outerProbe), null); return new Chain(child, inner, outer); }); var child = chain.child; var inner = chain.inner; var outer = chain.outer;
            entered(context, () -> { assertSame(outer, assertThrows(ThunkSuspended.class, () -> driver.force(outer)).getThunk()); assertEquals(MaskingState.UNMASKED, SynchronousMasking.current(driver)); assertThrows(RuntimeFault.class, () -> driver.deliver(inner, outer, payload)); assertEquals(5, inner.getState(), "A wrong child cannot claim the handler continuation"); return null; }); assertEquals(5, child.getState()); assertEquals(5, inner.getState()); assertEquals(5, outer.getState());
            try (var pool = Executors.newSingleThreadExecutor()) { var result = pool.submit(() -> entered(context, () -> { SynchronousMasking.set(driver, MaskingState.MASKED_UNINTERRUPTIBLE); try { assertEquals(77L, driver.deliver(inner, child, payload)); assertEquals(MaskingState.MASKED_UNINTERRUPTIBLE, SynchronousMasking.current(driver)); assertEquals(177L, driver.force(outer)); assertEquals(MaskingState.MASKED_UNINTERRUPTIBLE, SynchronousMasking.current(driver)); return 177L; } finally { SynchronousMasking.set(driver, MaskingState.UNMASKED); } })); assertEquals(177L, result.get(5, TimeUnit.SECONDS)); }
            assertSame(payload, innerProbe.handlerPayload.get()); assertEquals(MaskingState.MASKED_INTERRUPTIBLE, innerProbe.handlerMask.get()); assertNull(outerProbe.handlerPayload.get(), "The nearest handler consumes this delivery"); assertEquals(5, child.getState(), "The shared child is suspended, not poisoned by delivery"); assertEquals(2, inner.getState()); assertEquals(2, outer.getState()); entered(context, () -> { assertSame(child, assertThrows(ThunkSuspended.class, () -> driver.force(child)).getThunk()); assertEquals(42L, ((ThunkYieldProofRoot.Answer) driver.force(child)).number()); return null; }); assertEquals(1, childEffects.get(), "The shared child's prefix cannot replay"); assertEquals(1, innerEffects.get()); assertEquals(1, outerEffects.get());
        }
    }
    private record Pair(Thunk child, Thunk caller) {}
    @Test void unhandledPrivateDeliveryNeverBecomesMemoizedGuestFailure() throws Exception {
        try (var context = executionContext()) { context.initialize("thc"); var language = entered(context, () -> TruffleLanguage.LanguageReference.create(Language.class).get(null)); var driver = entered(context, Driver::new); var probe = new ThunkYieldProofRoot.MaskProbe();
            var pair = entered(context, () -> { var child = new Thunk(ThunkYieldProofRoot.target(language, new AtomicInteger(), new AtomicInteger(), new ThunkYieldProofRoot.Gate(), new Object()), null); var caller = new Thunk(ThunkYieldProofRoot.maskedCaller(language, new AtomicReference<>(child), new AtomicInteger(), new AtomicInteger(), MaskingState.MASKED_INTERRUPTIBLE, MaskingState.UNMASKED, probe), null); return new Pair(child, caller); }); var child = pair.child; var caller = pair.caller;
            entered(context, () -> { assertSame(caller, assertThrows(ThunkSuspended.class, () -> driver.force(caller)).getThunk()); assertThrows(ThunkYieldProofRoot.PrivateAsyncDelivery.class, () -> driver.deliver(caller, child, new Object())); assertEquals(MaskingState.UNMASKED, SynchronousMasking.current(driver)); assertNull(probe.handlerPayload.get(), "The ordinary guest handler must reject async origin"); assertEquals(5, child.getState()); assertEquals(4, caller.getState()); assertThrows(RuntimeFault.class, () -> driver.force(caller)); return null; });
        }
    }
    @Test void compiledNestedMasksParkToAmbientAndResumeOnAnotherCarrier() throws Exception {
        try (var context = executionContext()) { context.initialize("thc"); var language = entered(context, () -> TruffleLanguage.LanguageReference.create(Language.class).get(null)); var driver = entered(context, Driver::new); var callerEffects = new AtomicInteger(); var compiledEffects = new AtomicInteger(); var childEffects = new AtomicInteger(); var probe = new ThunkYieldProofRoot.MaskProbe();
            var selectedChild = entered(context, () -> new AtomicReference<>(new Thunk(new RootNode(null) { @Override public Object execute(VirtualFrame frame) { return new ThunkYieldProofRoot.Answer(42L, this); } }.getCallTarget(), null))); var target = entered(context, () -> ThunkYieldProofRoot.maskedCaller(language, selectedChild, callerEffects, compiledEffects, MaskingState.MASKED_INTERRUPTIBLE, MaskingState.MASKED_UNINTERRUPTIBLE, probe)); entered(context, () -> { for (int i = 0; i < 8; i++) assertEquals(142L, driver.force(new Thunk(target, null))); compile(target); return null; }); int callerBefore = callerEffects.get(), compiledBefore = compiledEffects.get(); var child = entered(context, () -> new Thunk(ThunkYieldProofRoot.target(language, childEffects, new AtomicInteger(), new ThunkYieldProofRoot.Gate(), new Object()), null)); selectedChild.set(child); var caller = new Thunk(target, null);
            entered(context, () -> { assertSame(caller, assertThrows(ThunkSuspended.class, () -> driver.force(caller)).getThunk()); assertEquals(MaskingState.UNMASKED, SynchronousMasking.current(driver), "Parking must unwind both active scopes to this carrier's ambient mask"); return null; }); assertEquals(MaskingState.MASKED_UNINTERRUPTIBLE, probe.parked.get()); assertEquals(5, caller.getState()); var frame = ((ContinuationResult) caller.getValue()).getFrame();
            boolean liveOperand = false; for (int i = 0; i < frame.getFrameDescriptor().getNumberOfSlots(); i++) if (frame.isLong(i) && frame.getLong(i) == 100L) { liveOperand = true; break; } assertTrue(liveOperand, "The primitive operand below mask/handler scopes survives"); boolean liveMask = false; for (int i = 0; i < frame.getFrameDescriptor().getNumberOfSlots(); i++) if (frame.isObject(i) && frame.getObject(i) == MaskingState.MASKED_UNINTERRUPTIBLE) { liveMask = true; break; } assertTrue(liveMask, "The logical active mask is stored in the continuation frame"); assertTrue(compiledEffects.get() > compiledBefore, "Initial masked caller ran installed guest code");
            try (var pool = Executors.newSingleThreadExecutor()) { var result = pool.submit(() -> entered(context, () -> { SynchronousMasking.set(driver, MaskingState.MASKED_INTERRUPTIBLE); try { assertSame(caller, assertThrows(ThunkSuspended.class, () -> driver.force(caller)).getThunk()); assertEquals(MaskingState.MASKED_INTERRUPTIBLE, SynchronousMasking.current(driver)); long answer = (Long) driver.force(caller); assertEquals(MaskingState.MASKED_INTERRUPTIBLE, SynchronousMasking.current(driver), "The resumer's ambient mask survives the logical computation"); return answer; } finally { SynchronousMasking.set(driver, MaskingState.UNMASKED); } })); assertEquals(142L, result.get(5, TimeUnit.SECONDS)); }
            assertEquals(MaskingState.MASKED_UNINTERRUPTIBLE, probe.reentered.get()); assertEquals(MaskingState.MASKED_INTERRUPTIBLE, probe.afterInner.get()); assertEquals(MaskingState.UNMASKED, probe.afterOuter.get()); assertNull(probe.handlerMask.get()); assertNull(probe.handlerPayload.get()); assertEquals(callerBefore + 1, callerEffects.get()); assertEquals(1, childEffects.get()); assertEquals(2, caller.getState()); assertEquals(2, child.getState());
        }
    }
    @Test void resumedGuestFailureRunsHandlerUnderMaskAndRestoresCarrier() throws Exception {
        try (var context = executionContext()) { context.initialize("thc"); var language = entered(context, () -> TruffleLanguage.LanguageReference.create(Language.class).get(null)); var driver = entered(context, Driver::new); var payload = new Object(); var callerEffects = new AtomicInteger(); var compiledEffects = new AtomicInteger(); var childEffects = new AtomicInteger(); var probe = new ThunkYieldProofRoot.MaskProbe();
            var selectedChild = entered(context, () -> new AtomicReference<>(new Thunk(new RootNode(null) { @Override public Object execute(VirtualFrame frame) { return new ThunkYieldProofRoot.Answer(42L, this); } }.getCallTarget(), null))); var target = entered(context, () -> ThunkYieldProofRoot.maskedCaller(language, selectedChild, callerEffects, compiledEffects, MaskingState.UNMASKED, MaskingState.UNMASKED, probe)); entered(context, () -> { for (int i = 0; i < 8; i++) assertEquals(142L, driver.force(new Thunk(target, null))); compile(target); return null; }); int compiledBefore = compiledEffects.get(); var child = entered(context, () -> new Thunk(ThunkYieldProofRoot.target(language, childEffects, new AtomicInteger(), new ThunkYieldProofRoot.Gate(), new GuestException(payload, driver)), null)); selectedChild.set(child); var caller = new Thunk(target, null);
            entered(context, () -> { assertSame(caller, assertThrows(ThunkSuspended.class, () -> driver.force(caller)).getThunk()); assertEquals(MaskingState.UNMASKED, SynchronousMasking.current(driver)); return null; }); assertEquals(MaskingState.UNMASKED, probe.parked.get()); assertTrue(compiledEffects.get() > compiledBefore);
            try (var pool = Executors.newSingleThreadExecutor()) { var result = pool.submit(() -> entered(context, () -> { SynchronousMasking.set(driver, MaskingState.MASKED_UNINTERRUPTIBLE); try { assertSame(caller, assertThrows(ThunkSuspended.class, () -> driver.force(caller)).getThunk()); assertEquals(MaskingState.MASKED_UNINTERRUPTIBLE, SynchronousMasking.current(driver)); long answer = (Long) driver.force(caller); assertEquals(MaskingState.MASKED_UNINTERRUPTIBLE, SynchronousMasking.current(driver)); return answer; } finally { SynchronousMasking.set(driver, MaskingState.UNMASKED); } })); assertEquals(77L, result.get(5, TimeUnit.SECONDS)); }
            assertEquals(MaskingState.UNMASKED, probe.reentered.get()); assertEquals(MaskingState.UNMASKED, probe.afterInner.get()); assertEquals(MaskingState.UNMASKED, probe.afterOuter.get()); assertEquals(MaskingState.MASKED_INTERRUPTIBLE, probe.handlerMask.get(), "An unmasked catch handler runs masked, even after cross-thread resume"); assertSame(payload, probe.handlerPayload.get()); assertEquals(1, childEffects.get()); assertEquals(1, callerEffects.get() - 8); assertEquals(3, child.getState()); assertEquals(2, caller.getState(), "The handler recovers the caller normally");
        }
    }
    @Test void internalSuspensionBypassesHaskellHandlerAndUnwindsMask() throws Exception {
        try (var context = executionContext()) { context.initialize("thc"); var language = entered(context, () -> TruffleLanguage.LanguageReference.create(Language.class).get(null)); var driver = entered(context, Driver::new); var effects = new AtomicInteger(); var probe = new ThunkYieldProofRoot.MaskProbe();
            var pair = entered(context, () -> { var child = new Thunk(ThunkYieldProofRoot.target(language, effects, new AtomicInteger(), new ThunkYieldProofRoot.Gate(), new Object()), null); return new Pair(child, new Thunk(ThunkYieldProofRoot.uncapturedMaskedCaller(language, child, probe), null)); }); var child = pair.child; var caller = pair.caller; entered(context, () -> { assertSame(child, assertThrows(ThunkSuspended.class, () -> driver.force(caller)).getThunk()); assertEquals(MaskingState.UNMASKED, SynchronousMasking.current(driver)); assertThrows(RuntimeFault.class, () -> driver.force(caller)); return null; });
            assertNull(probe.handlerMask.get(), "A Haskell catch cannot consume the internal suspension signal"); assertNull(probe.handlerPayload.get()); assertEquals(4, caller.getState(), "An uncaptured caller fails closed without replay"); assertEquals(5, child.getState()); assertEquals(1, effects.get());
        }
    }
    private record TailSetup(AtomicReference<Thunk> child, RootCallTarget target) {}
    @Test void resumedTailTrampolineKeepsLogicalMaskUntilChainCompletes() throws Exception {
        try (var context = executionContext()) { context.initialize("thc"); var language = entered(context, () -> TruffleLanguage.LanguageReference.create(Language.class).get(null)); var driver = entered(context, Driver::new); var effects = new AtomicInteger(); var compiledEffects = new AtomicInteger(); var childEffects = new AtomicInteger(); var observedTailMask = new AtomicReference<MaskingState>(); var probe = new ThunkYieldProofRoot.MaskProbe();
            var setup = entered(context, () -> { var warm = new Thunk(new RootNode(null) { @Override public Object execute(VirtualFrame frame) { return new ThunkYieldProofRoot.Answer(42L, this); } }.getCallTarget(), null); var tail = new RootNode(null) { @Override public Object execute(VirtualFrame frame) { var mask = SynchronousMasking.current(this); observedTailMask.set(mask); return mask.getTag(); } }.getCallTarget(); return new TailSetup(new AtomicReference<>(warm), tail); }); var selectedChild = setup.child; var tailTarget = setup.target; var tailProbe = new ThunkYieldProofRoot.TailProbe(tailTarget);
            var target = entered(context, () -> ThunkYieldProofRoot.maskedCaller(language, selectedChild, effects, compiledEffects, MaskingState.MASKED_INTERRUPTIBLE, MaskingState.MASKED_UNINTERRUPTIBLE, probe, tailProbe)); entered(context, () -> { for (int i = 0; i < 8; i++) assertEquals(142L, driver.force(new Thunk(target, null))); compile(target); return null; }); int effectsBefore = effects.get(), compiledBefore = compiledEffects.get(); var child = entered(context, () -> new Thunk(ThunkYieldProofRoot.target(language, childEffects, new AtomicInteger(), new ThunkYieldProofRoot.Gate(), new Object()), null)); selectedChild.set(child); tailProbe.armed = true; var caller = new Thunk(target, null);
            entered(context, () -> { assertSame(caller, assertThrows(ThunkSuspended.class, () -> driver.force(caller)).getThunk()); assertEquals(MaskingState.UNMASKED, SynchronousMasking.current(driver)); return null; }); assertTrue(compiledEffects.get() > compiledBefore);
            try (var pool = Executors.newSingleThreadExecutor()) { var result = pool.submit(() -> entered(context, () -> { SynchronousMasking.set(driver, MaskingState.MASKED_INTERRUPTIBLE); try { assertSame(caller, assertThrows(ThunkSuspended.class, () -> driver.force(caller)).getThunk()); assertEquals(MaskingState.MASKED_INTERRUPTIBLE, SynchronousMasking.current(driver)); long answer = (Long) driver.force(caller); assertEquals(MaskingState.MASKED_INTERRUPTIBLE, SynchronousMasking.current(driver)); return answer; } finally { SynchronousMasking.set(driver, MaskingState.UNMASKED); } })); assertEquals(1L, result.get(5, TimeUnit.SECONDS)); }
            assertEquals(MaskingState.MASKED_UNINTERRUPTIBLE, observedTailMask.get(), "The tail target still belongs to the resumed logical mask scope"); assertEquals(effectsBefore + 1, effects.get()); assertEquals(1, childEffects.get()); assertEquals(2, caller.getState());
        }
    }
}
