// SPDX-FileCopyrightText: 2026 Edward Kmett
// SPDX-License-Identifier: UPL-1.0 AND BSD-3-Clause
package thc.runtime;

import com.oracle.truffle.api.RootCallTarget;
import com.oracle.truffle.api.TruffleLanguage;
import org.graalvm.polyglot.Context;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.*;
import org.junit.jupiter.api.io.TempDir;
import thc.*;
import java.io.File;
import java.net.URI;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;
import static thc.runtime.OriginalStdioChecks.*;

/** Genuine installed GHC and Unix declarations, with native-compiled consumers. */
@EnabledOnOs(OS.LINUX)
@EnabledIfSystemProperty(named="os.arch",matches="amd64|x86_64")
@SuppressWarnings("unchecked")
class OriginalPathLinkTest {
    @TempDir Path directory;
    private final File root=new File(System.getProperty("thc.projectRoot"));
    private final String prefix="build/original-path-link";
    private final Map<String,OriginalStdioOp> operations=new LinkedHashMap<>();
    OriginalPathLinkTest() { operations.put("pathSymlink",OriginalStdioOp.SYMLINK); operations.put("pathReadlink",OriginalStdioOp.READLINK); }
    private Map<String,Object> json(String path) throws Exception { return (Map<String,Object>)Json.parse(Files.readString(new File(root,path).toPath())); }
    private Map<String,Object> source(String stage) throws Exception { return json(prefix+"/"+stage+".json"); }
    private Object copy(Object value) { return Json.parse(Json.stringify(value)); }
    private ManagedAddress cstring(String value) { return address(value.getBytes(StandardCharsets.UTF_8)); }
    private ExecutableProgram program(Language language,String backend,Map<String,Object> module) { return backend.equals("ast")?new Program(language,module):new BytecodeProgram(language,module); }
    private Context context() { return NativeFileProvider.createContext(Set.of(),ContextProfile.SYNCHRONOUS_TEST); }
    private void valid(RootCallTarget target) throws Exception { assertEquals(true,target.getClass().getMethod("isValidLastTier").invoke(target)); }
    private void released(Language language) { var handoff=language.getHandoffState().get(); assertEquals(0,handoff.getArguments().getDepth()); assertEquals(0,handoff.getResults().getDepth()); assertEquals(0,handoff.getArguments().retainedReferences()); assertEquals(0,handoff.getResults().retainedReferences()); }
    private OriginalStdioOp validate(List<Object> call) { var reps=new ArrayList<Object>(); for(var arg:(List<List<Object>>)call.get(2)) { var metadata=CoreRepresentations.metadata(arg); reps.add(metadata==null?null:metadata.get("rep")); } return CoreOriginalStdio.validate(call.get(6),reps,(List<?>)call.get(3),((Map<?,?>)call.get(6)).get("rep")); }
    private List<Object> original(String name) throws Exception { return original(name,"post"); }
    private List<Object> original(String name,String stage) throws Exception { return single(foreignCalls(CoreModules.reachable(source(stage),name)),ignored->true); }
    private Map<String,Object> raw(List<Object> call) throws Exception { return rawModule(call,source("post")); }
    private byte[] bytes(Map<String,Object> row,String name) { var values=(List<Long>)row.get(name); byte[] result=new byte[values.size()]; for(int i=0;i<result.length;i++) result[i]=values.get(i).byteValue(); return result; }
    private ManagedAddress address(byte[] bytes) { return ManagedAddress.fromByteArray(Arrays.copyOf(bytes,bytes.length+1)); }
    private ManagedAddress path(Path directory,byte[] bytes) { byte[] prefix=bytes.length==0?new byte[0]:(Path.of(Language.currentState().getEnv().getCurrentWorkingDirectory().getPath()).relativize(directory)+"/").getBytes(StandardCharsets.UTF_8); byte[] result=Arrays.copyOf(prefix,prefix.length+bytes.length); System.arraycopy(bytes,0,result,prefix.length,bytes.length); return address(result); }
    private Path rawPath(Path directory,byte[] bytes) { var suffix=new StringBuilder(); for(byte value:bytes) suffix.append(String.format(Locale.ROOT,"%%%02X",value&255)); return Path.of(URI.create(directory.toUri().toASCIIString()+suffix)); }
    private Path rawTarget(byte[] bytes) { boolean rooted=bytes.length>0&&bytes[0]==47; var absolute=rawPath(Path.of("/"),rooted?Arrays.copyOfRange(bytes,1,bytes.length):bytes); return rooted?absolute:absolute.subpath(0,absolute.getNameCount()); }
    private Path setup() throws Exception { var scratch=Files.createTempDirectory(directory,"case-"); Files.writeString(scratch.resolve("target"),"unchanged"); Files.createDirectory(scratch.resolve("sub")); Files.createSymbolicLink(scratch.resolve("existing-link"),Path.of("target")); return scratch; }
    @Test void genuineNativeLinksMatchBothBackendsAndFirstInstalledCalls() throws Exception {
        var manifest=json(prefix+"/manifest.json"); assertEquals(new ArrayList<>(operations.keySet()),manifest.get("entries")); assertTrue(CoreOriginalStdio.isOriginalUnixUnit(manifest.get("unixUnit"))); hashes(root,manifest.get("inputHashes"),Set.of("test/fixtures/compiler/OriginalPathLinkAudit.hs","test/haskell-fixtures/OriginalPathLinkFixtures.hs","bin/core_original_foreign.py","bin/core-capabilities.json")); var artifacts=new HashSet<>(Set.of(prefix+"/oracle.json")); for(var stage:List.of("pre","post")) { artifacts.add(prefix+"/"+stage+".json"); for(var name:operations.keySet()) artifacts.add(prefix+"/"+stage+"-"+name+".audit.json"); } hashes(root,manifest.get("artifactHashes"),artifacts,prefix+"/"); var oracle=json(prefix+"/oracle.json"); var symlinkRows=(List<Map<String,Object>>)oracle.get("symlinkRows"); var readlinkRows=(List<Map<String,Object>>)oracle.get("readlinkRows"); var symlinkNames=new ArrayList<Object>(); for(var row:symlinkRows) symlinkNames.add(row.get("name")); var readlinkNames=new ArrayList<Object>(); for(var row:readlinkRows) readlinkNames.add(row.get("name")); assertEquals(List.of("relative","dot-segments","parent-relative","absolute","dangling","raw-target","raw-link","empty-target","empty-path","existing-file","existing-link","missing-parent","not-directory"),symlinkNames); assertEquals(List.of("full","exact","short","one","zero","dangling","raw-target","raw-link","missing","regular","not-directory","empty"),readlinkNames);
        for(var stage:List.of("pre","post")) for(var operation:operations.entrySet()) { var name=operation.getKey(); var audit=json(prefix+"/"+stage+"-"+name+".audit.json"); assertEquals(true,audit.get("accepted")); assertEquals(List.of(),audit.get("issues")); assertEquals(List.of(),audit.get("missingGlobals")); var linked=with(CoreModules.reachable(source(stage),name),"instrument",true); var evidence=new ArrayCoreEvidence(linked,name); assertEquals(1,evidence.getBindings().size()); assertEquals(1,evidence.guestLambdas(evidence.getRoot().get("expr")).size()); assertEquals(1,evidence.loweredGuestLambdas(evidence.getRoot().get("expr")).size()); assertEquals(operation.getValue(),validate(original(name,stage))); assertEquals(manifest.get("unixUnit"),((Map<?,?>)((Map<?,?>)((Map<?,?>)original(name,stage).get(6)).get("foreignCall")).get("target")).get("unit")); var rows=name.equals("pathSymlink")?symlinkRows:readlinkRows;
            for(var backend:List.of("ast","bytecode")) try(var context=context()) { context.initialize("thc"); context.enter(); try { var language=TruffleLanguage.LanguageReference.create(Language.class).get(null); var executable=program(language,backend,linked); var entry=executable.entryTarget(name); var stdio=Language.currentState().getStdio();
                class Exercise { void run(boolean compiled) throws Exception { for(var row:rows) { var scratch=setup(); var pathBytes=bytes(row,"path"); var target=bytes(row,"target"); int capacity=row.get("capacity") instanceof Long n?n.intValue():0; byte[] output=new byte[capacity+16]; Arrays.fill(output,(byte)90); if(name.equals("pathReadlink")) { Files.createSymbolicLink(scratch.resolve("link"),rawTarget(target)); if(Objects.equals(row.get("name"),"raw-link")) Files.createSymbolicLink(rawPath(scratch,pathBytes),rawTarget(target)); } assertEquals(-1L,stdio.close(-1)); long before=((Number)executable.diagnostics().get("compiledEntries")).longValue(); if(compiled) valid(entry); var actual=name.equals("pathSymlink")?Calls.target(entry,new Object[]{0L,address(target),path(scratch,pathBytes)}):Calls.target(entry,new Object[]{0L,path(scratch,pathBytes),ManagedAddress.fromByteArray(output).plus(8),(long)capacity}); assertEquals(row.get("status"),actual,stage+"/"+backend+"/"+name+"/"+row.get("name")); assertEquals(row.get("errno"),stdio.errno()); if(compiled) { assertEquals(before+1,((Number)executable.diagnostics().get("compiledEntries")).longValue()); valid(entry); }
                    if(name.equals("pathSymlink")) { var link=pathBytes.length==0?null:rawPath(scratch,pathBytes); var observed=link!=null&&Files.isSymbolicLink(link)?Files.readSymbolicLink(link):null; var expected=row.get("linkTarget") instanceof List<?>?rawTarget(bytes(row,"linkTarget")):null; assertEquals(expected,observed); } else { assertEquals(row.get("bufferHex"),hex(output)); long count=(Long)actual; if(count>=0) { assertEquals(Math.min((long)target.length,(long)capacity),count); assertArrayEquals(Arrays.copyOfRange(target,0,(int)count),Arrays.copyOfRange(output,8,8+(int)count)); for(int i=8+(int)count;i<output.length;i++) assertEquals((byte)90,output[i]); } else for(byte value:output) assertEquals((byte)90,value); } assertEquals("unchanged",Files.readString(scratch.resolve("target"))); released(language);
                } } }
                var exercise=new Exercise(); exercise.run(false); entry.getClass().getMethod("compile",boolean.class).invoke(entry,true); valid(entry); exercise.run(true); assertEquals(0L,((Number)executable.diagnostics().get("unsupportedTraps")).longValue());
            } finally { context.leave(); } }
        }
    }
    @Test void exactDescriptorOwnerStateAndStoredOperandProofsRemainRequired() throws Exception {
        for(var operationEntry:operations.entrySet()) { var call=original(operationEntry.getKey()); var operation=operationEntry.getValue(); assertEquals(operation,validate(call)); for(var edit:List.of(list("safety","safe"),list("convention","capi"),list("arity",2L),list("suppliedArity",2L))) { var bad=(List<Object>)copy(call); ((Map<String,Object>)((Map<?,?>)bad.get(6)).get("foreignCall")).put((String)edit.get(0),edit.get(1)); assertThrows(RuntimeFault.class,()->validate(bad)); }
            for(var unit:List.of("main","unix-2.8.7.0-inplace","unix-2.8.8.0-ABCD","unix-2.8.8.0-nothex","ghc-internal")) { if(operation==OriginalStdioOp.READLINK&&unit.equals("ghc-internal")) continue; var bad=(List<Object>)copy(call); ((Map<String,Object>)((Map<?,?>)((Map<?,?>)bad.get(6)).get("foreignCall")).get("target")).put("unit",unit); assertThrows(RuntimeFault.class,()->validate(bad)); }
            var widened=(List<Object>)copy(call); var meta=(Map<?,?>)widened.get(6); for(var rep:list(meta.get("rep"),((Map<?,?>)meta.get("foreignCall")).get("resultRep"))) { var proof=(Map<String,Object>)rep; proof.put("primReps",list("Int64Rep")); ((List<Map<String,Object>>)proof.get("components")).get(1).put("primReps",list("Int64Rep")); } assertThrows(RuntimeFault.class,()->validate(widened));
            for(var backend:List.of("ast","bytecode")) try(var context=context()) { context.initialize("thc"); context.enter(); try { var language=TruffleLanguage.LanguageReference.create(Language.class).get(null); for(var unit:List.of("unix-2.8.8.0-inplace","unix-2.8.8.0-460b")) { var installed=(List<Object>)copy(call); ((Map<String,Object>)((Map<?,?>)((Map<?,?>)installed.get(6)).get("foreignCall")).get("target")).put("unit",unit); assertEquals(operation,validate(installed)); program(language,backend,raw(installed)); } for(int i=0;i<((List<?>)call.get(2)).size();i++) { int index=i; assertThrows(RuntimeFault.class,()->program(language,backend,rawModule(call,source("post"),index))); } var shadowed=raw(call); var body=single((List<Map<String,Object>>)shadowed.get("bindings"),ignored->true).get("expr"); var copied=single(foreignCalls(body),ignored->true); copied.set(1,list("var","p0",((List<?>)copied.get(1)).get(2))); assertThrows(RuntimeFault.class,()->program(language,backend,shadowed)); } finally { context.leave(); } }
        }
    }
    @Test void stateBoundsAndWritableByteStoragePrecedeEffects() throws Exception {
        for(var backend:List.of("ast","bytecode")) try(var context=context()) { context.initialize("thc"); context.enter(); try { var language=TruffleLanguage.LanguageReference.create(Language.class).get(null); var scratch=setup(); var symlink=program(language,backend,raw(original("pathSymlink"))).entryTarget("entry"); var readlink=program(language,backend,raw(original("pathReadlink"))).entryTarget("entry"); var stdio=Language.currentState().getStdio(); byte[] outputBytes=new byte[32]; Arrays.fill(outputBytes,(byte)90); var output=ManagedAddress.fromByteArray(outputBytes).plus(8); var missing=path(scratch,"missing".getBytes(StandardCharsets.UTF_8)); assertEquals(-1L,stdio.close(-1)); long prior=stdio.errno(); assertThrows(RuntimeFault.class,()->Calls.target(symlink,new Object[]{0L,address("target".getBytes(StandardCharsets.UTF_8)),path(scratch,"new".getBytes(StandardCharsets.UTF_8)),9L})); assertFalse(Files.exists(scratch.resolve("new")));
            class Read { Object call(ManagedAddress destination,long capacity,Object token) { return Calls.target(readlink,new Object[]{0L,missing,destination,capacity,token}); } Object call(ManagedAddress destination) { return call(destination,16,thc.runtime.Unit.INSTANCE); } } var read=new Read(); assertThrows(RuntimeFault.class,()->read.call(output,16,9L)); for(long capacity:new long[]{-1,(long)Integer.MAX_VALUE+1}) assertThrows(RuntimeFault.class,()->read.call(output,capacity,thc.runtime.Unit.INSTANCE)); for(var bad:List.of(ManagedAddress.nullAddress(),ManagedAddress.fromByteArray(new byte[15]),ManagedAddress.fromHex("5a".repeat(16)),output.plus(9))) assertThrows(RuntimeFault.class,()->read.call(bad)); var allocation=ManagedAllocation.mutable(32,8); allocation.writeAddressByteOffset(8,output); assertThrows(RuntimeFault.class,()->read.call(ManagedAddress.fromAllocation(allocation))); assertSame(output,allocation.readAddressByteOffset(8)); assertEquals(prior,stdio.errno()); for(byte value:outputBytes) assertEquals((byte)90,value); assertEquals(-1,read.call(output)); assertEquals(StdioHostAbi.load().error(1),stdio.errno()); for(byte value:outputBytes) assertEquals((byte)90,value);
            // Path and destination can alias: snapshot the full path before publication.
            var raw=scratch.resolve("existing-link").toString().getBytes(StandardCharsets.UTF_8); var aliasedBytes=Arrays.copyOf(raw,raw.length+1); var alias=ManagedAddress.fromByteArray(aliasedBytes); assertEquals(6,Calls.target(readlink,new Object[]{0L,alias,alias,(long)aliasedBytes.length,thc.runtime.Unit.INSTANCE})); assertArrayEquals("target".getBytes(StandardCharsets.UTF_8),Arrays.copyOfRange(aliasedBytes,0,6)); assertEquals(0,Calls.target(symlink,new Object[]{0L,address("../target".getBytes(StandardCharsets.UTF_8)),path(scratch,"new".getBytes(StandardCharsets.UTF_8)),thc.runtime.Unit.INSTANCE})); assertEquals(Path.of("../target"),Files.readSymbolicLink(scratch.resolve("new"))); released(language);
        } finally { context.leave(); } }
        for(var backend:List.of("ast","bytecode")) try(var context=Context.newBuilder("thc").build()) { context.initialize("thc"); context.enter(); try { var language=TruffleLanguage.LanguageReference.create(Language.class).get(null); var destination=directory.resolve("denied"); var symlink=program(language,backend,raw(original("pathSymlink"))).entryTarget("entry"); assertEquals(-1,Calls.target(symlink,new Object[]{0L,address("target".getBytes(StandardCharsets.UTF_8)),cstring(destination.toString()),thc.runtime.Unit.INSTANCE})); assertEquals(StdioHostAbi.load().error(7),Language.currentState().getStdio().errno()); assertFalse(Files.exists(destination)); byte[] bytes=new byte[16]; Arrays.fill(bytes,(byte)90); var readlink=program(language,backend,raw(original("pathReadlink"))).entryTarget("entry"); assertEquals(-1,Calls.target(readlink,new Object[]{0L,cstring(destination.toString()),ManagedAddress.fromByteArray(bytes),16L,thc.runtime.Unit.INSTANCE})); assertEquals(StdioHostAbi.load().error(7),Language.currentState().getStdio().errno()); for(byte value:bytes) assertEquals((byte)90,value); } finally { context.leave(); } }
    }
    @Test void nativeOutputAliasesKeepContextAndLifetimeChecks() throws Exception {
        for(var backend:List.of("ast","bytecode")) try(var first=context()) { first.initialize("thc"); first.enter(); try { var language=TruffleLanguage.LanguageReference.create(Language.class).get(null); var scratch=setup(); var state=Language.currentState(); var base=state.getNativeAllocations().malloc(32); var alias=base.plus(8); var entry=program(language,backend,raw(original("pathReadlink"))).entryTarget("entry"); try { base.fill(32,90); assertEquals(6,Calls.target(entry,new Object[]{0L,path(scratch,"existing-link".getBytes(StandardCharsets.UTF_8)),alias,16L,thc.runtime.Unit.INSTANCE})); byte[] actual=new byte[6]; for(int i=0;i<actual.length;i++) actual[i]=(byte)alias.readWord8(i); assertArrayEquals("target".getBytes(StandardCharsets.UTF_8),actual); for(long i=0;i<=7;i++) assertEquals(90L,base.readWord8(i)); for(long i=14;i<=31;i++) assertEquals(90L,base.readWord8(i)); try(var second=context()) { second.initialize("thc"); second.enter(); try { var other=TruffleLanguage.LanguageReference.create(Language.class).get(null); var foreign=program(other,backend,raw(original("pathReadlink"))).entryTarget("entry"); assertThrows(RuntimeFault.class,()->Calls.target(foreign,new Object[]{0L,cstring(scratch.resolve("existing-link").toString()),alias,16L,thc.runtime.Unit.INSTANCE})); released(other); } finally { second.leave(); } } } finally { state.getNativeAllocations().free(base); } assertThrows(RuntimeFault.class,()->Calls.target(entry,new Object[]{0L,path(scratch,"existing-link".getBytes(StandardCharsets.UTF_8)),alias,16L,thc.runtime.Unit.INSTANCE})); released(language); } finally { first.leave(); } }
    }
}
