// SPDX-FileCopyrightText: 2026 Edward Kmett
// SPDX-License-Identifier: UPL-1.0 AND BSD-3-Clause
package thc.runtime;

import com.oracle.truffle.api.RootCallTarget;
import com.oracle.truffle.api.TruffleLanguage;
import com.oracle.truffle.api.bytecode.BytecodeConfig;
import com.oracle.truffle.api.bytecode.ContinuationResult;
import com.oracle.truffle.api.frame.VirtualFrame;
import org.graalvm.polyglot.Context;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.*;
import org.junit.jupiter.api.io.TempDir;
import thc.*;
import java.io.File;
import java.net.URI;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;
import static thc.runtime.ScalarTestCalls.callScalarTestTarget;
import static thc.runtime.OriginalStdioChecks.*;

/** Genuine installed GHC and Unix declarations, with native-compiled consumers. */
@EnabledOnOs(OS.LINUX)
@EnabledIfSystemProperty(named="os.arch",matches="amd64|x86_64")
@SuppressWarnings("unchecked")
class OriginalFstatAtTest {
    @TempDir Path directory;
    private final File root=new File(System.getProperty("thc.projectRoot"));
    private final String prefix="build/original-fstatat";
    private Map<String,Object> json(String path) throws Exception { return (Map<String,Object>)Json.parse(Files.readString(new File(root,path).toPath())); }
    private Map<String,Object> source(String stage) throws Exception { return json(prefix+"/"+stage+".json"); }
    private Object copy(Object value) { return Json.parse(Json.stringify(value)); }
    private ManagedAddress cstring(String value) { var bytes=value.getBytes(StandardCharsets.UTF_8); return ManagedAddress.fromByteArray(Arrays.copyOf(bytes,bytes.length+1)); }
    private ExecutableProgram program(Language language,String backend,Map<String,Object> module) { return backend.equals("ast")?new Program(language,module):new BytecodeProgram(language,module); }
    private Context context() { return NativeFileProvider.createContext(Set.of(),ContextProfile.SYNCHRONOUS_TEST); }
    private void valid(RootCallTarget target) throws Exception { assertEquals(true,target.getClass().getMethod("isValidLastTier").invoke(target)); }
    private void released(Language language) { var handoff=language.getHandoffState().get(); assertEquals(0,handoff.getArguments().getDepth()); assertEquals(0,handoff.getResults().getDepth()); assertEquals(0,handoff.getArguments().retainedReferences()); assertEquals(0,handoff.getResults().retainedReferences()); }
    private OriginalStdioOp validate(List<Object> call) { var reps=new ArrayList<Object>(); for(var arg:(List<List<Object>>)call.get(2)) { var metadata=CoreRepresentations.metadata(arg); reps.add(metadata==null?null:metadata.get("rep")); } return CoreOriginalStdio.validate(call.get(6),reps,(List<?>)call.get(3),((Map<?,?>)call.get(6)).get("rep")); }
    private List<Object> original() throws Exception { return original("post"); }
    private List<Object> original(String stage) throws Exception { return single(foreignCalls(CoreModules.reachable(source(stage),"pathFstatAt")),ignored->true); }
    private Map<String,Object> raw() throws Exception { return raw(original()); }
    private Map<String,Object> raw(List<Object> call) throws Exception { return rawModule(call,source("post")); }
    private Path rawPath(Path scratch,byte[] bytes) { var suffix=new StringBuilder(); for(byte value:bytes) suffix.append(String.format(Locale.ROOT,"%%%02X",value&255)); return Path.of(URI.create(scratch.toUri().toASCIIString()+suffix)); }
    private long readOnly() throws Exception { return StdioHostAbi.load().flagConstant(OriginalStdioOp.O_RDONLY); }
    private long open(Path path) throws Exception { long fd=Language.currentState().getStdio().open(cstring(path.toString()),readOnly(),0); assertTrue(fd>=3); return fd; }
    private long field(ManagedAddress address,OriginalStdioOp operation) { return PosixStat.execute(operation,address,0); }
    private int size() { return (int)field(ManagedAddress.nullAddress(),OriginalStdioOp.SIZEOF_STAT); }
    private void cwd(Path path) { var env=Language.currentState().getEnv(); env.setCurrentWorkingDirectory(env.getPublicTruffleFile(path.toString())); }
    private Path setup() throws Exception { var scratch=Files.createTempDirectory(directory,"native-"); Files.setAttribute(scratch,"unix:mode",448); byte[] bytes=new byte[32]; for(int i=0;i<bytes.length;i++) bytes[i]=(byte)i; Files.write(scratch.resolve("target"),bytes); Files.writeString(scratch.resolve("regular"),"unchanged"); for(var name:List.of("target","regular")) Files.setAttribute(scratch.resolve(name),"unix:mode",416); Files.createDirectory(scratch.resolve("sub")); Files.setAttribute(scratch.resolve("sub"),"unix:mode",488); Files.createSymbolicLink(scratch.resolve("link"),Path.of("target")); Files.createSymbolicLink(scratch.resolve("dangling"),Path.of("absent-target")); Files.createSymbolicLink(rawPath(scratch,new byte[]{-1,110}),Path.of("target")); return scratch; }
    private ManagedAddress rowAddress(Path scratch,Map<String,Object> row) { var values=(List<Long>)row.get("path"); byte[] bytes=new byte[values.size()]; for(int i=0;i<bytes.length;i++) bytes[i]=values.get(i).byteValue(); byte[] anchor=bytes.length==0?new byte[0]:Objects.equals(row.get("absolute"),true)?(scratch+"/").getBytes(StandardCharsets.UTF_8):Objects.equals(row.get("fdMode"),"cwd")?(Path.of(Language.currentState().getEnv().getCurrentWorkingDirectory().getPath()).relativize(scratch)+"/").getBytes(StandardCharsets.UTF_8):new byte[0]; byte[] result=Arrays.copyOf(anchor,anchor.length+bytes.length+1); System.arraycopy(bytes,0,result,anchor.length,bytes.length); return ManagedAddress.fromByteArray(result); }
    private List<Long> values(ManagedAddress destination,Path target) throws Exception { long mode=field(destination,OriginalStdioOp.ST_MODE); boolean isDirectory=PosixStat.execute(OriginalStdioOp.IS_DIR,ManagedAddress.nullAddress(),mode)!=0; return List.of(isDirectory?-1L:field(destination,OriginalStdioOp.ST_SIZE),mode&65535L,field(destination,OriginalStdioOp.ST_DEV)==((Number)Files.getAttribute(target,"unix:dev")).longValue()?1L:0L,field(destination,OriginalStdioOp.ST_INO)==((Number)Files.getAttribute(target,"unix:ino")).longValue()?1L:0L); }
    @Test void genuineNativeImagesMatchBothBackendsAndEveryFirstInstalledCall() throws Exception {
        var manifest=json(prefix+"/manifest.json"); assertEquals(List.of("pathFstatAt"),manifest.get("entries")); hashes(root,manifest.get("inputHashes"),Set.of("test/fixtures/compiler/OriginalFstatAtAudit.hs","test/haskell-fixtures/OriginalFstatAtFixtures.hs","src/main/c/stdio-abi-probe.c","bin/core_original_foreign.py","bin/core-capabilities.json")); var artifacts=new HashSet<>(Set.of(prefix+"/oracle.json")); for(var stage:List.of("pre","post")) { artifacts.add(prefix+"/"+stage+".json"); artifacts.add(prefix+"/"+stage+"-pathFstatAt.audit.json"); } hashes(root,manifest.get("artifactHashes"),artifacts,prefix+"/"); var oracle=json(prefix+"/oracle.json"); var at=(Map<?,?>)oracle.get("at"); var abi=StdioHostAbi.load(); assertEquals(at.get("AT_FDCWD"),abi.getAtFdcwd()); assertEquals(at.get("AT_SYMLINK_NOFOLLOW"),abi.getAtSymlinkNoFollow()); assertEquals(at.get("AT_EMPTY_PATH"),abi.getAtEmptyPath()); int imageSize=size(); assertEquals(oracle.get("size"),(long)imageSize); var rows=(List<Map<String,Object>>)oracle.get("rows"); assertEquals(47,rows.size()); var names=new HashSet<Object>(); var modes=new HashSet<Object>(); int empty=0; boolean absoluteInvalid=false,wideFlags=false,wideFd=false; for(var row:rows) { names.add(row.get("name")); modes.add(row.get("fdMode")); if(((List<?>)row.get("path")).isEmpty()) empty++; absoluteInvalid|=Objects.equals(row.get("absolute"),true)&&Objects.equals(row.get("fdMode"),"invalid"); wideFlags|=Objects.equals(row.get("flags"),0x1_0000_0000L); wideFd|=Objects.equals(row.get("fdOffset"),0x1_0000_0000L); } assertEquals(47,names.size()); assertEquals(Set.of("cwd","directory","duplicate","closed","regular","invalid"),modes); assertEquals(18,empty); assertTrue(absoluteInvalid); assertTrue(wideFlags); assertTrue(wideFd);
        for(var stage:List.of("pre","post")) { var audit=json(prefix+"/"+stage+"-pathFstatAt.audit.json"); assertEquals(true,audit.get("accepted")); assertEquals(List.of(),audit.get("issues")); assertEquals(List.of(),audit.get("missingGlobals")); var linked=with(CoreModules.reachable(source(stage),"pathFstatAt"),"instrument",true); var evidence=new ArrayCoreEvidence(linked,"pathFstatAt"); assertEquals(1,evidence.getBindings().size()); assertEquals(1,evidence.guestLambdas(evidence.getRoot().get("expr")).size()); assertEquals(1,evidence.loweredGuestLambdas(evidence.getRoot().get("expr")).size()); assertEquals(OriginalStdioOp.FSTATAT,validate(original(stage)));
            for(var backend:List.of("ast","bytecode")) try(var context=context()) { context.initialize("thc"); context.enter(); try { var language=TruffleLanguage.LanguageReference.create(Language.class).get(null);
                // Keep CWD and row fixtures on the same filesystem. Match the native
                // CWD's recorded permissions, while using a different actual directory.
                var anchor=Files.createTempDirectory(directory,"context-cwd-"); Files.setAttribute(anchor,"unix:mode",((Number)oracle.get("cwdMode")).intValue()&4095); cwd(anchor); var executable=program(language,backend,linked); var entry=executable.entryTarget("pathFstatAt"); var stdio=Language.currentState().getStdio(); class Exercise { void run(boolean compiled) throws Exception { for(var row:rows) { var scratch=setup(); Long owned=null; long fd; switch((String)row.get("fdMode")) { case "cwd" -> fd=abi.getAtFdcwd(); case "invalid" -> fd=-1; case "directory" -> { fd=open(scratch); owned=fd; } case "regular" -> { fd=open(scratch.resolve("regular")); owned=fd; } case "closed" -> { fd=open(scratch); assertEquals(0L,stdio.close(fd)); } case "duplicate" -> { long first=open(scratch); fd=stdio.duplicate(first); assertTrue(fd>=3); owned=fd; assertEquals(0L,stdio.close(first)); } default -> throw new IllegalStateException("Unknown native descriptor setup"); }
                    try { byte[] bytes=new byte[imageSize+16]; Arrays.fill(bytes,(byte)90); var destination=ManagedAddress.fromByteArray(bytes).plus(8); assertEquals(-1L,stdio.close(-1)); long before=((Number)executable.diagnostics().get("compiledEntries")).longValue(); if(compiled) valid(entry); assertEquals(row.get("status"),Calls.target(entry,new Object[]{0L,fd+(Long)row.get("fdOffset"),rowAddress(scratch,row),destination,row.get("flags")}),stage+"/"+backend+"/"+row.get("name")); assertEquals(row.get("errno"),stdio.errno(),Objects.toString(row.get("name"))); if(compiled) { assertEquals(before+1,((Number)executable.diagnostics().get("compiledEntries")).longValue()); valid(entry); } assertEquals(true,row.get("guardsIntact")); if(Objects.equals(row.get("status"),0L)) { assertEquals(row.get("values"),values(destination,scratch.resolve("target")),Objects.toString(row.get("name"))); for(int i=0;i<8;i++) assertEquals((byte)90,bytes[i]); for(int i=imageSize+8;i<bytes.length;i++) assertEquals((byte)90,bytes[i]); } else for(byte value:bytes) assertEquals((byte)90,value); released(language); } finally { if(owned!=null) assertEquals(0L,stdio.close(owned)); }
                } } } var exercise=new Exercise(); exercise.run(false); entry.getClass().getMethod("compile",boolean.class).invoke(entry,true); valid(entry); exercise.run(true); assertEquals(0L,((Number)executable.diagnostics().get("unsupportedTraps")).longValue());
            } finally { context.leave(); } }
        }
    }
    @Test void exactDirectoryWrapperOwnerSafeAbiAndStoredProofsRemainRequired() throws Exception {
        var call=original(); assertEquals(OriginalStdioOp.FSTATAT,validate(call)); var owner=((Map<?,?>)((Map<?,?>)((Map<?,?>)call.get(6)).get("foreignCall")).get("target")).get("unit"); assertEquals(json(prefix+"/manifest.json").get("directoryUnit"),owner); class Declaration { String label(String suffix) { return "ghczuwrapperZC1ZCdirectoryzm1zi3zi10zi0zm"+suffix+"ZCSystemziDirectoryziInternalziPosixZCfstatat"; } List<Object> make(String unit,String symbol) { var result=(List<Object>)copy(call); var target=(Map<String,Object>)((Map<?,?>)((Map<?,?>)result.get(6)).get("foreignCall")).get("target"); target.put("unit",unit); target.put("symbol",symbol); return result; } } var declaration=new Declaration(); for(var suffix:List.of("inplace","02fc","deadbeef")) { assertEquals(OriginalStdioOp.FSTATAT,validate(declaration.make("directory-1.3.10.0-"+suffix,declaration.label(suffix)))); var other=suffix.equals("inplace")?"02fc":"inplace"; assertThrows(RuntimeFault.class,()->validate(declaration.make("directory-1.3.10.0-"+suffix,declaration.label(other)))); }
        for(var edit:List.of(list("safety","unsafe"),list("safety","interruptible"),list("convention","ccall"),list("arity",4L),list("suppliedArity",4L))) { var bad=(List<Object>)copy(call); ((Map<String,Object>)((Map<?,?>)bad.get(6)).get("foreignCall")).put((String)edit.get(0),edit.get(1)); assertThrows(RuntimeFault.class,()->validate(bad)); } for(var unit:List.of("main","ghc-internal","unix-2.8.8.0-inplace","directory-1.3.9.0-inplace","directory-1.3.10.0-","directory-1.3.10.0-ABCD","directory-1.3.10.0-02fc:forged")) assertThrows(RuntimeFault.class,()->validate(declaration.make(unit,declaration.label("02fc"))));
        for(var backend:List.of("ast","bytecode")) try(var context=context()) { context.initialize("thc"); context.enter(); try { var language=TruffleLanguage.LanguageReference.create(Language.class).get(null); for(var symbol:List.of(declaration.label("02FC"),declaration.label("nothex"),declaration.label(""),declaration.label("02fc").replace("ZC1ZC","ZC2ZC"),declaration.label("02fc").replace("InternalziPosix","InternalziWindows"),declaration.label("02fc").replace("ZCfstatat","ZCstat"))) assertThrows(RuntimeFault.class,()->program(language,backend,raw(declaration.make("directory-1.3.10.0-02fc",symbol)))); for(int i=0;i<=4;i++) { int index=i; assertThrows(RuntimeFault.class,()->program(language,backend,rawModule(call,source("post"),index))); } var shadowed=raw(call); var copied=single(foreignCalls(shadowed),ignored->true); copied.set(1,list("var","p0",((List<?>)copied.get(1)).get(2))); assertThrows(RuntimeFault.class,()->program(language,backend,shadowed)); for(int index:new int[]{0,3}) for(var rep:List.of("IntRep","Word32Rep","Word64Rep")) { var bad=(List<Object>)copy(call); var descriptor=(Map<String,Object>)((Map<?,?>)bad.get(6)).get("foreignCall"); ((List<Map<String,Object>>)descriptor.get("argumentReps")).get(index).put("primReps",list(rep)); assertThrows(RuntimeFault.class,()->program(language,backend,raw(bad))); } } finally { context.leave(); } }
    }
    @Test void stateCanonicalIntegersAndCompleteDestinationChecksPrecedeObservation() throws Exception {
        int imageSize=size(); for(var backend:List.of("ast","bytecode")) try(var context=context()) { context.initialize("thc"); context.enter(); try { var language=TruffleLanguage.LanguageReference.create(Language.class).get(null); var entry=program(language,backend,raw()).entryTarget("entry"); var stdio=Language.currentState().getStdio(); byte[] bytes=new byte[imageSize+16]; Arrays.fill(bytes,(byte)90); var destination=ManagedAddress.fromByteArray(bytes).plus(8); var path=cstring(directory.resolve("missing").toString()); int fd=(int)StdioHostAbi.load().getAtFdcwd(); class Invoke { Object call(ManagedAddress output,ManagedAddress path,Object fd,Object flags,Object token) { return callScalarTestTarget(entry,new Object[]{0L,fd,path,output,flags,token}); } Object call(ManagedAddress output) { return call(output,path,fd,0,thc.runtime.Unit.INSTANCE); } } var invoke=new Invoke(); assertThrows(RuntimeFault.class,()->Calls.target(entry,new Object[]{0L,fd,path,destination,0,9L})); assertEquals(-1L,stdio.close(-1)); long prior=stdio.errno(); assertThrows(RuntimeFault.class,()->invoke.call(destination,path,fd,0,9L)); for(long number:new long[]{(long)Integer.MIN_VALUE-1,(long)Integer.MAX_VALUE+1,0x1_0000_0000L}) { assertThrows(RuntimeFault.class,()->invoke.call(destination,path,number,0,thc.runtime.Unit.INSTANCE)); assertThrows(RuntimeFault.class,()->invoke.call(destination,path,fd,number,thc.runtime.Unit.INSTANCE)); } for(var bad:List.of(ManagedAddress.nullAddress(),ManagedAddress.fromByteArray(new byte[imageSize-1]),ManagedAddress.fromHex("00".repeat(imageSize)),destination.plus(9))) assertThrows(RuntimeFault.class,()->invoke.call(bad)); var allocation=ManagedAllocation.mutable(imageSize+16L,8); allocation.writeAddressByteOffset(8,destination); assertThrows(RuntimeFault.class,()->invoke.call(ManagedAddress.fromAllocation(allocation))); assertSame(destination,allocation.readAddressByteOffset(8)); for(var bad:List.of(ManagedAddress.nullAddress(),ManagedAddress.fromByteArray(new byte[]{65}),ManagedAddress.fromAllocation(allocation).plus(8))) assertThrows(RuntimeFault.class,()->invoke.call(destination,bad,fd,0,thc.runtime.Unit.INSTANCE)); assertEquals(prior,stdio.errno()); for(byte value:bytes) assertEquals((byte)90,value); assertEquals(-1,invoke.call(destination)); assertEquals(StdioHostAbi.load().error(1),stdio.errno()); for(byte value:bytes) assertEquals((byte)90,value); released(language); } finally { context.leave(); } }
        for(var backend:List.of("ast","bytecode")) try(var context=Context.newBuilder("thc").build()) { context.initialize("thc"); context.enter(); try { var language=TruffleLanguage.LanguageReference.create(Language.class).get(null); byte[] bytes=new byte[imageSize]; Arrays.fill(bytes,(byte)90); var entry=program(language,backend,raw()).entryTarget("entry"); assertEquals(-1,callScalarTestTarget(entry,new Object[]{0L,-999,cstring(directory.toString()),ManagedAddress.fromByteArray(bytes),0,thc.runtime.Unit.INSTANCE})); assertEquals(StdioHostAbi.load().error(7),Language.currentState().getStdio().errno()); for(byte value:bytes) assertEquals((byte)90,value); } finally { context.leave(); } }
    }
    @Test void emptyPathUsesContextDirectoryAndFollowsItsSymlinkAnchorWithNoFollow() throws Exception {
        var first=Files.createDirectory(directory.resolve("first")); var second=Files.createDirectory(directory.resolve("second")); var link=Files.createSymbolicLink(directory.resolve("anchor-link"),Path.of("second")); var abi=StdioHostAbi.load(); for(var backend:List.of("ast","bytecode")) try(var context=context()) { context.initialize("thc"); context.enter(); try { var language=TruffleLanguage.LanguageReference.create(Language.class).get(null); var env=Language.currentState().getEnv(); var initialCwd=env.getCurrentWorkingDirectory().getPath(); var entry=program(language,backend,raw()).entryTarget("entry"); for(var anchor:List.of(first,second,link)) { cwd(anchor); for(long flags:new long[]{abi.getAtEmptyPath(),abi.getAtEmptyPath()|abi.getAtSymlinkNoFollow()}) { byte[] bytes=new byte[size()]; Arrays.fill(bytes,(byte)90); var destination=ManagedAddress.fromByteArray(bytes); assertEquals(0,callScalarTestTarget(entry,new Object[]{0L,(int)abi.getAtFdcwd(),cstring(""),destination,(int)flags,thc.runtime.Unit.INSTANCE})); assertEquals(((Number)Files.getAttribute(anchor,"unix:ino")).longValue(),field(destination,OriginalStdioOp.ST_INO)); assertEquals(((Number)Files.getAttribute(anchor,"unix:mode")).longValue(),field(destination,OriginalStdioOp.ST_MODE)); assertEquals(1L,PosixStat.execute(OriginalStdioOp.IS_DIR,ManagedAddress.nullAddress(),field(destination,OriginalStdioOp.ST_MODE))); } byte[] unchanged=new byte[size()]; Arrays.fill(unchanged,(byte)90); assertEquals(-1,callScalarTestTarget(entry,new Object[]{0L,(int)abi.getAtFdcwd(),cstring(""),ManagedAddress.fromByteArray(unchanged),0,thc.runtime.Unit.INSTANCE})); assertEquals(abi.error(1),Language.currentState().getStdio().errno()); for(byte value:unchanged) assertEquals((byte)90,value); } try(var other=context()) { other.initialize("thc"); other.enter(); try { assertEquals(initialCwd,Language.currentState().getEnv().getCurrentWorkingDirectory().getPath()); } finally { other.leave(); } } released(language); } finally { context.leave(); } }
    }
    @Test void aliasedNativeImagesAndDirectoryDuplicatesKeepContextAndLifetimeChecks() throws Exception {
        int imageSize=size(); for(var backend:List.of("ast","bytecode")) try(var first=context()) { first.initialize("thc"); first.enter(); try { var language=TruffleLanguage.LanguageReference.create(Language.class).get(null); var scratch=setup(); var state=Language.currentState(); long fd=open(scratch); long duplicate=state.getStdio().duplicate(fd); assertTrue(duplicate>=3); assertNotEquals(fd,duplicate); assertEquals(0L,state.getStdio().close(fd)); var entry=program(language,backend,raw()).entryTarget("entry"); var base=state.getNativeAllocations().malloc(imageSize+16L); var alias=base.plus(8); try { base.fill(imageSize+16L,90);
            // Path bytes and the output share an allocation. The input snapshot
            // must finish before successful stat publication overwrites it.
            ManagedAddress.fromByteArray(new byte[]{116,97,114,103,101,116,0}).copyNonOverlappingTo(alias,7); try(var second=context()) { second.initialize("thc"); second.enter(); try { var other=TruffleLanguage.LanguageReference.create(Language.class).get(null); var foreign=program(other,backend,raw()).entryTarget("entry"); assertThrows(RuntimeFault.class,()->callScalarTestTarget(foreign,new Object[]{0L,(int)duplicate,cstring("target"),alias,0,thc.runtime.Unit.INSTANCE})); byte[] untouched=new byte[imageSize]; Arrays.fill(untouched,(byte)90); assertEquals(-1,callScalarTestTarget(foreign,new Object[]{0L,(int)duplicate,cstring("target"),ManagedAddress.fromByteArray(untouched),0,thc.runtime.Unit.INSTANCE})); assertEquals(StdioHostAbi.load().error(4),Language.currentState().getStdio().errno()); for(byte value:untouched) assertEquals((byte)90,value); released(other); } finally { second.leave(); } } assertEquals(0,callScalarTestTarget(entry,new Object[]{0L,(int)duplicate,alias,alias,0,thc.runtime.Unit.INSTANCE})); assertEquals(32L,field(alias,OriginalStdioOp.ST_SIZE)); for(long i=0;i<=7;i++) { assertEquals(90L,base.readWord8(i)); assertEquals(90L,base.readWord8(imageSize+8L+i)); } assertEquals(0L,state.getStdio().close(duplicate)); base.fill(imageSize+16L,90); assertEquals(-1,callScalarTestTarget(entry,new Object[]{0L,(int)duplicate,cstring("target"),alias,0,thc.runtime.Unit.INSTANCE})); for(long i=0;i<imageSize+16L;i++) assertEquals(90L,base.readWord8(i)); } finally { state.getNativeAllocations().free(base); } assertThrows(RuntimeFault.class,()->callScalarTestTarget(entry,new Object[]{0L,(int)StdioHostAbi.load().getAtFdcwd(),cstring(scratch.resolve("target").toString()),alias,0,thc.runtime.Unit.INSTANCE})); released(language); } finally { first.leave(); } }
    }
    @Test void completedSafeStatResumesWithTheSavedImageWithoutReplay() throws Exception {
        try(var context=context()) { context.initialize("thc"); context.enter(); try { var language=TruffleLanguage.LanguageReference.create(Language.class).get(null); var state=Language.currentState(); var identity=state.getThreads().enterCurrent(); try { var file=Files.writeString(directory.resolve("completed"),"before"); byte[] image=new byte[size()]; Arrays.fill(image,(byte)90); var destination=ManagedAddress.fromByteArray(image); var proof=CoreRepresentations.parse(((Map<?,?>)original().get(6)).get("rep")); var layout=new FrameLayout(); int[] slots={layout.bind("completed CInt")}; var shape=new TupleShape(proof,language); class Enqueue extends Expr { AsyncRequest pending; int evaluated; @Override public Object execute(VirtualFrame frame) { evaluated++; pending=state.getThreads().send(identity,"after fstatat"); return thc.runtime.Unit.INSTANCE; } } var enqueue=new Enqueue(); java.util.function.Function<Object,Expr> value=v->new Expr() { @Override public Object execute(VirtualFrame frame) { return v; } }; var body=new OriginalStdioExpression(OriginalStdioOp.FSTATAT,new Expr[]{value.apply((int)StdioHostAbi.load().getAtFdcwd()),value.apply(cstring(file.toString())),value.apply(destination),value.apply(0),enqueue},proof); var ast=new FunctionRoot(language,layout.build(),"fstatat completion",null,new int[0],new int[0],new int[0],body,new Metrics(false),new CoreRepresentation[0],body.getRepresentation(),body.getCoreSourceLocation(),new boolean[0],null,shape,slots,null,true,new int[0][],false,FunctionRootRole.FUNCTION,false); var saved=Objects.requireNonNull(SavedGuestContinuations.savedGuestContinuation(Calls.target(ast.getCallTarget(),new Object[]{0L}))); assertSame(enqueue.pending,saved.asyncRequest()); assertEquals(6L,field(destination,OriginalStdioOp.ST_SIZE)); enqueue.pending.acknowledge(); Files.writeString(file,"changed after native stat"); var completed=saved.continueWith(thc.runtime.Unit.INSTANCE); assertEquals(0,shape.getLayout().getInt(TupleResults.ownedTupleResult(completed,shape),0)); assertEquals(6L,field(destination,OriginalStdioOp.ST_SIZE)); assertEquals(1,enqueue.evaluated); released(language);
            var request=state.getThreads().send(identity,"after bytecode fstatat"); long atFdcwd=StdioHostAbi.load().getAtFdcwd(); var target=BytecodeRootGen.create(language,BytecodeConfig.DEFAULT,b->{ b.beginRoot(); var result=b.createLocal("completed CInt","primitive"); var token=b.createLocal("pending request","object"); b.beginOriginalFstatAt(result); b.emitLoadConstant(atFdcwd); b.emitLoadConstant(cstring(file.toString())); b.emitLoadConstant(destination); b.emitLoadConstant(0L); b.emitLoadConstant(thc.runtime.Unit.INSTANCE); b.endOriginalFstatAt(); b.beginIfThen(); b.emitPollAsync(token); b.beginYield(); b.emitLoadLocal(token); b.endYield(); b.endIfThen(); b.beginReturn(); b.emitLoadLocal(result); b.endReturn(); b.endRoot(); }).getNode(0).getCallTarget(); var suspended=(ContinuationResult)Calls.target(target,new Object[]{0L}); assertSame(request,suspended.getResult()); long savedSize=Files.size(file); assertEquals(savedSize,field(destination,OriginalStdioOp.ST_SIZE)); request.acknowledge(); Files.writeString(file,"x"); assertEquals(0,suspended.continueWith(thc.runtime.Unit.INSTANCE)); assertEquals(savedSize,field(destination,OriginalStdioOp.ST_SIZE)); var lowered=(BytecodeRoot)new BytecodeProgram(language,raw(),true).entryTarget("entry").getRootNode(); var names=new ArrayList<String>(); for(var instruction:lowered.getBytecodeNode().getInstructions()) names.add(instruction.getName()); int effect=-1; for(int i=0;i<names.size();i++) if(names.get(i).toLowerCase(Locale.ROOT).contains("originalfstatat")) { effect=i; break; } assertTrue(effect>=0,names.toString()); boolean poll=false; for(int i=effect+1;i<names.size();i++) poll|=names.get(i).toLowerCase(Locale.ROOT).contains("pollasync"); assertTrue(poll,names.toString()); released(language);
        } finally { state.getThreads().leaveCurrent(); } } finally { context.leave(); } }
    }
}
