// SPDX-FileCopyrightText: 2026 Edward Kmett
// SPDX-License-Identifier: UPL-1.0 AND BSD-3-Clause
package thc.runtime;

import com.oracle.truffle.api.RootCallTarget;
import com.oracle.truffle.api.TruffleLanguage;
import org.graalvm.polyglot.Context;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.*;
import org.junit.jupiter.api.io.TempDir;
import thc.*;
import java.io.File;
import java.net.URI;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.nio.file.attribute.PosixFilePermissions;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;
import static thc.runtime.OriginalStdioChecks.*;

/** Genuine installed GHC and Unix declarations, with native-compiled consumers. */
@EnabledOnOs(OS.LINUX)
@EnabledIfSystemProperty(named="os.arch",matches="amd64|x86_64")
@SuppressWarnings("unchecked")
class OriginalPathStatTest {
    @TempDir Path directory;
    private final File root=new File(System.getProperty("thc.projectRoot"));
    private final String prefix="build/original-path-stat";
    private final Map<String,OriginalStdioOp> operations=new LinkedHashMap<>();
    OriginalPathStatTest() { operations.put("pathStat",OriginalStdioOp.STAT); operations.put("pathLstat",OriginalStdioOp.LSTAT); operations.put("unixPathLstat",OriginalStdioOp.UNIX_LSTAT); }
    private Map<String,Object> json(String path) throws Exception { return (Map<String,Object>)Json.parse(Files.readString(new File(root,path).toPath())); }
    private Map<String,Object> source(String stage) throws Exception { return json(prefix+"/"+stage+".json"); }
    private Object copy(Object value) { return Json.parse(Json.stringify(value)); }
    private ManagedAddress cstring(String value) { var bytes=value.getBytes(StandardCharsets.UTF_8); return ManagedAddress.fromByteArray(Arrays.copyOf(bytes,bytes.length+1)); }
    private ExecutableProgram program(Language language,String backend,Map<String,Object> module) { return backend.equals("ast")?new Program(language,module):new BytecodeProgram(language,module); }
    private Context context() { return NativeFileProvider.createContext(Set.of(),ContextProfile.SYNCHRONOUS_TEST); }
    private void valid(RootCallTarget target) throws Exception { assertEquals(true,target.getClass().getMethod("isValidLastTier").invoke(target)); }
    private void released(Language language) { var handoff=language.getHandoffState().get(); assertEquals(0,handoff.getArguments().getDepth()); assertEquals(0,handoff.getResults().getDepth()); assertEquals(0,handoff.getArguments().retainedReferences()); assertEquals(0,handoff.getResults().retainedReferences()); }
    private OriginalStdioOp validate(List<Object> call) { var reps=new ArrayList<Object>(); for(var arg:(List<List<Object>>)call.get(2)) { var metadata=CoreRepresentations.metadata(arg); reps.add(metadata==null?null:metadata.get("rep")); } return CoreOriginalStdio.validate(call.get(6),reps,(List<?>)call.get(3),((Map<?,?>)call.get(6)).get("rep")); }
    private List<Object> original(String name) throws Exception { return original(name,"post"); }
    private List<Object> original(String name,String stage) throws Exception { return single(foreignCalls(CoreModules.reachable(source(stage),name)),ignored->true); }
    private Map<String,Object> raw(List<Object> call) throws Exception { return rawModule(call,source("post")); }
    private long field(ManagedAddress address,OriginalStdioOp operation) { return PosixStat.execute(operation,address,0); }
    private ManagedAddress relativePath(byte[] bytes) {
        // The fixed native filesystem keeps its context CWD. Resolve the test
        // directory relative to that CWD while retaining raw bytes and ./...
        byte[] prefix=bytes.length==0?new byte[0]:(Path.of(Language.currentState().getEnv().getCurrentWorkingDirectory().getPath()).relativize(directory)+"/").getBytes(StandardCharsets.UTF_8); byte[] result=Arrays.copyOf(prefix,prefix.length+bytes.length+1); System.arraycopy(bytes,0,result,prefix.length,bytes.length); return ManagedAddress.fromByteArray(result);
    }
    @Test void originalNativePathImagesMatchBothBackendsAndFirstInstalledCalls() throws Exception {
        var manifest=json(prefix+"/manifest.json"); assertEquals(new ArrayList<>(operations.keySet()),manifest.get("entries")); assertTrue(CoreOriginalStdio.isOriginalUnixUnit(manifest.get("unixUnit"))); hashes(root,manifest.get("inputHashes"),Set.of("test/fixtures/compiler/OriginalPathStatAudit.hs","test/haskell-fixtures/OriginalPathStatFixtures.hs","bin/core_original_foreign.py","bin/core-capabilities.json")); var artifacts=new HashSet<>(Set.of(prefix+"/oracle.json")); for(var stage:List.of("pre","post")) { artifacts.add(prefix+"/"+stage+".json"); for(var name:operations.keySet()) artifacts.add(prefix+"/"+stage+"-"+name+".audit.json"); } hashes(root,manifest.get("artifactHashes"),artifacts,prefix+"/"); var oracle=json(prefix+"/oracle.json"); int size=((Number)oracle.get("size")).intValue(); assertEquals((long)size,field(ManagedAddress.nullAddress(),OriginalStdioOp.SIZEOF_STAT)); var rows=(List<Map<String,Object>>)oracle.get("rows"); var expectedRows=new ArrayList<List<Object>>(); for(var entry:operations.keySet()) for(var name:List.of("file","directory","link","dangling","missing","empty","not-directory","relative","raw-link")) expectedRows.add(list(entry,name)); var actualRows=new ArrayList<List<Object>>(); for(var row:rows) actualRows.add(list(row.get("entry"),row.get("name"))); assertEquals(expectedRows,actualRows);
        var targetPath=directory.resolve("target"); byte[] data=new byte[32]; for(int i=0;i<data.length;i++) data[i]=(byte)i; Files.write(targetPath,data); Files.setPosixFilePermissions(targetPath,PosixFilePermissions.fromString("rw-r-----")); var sub=Files.createDirectory(directory.resolve("sub")); Files.setPosixFilePermissions(sub,PosixFilePermissions.fromString("rwxr-x---")); Files.createSymbolicLink(directory.resolve("link"),Path.of("target")); Files.createSymbolicLink(directory.resolve("dangling"),Path.of("absent-target"));
        // URI decoding preserves the actual Unix 0xff byte; no replacement-character filename.
        Files.createSymbolicLink(Path.of(URI.create(directory.toUri().toASCIIString()+"%FFn")),Path.of("target")); long device=((Number)Files.getAttribute(targetPath,"unix:dev")).longValue(); long inode=((Number)Files.getAttribute(targetPath,"unix:ino")).longValue();
        for(var stage:List.of("pre","post")) for(var operation:operations.entrySet()) { var name=operation.getKey(); var audit=json(prefix+"/"+stage+"-"+name+".audit.json"); assertEquals(true,audit.get("accepted")); assertEquals(List.of(),audit.get("issues")); assertEquals(List.of(),audit.get("missingGlobals")); var linked=with(CoreModules.reachable(source(stage),name),"instrument",true); var evidence=new ArrayCoreEvidence(linked,name); assertEquals(1,evidence.getBindings().size()); assertEquals(1,evidence.guestLambdas(evidence.getRoot().get("expr")).size()); assertEquals(1,evidence.loweredGuestLambdas(evidence.getRoot().get("expr")).size()); assertEquals(operation.getValue(),validate(original(name,stage))); if(operation.getValue()==OriginalStdioOp.UNIX_LSTAT) assertEquals(manifest.get("unixUnit"),((Map<?,?>)((Map<?,?>)((Map<?,?>)original(name,stage).get(6)).get("foreignCall")).get("target")).get("unit"));
            for(var backend:List.of("ast","bytecode")) try(var context=context()) { context.initialize("thc"); context.enter(); try { var language=TruffleLanguage.LanguageReference.create(Language.class).get(null); var executable=program(language,backend,linked); var entry=executable.entryTarget(name); var stdio=Language.currentState().getStdio(); class Exercise { void run(boolean compiled) throws Exception { for(var row:rows) { if(!Objects.equals(row.get("entry"),name)) continue; byte[] bytes=new byte[size+16]; Arrays.fill(bytes,(byte)90); var destination=ManagedAddress.fromByteArray(bytes).plus(8); var pathValues=(List<Long>)row.get("path"); byte[] pathBytes=new byte[pathValues.size()]; for(int i=0;i<pathBytes.length;i++) pathBytes[i]=pathValues.get(i).byteValue(); var path=relativePath(pathBytes); assertEquals(-1L,stdio.close(-1)); long before=((Number)executable.diagnostics().get("compiledEntries")).longValue(); if(compiled) valid(entry); assertEquals(row.get("status"),Calls.target(entry,new Object[]{0L,path,destination}),stage+"/"+backend+"/"+name+"/"+row.get("name")); assertEquals(row.get("errno"),stdio.errno()); if(compiled) { assertEquals(before+1,((Number)executable.diagnostics().get("compiledEntries")).longValue()); valid(entry); } assertEquals(true,row.get("guardsIntact")); if(Objects.equals(row.get("status"),0L)) { long mode=field(destination,OriginalStdioOp.ST_MODE); boolean directory=PosixStat.execute(OriginalStdioOp.IS_DIR,ManagedAddress.nullAddress(),mode)!=0L; var values=List.of(directory?-1L:field(destination,OriginalStdioOp.ST_SIZE),mode&65535L,field(destination,OriginalStdioOp.ST_DEV)==device?1L:0L,field(destination,OriginalStdioOp.ST_INO)==inode?1L:0L); assertEquals(row.get("values"),values); for(int i=0;i<8;i++) assertEquals((byte)90,bytes[i]); for(int i=size+8;i<bytes.length;i++) assertEquals((byte)90,bytes[i]); } else for(byte value:bytes) assertEquals((byte)90,value); released(language); } } } var exercise=new Exercise(); exercise.run(false); entry.getClass().getMethod("compile",boolean.class).invoke(entry,true); valid(entry); exercise.run(true); assertEquals(0L,((Number)executable.diagnostics().get("unsupportedTraps")).longValue()); } finally { context.leave(); } }
        }
    }
    @Test void exactDescriptorOwnerStateAndStoredOperandProofsRemainRequired() throws Exception {
        for(var operationEntry:operations.entrySet()) { var call=original(operationEntry.getKey()); var operation=operationEntry.getValue(); assertEquals(operation,validate(call)); for(var edit:List.of(list("safety","safe"),list("convention",operation==OriginalStdioOp.UNIX_LSTAT?"ccall":"capi"),list("arity",2L),list("suppliedArity",2L))) { var bad=(List<Object>)copy(call); ((Map<String,Object>)((Map<?,?>)bad.get(6)).get("foreignCall")).put((String)edit.get(0),edit.get(1)); assertThrows(RuntimeFault.class,()->validate(bad)); } for(var unit:List.of("main","unix-2.8.7.0-inplace","unix-2.8.8.0-ABCD","unix-2.8.8.0-nothex",operation==OriginalStdioOp.UNIX_LSTAT?"ghc-internal":"unix-2.8.8.0-inplace")) { var bad=(List<Object>)copy(call); ((Map<String,Object>)((Map<?,?>)((Map<?,?>)bad.get(6)).get("foreignCall")).get("target")).put("unit",unit); assertThrows(RuntimeFault.class,()->validate(bad)); }
            for(var backend:List.of("ast","bytecode")) try(var context=context()) { context.initialize("thc"); context.enter(); try { var language=TruffleLanguage.LanguageReference.create(Language.class).get(null); for(int i=0;i<=2;i++) { int index=i; assertThrows(RuntimeFault.class,()->program(language,backend,rawModule(call,source("post"),index))); } var shadowed=raw(call); var body=single((List<Map<String,Object>>)shadowed.get("bindings"),ignored->true).get("expr"); var copied=single(foreignCalls(body),ignored->true); copied.set(1,list("var","p0",((List<?>)copied.get(1)).get(2))); assertThrows(RuntimeFault.class,()->program(language,backend,shadowed)); } finally { context.leave(); } }
        }
    }
    @Test void installedLstatWrapperMustEncodeItsExactOwner() throws Exception {
        var call=original("unixPathLstat"); class Declaration { String label(String suffix) { return "ghczuwrapperZC2ZCunixzm2zi8zi8zi0zm"+suffix+"ZCSystemziPosixziFilesziPosixStringZClstat"; } List<Object> make(String owner,String symbol) { var result=(List<Object>)copy(call); var target=(Map<String,Object>)((Map<?,?>)((Map<?,?>)result.get(6)).get("foreignCall")).get("target"); target.put("unit",owner); target.put("symbol",symbol); return result; } } var declaration=new Declaration();
        for(var suffix:List.of("inplace","460b","deadbeef")) { var accepted=declaration.make("unix-2.8.8.0-"+suffix,declaration.label(suffix)); assertEquals(OriginalStdioOp.UNIX_LSTAT,validate(accepted)); CoreOriginalStdio.validateHeads(accepted); for(var backend:List.of("ast","bytecode")) try(var context=context()) { context.initialize("thc"); context.enter(); try { var language=TruffleLanguage.LanguageReference.create(Language.class).get(null); program(language,backend,raw(accepted)); var shadowed=raw(accepted); var boundCall=single(foreignCalls(shadowed),ignored->true); boundCall.set(1,list("var","p0",((List<?>)boundCall.get(1)).get(2))); assertThrows(RuntimeFault.class,()->program(language,backend,shadowed)); var malformed=raw(accepted); var malformedCall=single(foreignCalls(malformed),ignored->true); malformedCall.set(1,list("var",17L,((List<?>)malformedCall.get(1)).get(2))); assertThrows(RuntimeFault.class,()->program(language,backend,malformed)); } finally { context.leave(); } } var otherSuffix=suffix.equals("inplace")?"460b":"inplace"; assertThrows(RuntimeFault.class,()->validate(declaration.make("unix-2.8.8.0-"+suffix,declaration.label(otherSuffix)))); }
        for(var badSymbol:List.of(declaration.label("460B"),declaration.label("nothex"),declaration.label(""),declaration.label("460b").replace("ZC2ZC","ZC3ZC"),declaration.label("460b").replace("PosixString","ByteString"),declaration.label("460b").replace("ZClstat","ZCstat"),declaration.label("460b").replace("2zi8zi8zi0","2zi8zi7zi0"))) { var rejected=declaration.make("unix-2.8.8.0-460b",badSymbol); assertNull(validate(rejected)); for(var backend:List.of("ast","bytecode")) try(var context=context()) { context.initialize("thc"); context.enter(); try { var language=TruffleLanguage.LanguageReference.create(Language.class).get(null); assertThrows(RuntimeFault.class,()->program(language,backend,raw(rejected))); } finally { context.leave(); } } }
    }
    @Test void stateAndCompleteDestinationValidationPrecedePathObservation() throws Exception {
        int size=(int)field(ManagedAddress.nullAddress(),OriginalStdioOp.SIZEOF_STAT); for(var name:operations.keySet()) for(var backend:List.of("ast","bytecode")) try(var context=context()) { context.initialize("thc"); context.enter(); try { var language=TruffleLanguage.LanguageReference.create(Language.class).get(null); var executable=program(language,backend,raw(original(name))); var entry=executable.entryTarget("entry"); var stdio=Language.currentState().getStdio(); byte[] bytes=new byte[size+16]; Arrays.fill(bytes,(byte)90); var destination=ManagedAddress.fromByteArray(bytes).plus(8); class Invoke { Object call(ManagedAddress output,Object token) { return Calls.target(entry,new Object[]{0L,relativePath("missing".getBytes(StandardCharsets.UTF_8)),output,token}); } Object call(ManagedAddress output) { return call(output,thc.runtime.Unit.INSTANCE); } } var invoke=new Invoke(); assertEquals(-1L,stdio.close(-1)); long prior=stdio.errno(); assertThrows(RuntimeFault.class,()->invoke.call(destination,9L)); for(var bad:List.of(ManagedAddress.nullAddress(),ManagedAddress.fromByteArray(new byte[size-1]),ManagedAddress.fromHex("00".repeat(size)),destination.plus(9))) assertThrows(RuntimeFault.class,()->invoke.call(bad)); var allocation=ManagedAllocation.mutable((long)size+16,8); var pointer=ManagedAddress.fromAllocation(allocation); allocation.writeAddressByteOffset(8,destination); assertThrows(RuntimeFault.class,()->invoke.call(pointer)); assertSame(destination,allocation.readAddressByteOffset(8)); assertEquals(prior,stdio.errno()); for(byte value:bytes) assertEquals((byte)90,value); assertEquals(-1,invoke.call(destination)); assertEquals(StdioHostAbi.load().error(1),stdio.errno()); for(byte value:bytes) assertEquals((byte)90,value); released(language); } finally { context.leave(); } }
        try(var context=Context.newBuilder("thc").build()) { context.initialize("thc"); context.enter(); try { var language=TruffleLanguage.LanguageReference.create(Language.class).get(null); byte[] bytes=new byte[size]; Arrays.fill(bytes,(byte)90); var executable=program(language,"ast",raw(original("pathStat"))); assertEquals(-1,Calls.target(executable.entryTarget("entry"),new Object[]{0L,cstring(directory.toString()),ManagedAddress.fromByteArray(bytes),thc.runtime.Unit.INSTANCE})); assertEquals(StdioHostAbi.load().error(7),Language.currentState().getStdio().errno()); for(byte value:bytes) assertEquals((byte)90,value); } finally { context.leave(); } }
    }
    @Test void ownedNativeDestinationAliasesKeepContextAndLifetimeChecks() throws Exception {
        long size=field(ManagedAddress.nullAddress(),OriginalStdioOp.SIZEOF_STAT); Files.writeString(directory.resolve("target"),"owned"); for(var backend:List.of("ast","bytecode")) try(var first=context()) { first.initialize("thc"); first.enter(); try { var language=TruffleLanguage.LanguageReference.create(Language.class).get(null); var state=Language.currentState(); var base=state.getNativeAllocations().malloc(size+16); var alias=base.plus(8); var entry=program(language,backend,raw(original("pathStat"))).entryTarget("entry"); try { base.fill(size+16,90); assertEquals(0,Calls.target(entry,new Object[]{0L,relativePath("target".getBytes(StandardCharsets.UTF_8)),alias,thc.runtime.Unit.INSTANCE})); assertEquals(5L,field(alias,OriginalStdioOp.ST_SIZE)); for(long i=0;i<=7;i++) { assertEquals(90L,base.readWord8(i)); assertEquals(90L,base.readWord8(size+8+i)); } try(var second=context()) { second.initialize("thc"); second.enter(); try { var other=TruffleLanguage.LanguageReference.create(Language.class).get(null); var foreign=program(other,backend,raw(original("pathStat"))).entryTarget("entry"); assertThrows(RuntimeFault.class,()->Calls.target(foreign,new Object[]{0L,cstring(directory.resolve("target").toString()),alias,thc.runtime.Unit.INSTANCE})); released(other); } finally { second.leave(); } } } finally { state.getNativeAllocations().free(base); } assertThrows(RuntimeFault.class,()->Calls.target(entry,new Object[]{0L,relativePath("target".getBytes(StandardCharsets.UTF_8)),alias,thc.runtime.Unit.INSTANCE})); released(language); } finally { first.leave(); } }
    }
}
