// SPDX-FileCopyrightText: 2026 Edward Kmett
// SPDX-License-Identifier: UPL-1.0 AND BSD-3-Clause
package thc.runtime;

import com.oracle.truffle.api.RootCallTarget;
import com.oracle.truffle.api.TruffleLanguage;
import com.oracle.truffle.api.bytecode.BytecodeConfig;
import com.oracle.truffle.api.bytecode.ContinuationResult;
import com.oracle.truffle.api.frame.VirtualFrame;
import org.graalvm.polyglot.Context;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.*;
import org.junit.jupiter.api.io.TempDir;
import thc.*;
import java.io.File;
import java.net.URI;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;
import static thc.runtime.ScalarTestCalls.callScalarTestTarget;
import static thc.runtime.OriginalStdioChecks.*;

/** Genuine installed GHC and Unix declarations, with native-compiled consumers. */
@EnabledOnOs(OS.LINUX)
@EnabledIfSystemProperty(named="os.arch",matches="amd64|x86_64")
@SuppressWarnings("unchecked")
class OriginalUnlinkAtTest {
    @TempDir Path directory;
    private final File root=new File(System.getProperty("thc.projectRoot"));
    private final String prefix="build/original-unlinkat";
    private Map<String,Object> json(String path) throws Exception { return (Map<String,Object>)Json.parse(Files.readString(new File(root,path).toPath())); }
    private Map<String,Object> source(String stage) throws Exception { return json(prefix+"/"+stage+".json"); }
    private Object copy(Object value) { return Json.parse(Json.stringify(value)); }
    private ManagedAddress cstring(String value) { var bytes=value.getBytes(StandardCharsets.UTF_8); return ManagedAddress.fromByteArray(Arrays.copyOf(bytes,bytes.length+1)); }
    private ExecutableProgram program(Language language,String backend,Map<String,Object> module) { return backend.equals("ast")?new Program(language,module):new BytecodeProgram(language,module); }
    private Context context() { return NativeFileProvider.createContext(Set.of(),ContextProfile.SYNCHRONOUS_TEST); }
    private void valid(RootCallTarget target) throws Exception { assertEquals(true,target.getClass().getMethod("isValidLastTier").invoke(target)); }
    private void released(Language language) { var handoff=language.getHandoffState().get(); assertEquals(0,handoff.getArguments().getDepth()); assertEquals(0,handoff.getResults().getDepth()); assertEquals(0,handoff.getArguments().retainedReferences()); assertEquals(0,handoff.getResults().retainedReferences()); }
    private OriginalStdioOp validate(List<Object> call) { var reps=new ArrayList<Object>(); for(var arg:(List<List<Object>>)call.get(2)) { var metadata=CoreRepresentations.metadata(arg); reps.add(metadata==null?null:metadata.get("rep")); } return CoreOriginalStdio.validate(call.get(6),reps,(List<?>)call.get(3),((Map<?,?>)call.get(6)).get("rep")); }
    private List<Object> original() throws Exception { return original("post"); }
    private List<Object> original(String stage) throws Exception { return single(foreignCalls(CoreModules.reachable(source(stage),"pathUnlinkAt")),ignored->true); }
    private Map<String,Object> raw() throws Exception { return raw(original()); }
    private Map<String,Object> raw(List<Object> call) throws Exception { return rawModule(call,source("post")); }
    private Path rawPath(Path scratch,byte[] bytes) { var suffix=new StringBuilder(); for(byte value:bytes) suffix.append(String.format(Locale.ROOT,"%%%02X",value&255)); return Path.of(URI.create(scratch.toUri().toASCIIString()+suffix)); }
    private long readOnly() throws Exception { return StdioHostAbi.load().flagConstant(OriginalStdioOp.O_RDONLY); }
    private long open(Path path) throws Exception { long fd=Language.currentState().getStdio().open(cstring(path.toString()),readOnly(),0); assertTrue(fd>=3); return fd; }
    private final List<String> remainingKeys=List.of("file","other","regular","link","dangling","empty","nonempty","child","sub","raw");
    private Path setup() throws Exception { var scratch=Files.createTempDirectory(directory,"native-"); for(var name:List.of("file","other","regular")) Files.writeString(scratch.resolve(name),"unchanged"); Files.createSymbolicLink(scratch.resolve("link"),Path.of("file")); Files.createSymbolicLink(scratch.resolve("dangling"),Path.of("missing-target")); for(var name:List.of("empty","nonempty","sub")) Files.createDirectory(scratch.resolve(name)); Files.writeString(scratch.resolve("nonempty/child"),"unchanged"); Files.writeString(rawPath(scratch,new byte[]{-1,110}),"unchanged"); return scratch; }
    private Path objectPath(Path scratch,String key) { return switch(key) { case "child" -> scratch.resolve("nonempty/child"); case "raw" -> rawPath(scratch,new byte[]{-1,110}); default -> scratch.resolve(key); }; }
    private ManagedAddress rowAddress(Path scratch,Map<String,Object> row) { var values=(List<Long>)row.get("path"); byte[] bytes=new byte[values.size()]; for(int i=0;i<bytes.length;i++) bytes[i]=values.get(i).byteValue(); byte[] anchor=bytes.length==0?new byte[0]:Objects.equals(row.get("absolute"),true)?(scratch+"/").getBytes(StandardCharsets.UTF_8):Objects.equals(row.get("fdMode"),"cwd")?(Path.of(Language.currentState().getEnv().getCurrentWorkingDirectory().getPath()).relativize(scratch)+"/").getBytes(StandardCharsets.UTF_8):new byte[0]; byte[] result=Arrays.copyOf(anchor,anchor.length+bytes.length+1); System.arraycopy(bytes,0,result,anchor.length,bytes.length); return ManagedAddress.fromByteArray(result); }
    @Test void originalNativeUnlinkAtMatchesBothBackendsAndEveryFirstInstalledCall() throws Exception {
        var manifest=json(prefix+"/manifest.json"); assertEquals(List.of("pathUnlinkAt"),manifest.get("entries")); hashes(root,manifest.get("inputHashes"),Set.of("t/fixtures/compiler/OriginalUnlinkAtAudit.hs","t/haskell-fixtures/OriginalUnlinkAtFixtures.hs","src/main/c/stdio-abi-probe.c","bin/core_original_foreign.py","bin/core-capabilities.json")); var artifacts=new HashSet<>(Set.of(prefix+"/oracle.json")); for(var stage:List.of("pre","post")) { artifacts.add(prefix+"/"+stage+".json"); artifacts.add(prefix+"/"+stage+"-pathUnlinkAt.audit.json"); } hashes(root,manifest.get("artifactHashes"),artifacts,prefix+"/"); var oracle=json(prefix+"/oracle.json"); var at=(Map<?,?>)oracle.get("at"); var abi=StdioHostAbi.load(); assertEquals(at.get("AT_FDCWD"),abi.getAtFdcwd()); assertEquals(at.get("AT_REMOVEDIR"),abi.getAtRemoveDir()); var rows=(List<Map<String,Object>>)oracle.get("rows"); assertEquals(34,rows.size()); var names=new HashSet<Object>(); var modes=new HashSet<Object>(); boolean absoluteInvalid=false,removeDir=false,wideFlags=false,wideFd=false; for(var row:rows) { names.add(row.get("name")); modes.add(row.get("fdMode")); absoluteInvalid|=Objects.equals(row.get("absolute"),true)&&Objects.equals(row.get("fdMode"),"invalid"); removeDir|=Objects.equals(row.get("flags"),abi.getAtRemoveDir()); wideFlags|=Objects.equals(row.get("flags"),0x1_0000_0000L); wideFd|=Objects.equals(row.get("fdOffset"),0x1_0000_0000L); } assertEquals(34,names.size()); assertEquals(Set.of("cwd","directory","duplicate","closed","regular","invalid"),modes); assertTrue(absoluteInvalid); assertTrue(removeDir); assertTrue(wideFlags); assertTrue(wideFd);
        for(var stage:List.of("pre","post")) { var audit=json(prefix+"/"+stage+"-pathUnlinkAt.audit.json"); assertEquals(true,audit.get("accepted")); assertEquals(List.of(),audit.get("issues")); assertEquals(List.of(),audit.get("missingGlobals")); var linked=with(CoreModules.reachable(source(stage),"pathUnlinkAt"),"instrument",true); var evidence=new ArrayCoreEvidence(linked,"pathUnlinkAt"); assertEquals(1,evidence.getBindings().size()); assertEquals(1,evidence.guestLambdas(evidence.getRoot().get("expr")).size()); assertEquals(1,evidence.loweredGuestLambdas(evidence.getRoot().get("expr")).size()); assertEquals(OriginalStdioOp.UNLINKAT,validate(original(stage)));
            for(var backend:List.of("ast","bytecode")) try(var context=context()) { context.initialize("thc"); context.enter(); try { var language=TruffleLanguage.LanguageReference.create(Language.class).get(null); var executable=program(language,backend,linked); var entry=executable.entryTarget("pathUnlinkAt"); var stdio=Language.currentState().getStdio(); class Exercise { void run(boolean compiled) throws Exception { for(var row:rows) { var scratch=setup(); Long owned=null; long fd; switch((String)row.get("fdMode")) { case "cwd" -> fd=abi.getAtFdcwd(); case "invalid" -> fd=-1; case "directory" -> { fd=open(scratch); owned=fd; } case "regular" -> { fd=open(scratch.resolve("regular")); owned=fd; } case "closed" -> { fd=open(scratch); assertEquals(0L,stdio.close(fd)); } case "duplicate" -> { long first=open(scratch); fd=stdio.duplicate(first); assertTrue(fd>=3); owned=fd; assertEquals(0L,stdio.close(first)); } default -> throw new IllegalStateException("Unknown native descriptor setup"); }
                try { assertEquals(-1L,stdio.close(-1)); long before=((Number)executable.diagnostics().get("compiledEntries")).longValue(); if(compiled) valid(entry); assertEquals(row.get("status"),Calls.target(entry,new Object[]{0L,fd+(Long)row.get("fdOffset"),rowAddress(scratch,row),row.get("flags")}),stage+"/"+backend+"/"+row.get("name")); assertEquals(row.get("errno"),stdio.errno(),Objects.toString(row.get("name"))); if(compiled) { assertEquals(before+1,((Number)executable.diagnostics().get("compiledEntries")).longValue()); valid(entry); } var remaining=new ArrayList<String>(); for(var key:remainingKeys) if(Files.exists(objectPath(scratch,key),LinkOption.NOFOLLOW_LINKS)) remaining.add(key); assertEquals(row.get("remaining"),remaining,Objects.toString(row.get("name"))); for(var key:remaining) if(Set.of("file","other","regular","child","raw").contains(key)) assertEquals("unchanged",Files.readString(objectPath(scratch,key))); if(remaining.contains("link")) assertEquals(Path.of("file"),Files.readSymbolicLink(scratch.resolve("link"))); if(remaining.contains("dangling")) assertEquals(Path.of("missing-target"),Files.readSymbolicLink(scratch.resolve("dangling"))); released(language); } finally { if(owned!=null) assertEquals(0L,stdio.close(owned)); }
            } } } var exercise=new Exercise(); exercise.run(false); entry.getClass().getMethod("compile",boolean.class).invoke(entry,true); valid(entry); exercise.run(true); assertEquals(0L,((Number)executable.diagnostics().get("unsupportedTraps")).longValue()); } finally { context.leave(); } }
        }
    }
    @Test void exactDirectoryOwnerSafeAbiAndStoredProofsRemainRequired() throws Exception {
        var call=original(); assertEquals(OriginalStdioOp.UNLINKAT,validate(call)); var owner=((Map<?,?>)((Map<?,?>)((Map<?,?>)call.get(6)).get("foreignCall")).get("target")).get("unit"); assertEquals(json(prefix+"/manifest.json").get("directoryUnit"),owner); for(var edit:List.of(list("safety","unsafe"),list("safety","interruptible"),list("convention","capi"),list("arity",3L),list("suppliedArity",3L))) { var bad=(List<Object>)copy(call); ((Map<String,Object>)((Map<?,?>)bad.get(6)).get("foreignCall")).put((String)edit.get(0),edit.get(1)); assertThrows(RuntimeFault.class,()->validate(bad)); } for(var unit:List.of("main","ghc-internal","unix-2.8.8.0-inplace","directory-1.3.9.0-inplace","directory-1.3.10.0-","directory-1.3.10.0-ABCD","directory-1.3.10.0-02fc:forged")) { var bad=(List<Object>)copy(call); ((Map<String,Object>)((Map<?,?>)((Map<?,?>)bad.get(6)).get("foreignCall")).get("target")).put("unit",unit); assertThrows(RuntimeFault.class,()->validate(bad)); }
        for(var backend:List.of("ast","bytecode")) try(var context=context()) { context.initialize("thc"); context.enter(); try { var language=TruffleLanguage.LanguageReference.create(Language.class).get(null); for(int i=0;i<=3;i++) { int index=i; assertThrows(RuntimeFault.class,()->program(language,backend,rawModule(call,source("post"),index))); } var shadowed=raw(call); var body=single((List<Map<String,Object>>)shadowed.get("bindings"),ignored->true).get("expr"); var copied=single(foreignCalls(body),ignored->true); copied.set(1,list("var","p0",((List<?>)copied.get(1)).get(2))); assertThrows(RuntimeFault.class,()->program(language,backend,shadowed)); for(int index:new int[]{0,2}) for(var rep:List.of("IntRep","Word32Rep","Word64Rep")) { var bad=(List<Object>)copy(call); var descriptor=(Map<String,Object>)((Map<?,?>)bad.get(6)).get("foreignCall"); ((List<Map<String,Object>>)descriptor.get("argumentReps")).get(index).put("primReps",list(rep)); assertThrows(RuntimeFault.class,()->program(language,backend,raw(bad))); } } finally { context.leave(); } }
    }
    @Test void stateCanonicalIntegersAndPathOwnershipPrecedeDestructiveEffects() throws Exception {
        for(var backend:List.of("ast","bytecode")) try(var context=context()) { context.initialize("thc"); context.enter(); try { var language=TruffleLanguage.LanguageReference.create(Language.class).get(null); var entry=program(language,backend,raw()).entryTarget("entry"); var stdio=Language.currentState().getStdio(); var file=Files.createTempFile(directory,"preserved-",".txt"); var address=cstring(file.toString()); int fd=(int)StdioHostAbi.load().getAtFdcwd(); class Invoke { Object call(ManagedAddress address,Object fd,Object flags,Object state) { return callScalarTestTarget(entry,new Object[]{0L,fd,address,flags,state}); } Object call(ManagedAddress address) { return call(address,fd,0,thc.runtime.Unit.INSTANCE); } } var invoke=new Invoke(); assertThrows(RuntimeFault.class,()->Calls.target(entry,new Object[]{0L,fd,address,0,9L})); assertEquals(-1L,stdio.close(-1)); long prior=stdio.errno(); assertThrows(RuntimeFault.class,()->invoke.call(address,fd,0,9L)); for(long number:new long[]{(long)Integer.MIN_VALUE-1,(long)Integer.MAX_VALUE+1,0x1_0000_0000L}) { assertThrows(RuntimeFault.class,()->invoke.call(address,number,0,thc.runtime.Unit.INSTANCE)); assertThrows(RuntimeFault.class,()->invoke.call(address,fd,number,thc.runtime.Unit.INSTANCE)); } assertThrows(RuntimeFault.class,()->invoke.call(ManagedAddress.nullAddress())); assertThrows(RuntimeFault.class,()->invoke.call(ManagedAddress.fromByteArray(new byte[]{65}))); var allocation=ManagedAllocation.mutable(16,8); allocation.writeAddressByteOffset(0,ManagedAddress.nullAddress()); assertThrows(RuntimeFault.class,()->invoke.call(ManagedAddress.fromAllocation(allocation))); assertTrue(Files.exists(file)); assertEquals(prior,stdio.errno()); released(language); } finally { context.leave(); } }
        for(var backend:List.of("ast","bytecode")) try(var context=Context.newBuilder("thc").build()) { context.initialize("thc"); context.enter(); try { var language=TruffleLanguage.LanguageReference.create(Language.class).get(null); var file=Files.createTempFile(directory,"denied-",".txt"); var entry=program(language,backend,raw()).entryTarget("entry"); assertEquals(-1,callScalarTestTarget(entry,new Object[]{0L,-999,cstring(file.toString()),0,thc.runtime.Unit.INSTANCE})); assertEquals(StdioHostAbi.load().error(7),Language.currentState().getStdio().errno()); assertTrue(Files.exists(file)); } finally { context.leave(); } }
    }
    @Test void directoryDuplicatesAndNativePathAliasesRetainOwnershipAndLifetime() throws Exception {
        for(var backend:List.of("ast","bytecode")) try(var first=context()) { first.initialize("thc"); first.enter(); try { var language=TruffleLanguage.LanguageReference.create(Language.class).get(null); var scratch=Files.createTempDirectory(directory,"lease-"); var file=Files.writeString(scratch.resolve("target"),"original"); var state=Language.currentState(); long fd=open(scratch); long duplicate=state.getStdio().duplicate(fd); assertTrue(duplicate>=3); assertNotEquals(fd,duplicate); assertEquals(0L,state.getStdio().close(fd)); var entry=program(language,backend,raw()).entryTarget("entry"); byte[] bytes={116,97,114,103,101,116,0}; var base=state.getNativeAllocations().malloc(bytes.length+8L); var alias=base.plus(8); try { ManagedAddress.fromByteArray(bytes).copyNonOverlappingTo(alias,bytes.length); try(var second=context()) { second.initialize("thc"); second.enter(); try { var other=TruffleLanguage.LanguageReference.create(Language.class).get(null); var foreign=program(other,backend,raw()).entryTarget("entry"); assertThrows(RuntimeFault.class,()->callScalarTestTarget(foreign,new Object[]{0L,(int)duplicate,alias,0,thc.runtime.Unit.INSTANCE})); assertEquals(-1,callScalarTestTarget(foreign,new Object[]{0L,(int)duplicate,cstring("target"),0,thc.runtime.Unit.INSTANCE})); assertEquals(StdioHostAbi.load().error(4),Language.currentState().getStdio().errno()); released(other); } finally { second.leave(); } } assertEquals(-1,callScalarTestTarget(entry,new Object[]{0L,(int)fd,alias,0,thc.runtime.Unit.INSTANCE})); assertTrue(Files.exists(file)); long prior=state.getStdio().errno(); assertEquals(0,callScalarTestTarget(entry,new Object[]{0L,(int)duplicate,alias,0,thc.runtime.Unit.INSTANCE})); assertFalse(Files.exists(file)); assertEquals(prior,state.getStdio().errno()); assertEquals(0L,state.getStdio().close(duplicate)); Files.writeString(file,"replacement"); assertEquals(-1,callScalarTestTarget(entry,new Object[]{0L,(int)duplicate,alias,0,thc.runtime.Unit.INSTANCE})); assertTrue(Files.exists(file)); } finally { state.getNativeAllocations().free(base); } assertThrows(RuntimeFault.class,()->callScalarTestTarget(entry,new Object[]{0L,(int)duplicate,alias,0,thc.runtime.Unit.INSTANCE})); released(language); } finally { first.leave(); } }
    }
    @Test void completedSafeEffectsResumeAfterTheSavedResultWithoutReplay() throws Exception {
        try(var context=context()) { context.initialize("thc"); context.enter(); try { var language=TruffleLanguage.LanguageReference.create(Language.class).get(null); var state=Language.currentState(); var identity=state.getThreads().enterCurrent(); try { var file=Files.createTempFile(directory,"completed-",".txt"); var proof=CoreRepresentations.parse(((Map<?,?>)original().get(6)).get("rep")); var layout=new FrameLayout(); int[] slots={layout.bind("completed CInt")}; var shape=new TupleShape(proof,language); class Enqueue extends Expr { AsyncRequest pending; int evaluated; @Override public Object execute(VirtualFrame frame) { evaluated++; pending=state.getThreads().send(identity,"after unlinkat"); return thc.runtime.Unit.INSTANCE; } } var enqueue=new Enqueue(); java.util.function.Function<Object,Expr> value=v->new Expr() { @Override public Object execute(VirtualFrame frame) { return v; } }; var body=new OriginalStdioExpression(OriginalStdioOp.UNLINKAT,new Expr[]{value.apply((int)StdioHostAbi.load().getAtFdcwd()),value.apply(cstring(file.toString())),value.apply(0),enqueue},proof);
            var ast=new FunctionRoot(language,layout.build(),"unlinkat completion",null,new int[0],new int[0],new int[0],body,new Metrics(false),new CoreRepresentation[0],body.getRepresentation(),body.getCoreSourceLocation(),new boolean[0],null,shape,slots,null,true,new int[0][],false,FunctionRootRole.FUNCTION,false); var saved=Objects.requireNonNull(SavedGuestContinuations.savedGuestContinuation(Calls.target(ast.getCallTarget(),new Object[]{0L}))); assertSame(enqueue.pending,saved.asyncRequest()); assertFalse(Files.exists(file)); enqueue.pending.acknowledge(); Files.writeString(file,"replacement"); var completed=saved.continueWith(thc.runtime.Unit.INSTANCE); assertEquals(0,shape.getLayout().getInt(TupleResults.ownedTupleResult(completed,shape),0)); assertEquals("replacement",Files.readString(file)); assertEquals(1,enqueue.evaluated); released(language);
            // The bytecode operation writes its destination before any yield.
            var request=state.getThreads().send(identity,"after bytecode unlinkat"); long atFdcwd=StdioHostAbi.load().getAtFdcwd(); var target=BytecodeRootGen.create(language,BytecodeConfig.DEFAULT,b->{ b.beginRoot(); var result=b.createLocal("completed CInt","primitive"); var token=b.createLocal("pending request","object"); b.beginOriginalUnlinkAt(result); b.emitLoadConstant(atFdcwd); b.emitLoadConstant(cstring(file.toString())); b.emitLoadConstant(0L); b.emitLoadConstant(thc.runtime.Unit.INSTANCE); b.endOriginalUnlinkAt(); b.beginIfThen(); b.emitPollAsync(token); b.beginYield(); b.emitLoadLocal(token); b.endYield(); b.endIfThen(); b.beginReturn(); b.emitLoadLocal(result); b.endReturn(); b.endRoot(); }).getNode(0).getCallTarget(); var suspended=(ContinuationResult)Calls.target(target,new Object[]{0L}); assertSame(request,suspended.getResult()); assertFalse(Files.exists(file)); request.acknowledge(); Files.writeString(file,"second replacement"); assertEquals(0,suspended.continueWith(thc.runtime.Unit.INSTANCE)); assertEquals("second replacement",Files.readString(file));
            // Inspect the actual original-call lowering as well as the instruction.
            var lowered=(BytecodeRoot)new BytecodeProgram(language,raw(),true).entryTarget("entry").getRootNode(); var names=new ArrayList<String>(); for(var instruction:lowered.getBytecodeNode().getInstructions()) names.add(instruction.getName()); int effect=-1; for(int i=0;i<names.size();i++) if(names.get(i).toLowerCase(Locale.ROOT).contains("originalunlinkat")) { effect=i; break; } assertTrue(effect>=0,names.toString()); boolean poll=false; for(int i=effect+1;i<names.size();i++) poll|=names.get(i).toLowerCase(Locale.ROOT).contains("pollasync"); assertTrue(poll,names.toString()); released(language);
        } finally { state.getThreads().leaveCurrent(); } } finally { context.leave(); } }
    }
}
