cabal-version: 3.0
-- SPDX-FileCopyrightText: 2026 Edward Kmett
-- SPDX-License-Identifier: UPL-1.0 AND BSD-3-Clause

name: run-file-lifecycle
version: 0.1.0.0
build-type: Simple
license: UPL-1.0 AND BSD-3-Clause

executable lifecycle
  main-is: Main.hs
  hs-source-dirs: app
  build-depends: base >= 4.22 && < 4.23
  default-language: Haskell2010
  ghc-options: -O2
