#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Edward Kmett
# SPDX-License-Identifier: UPL-1.0 AND BSD-3-Clause

"""Generate concrete SIMD nodes from a small, pinned semantic/layout table.

Gradle writes build/generated/simd. --write updates the two explicitly marked
bytecode regions; --check verifies them. --verify-ghc checks machine contracts
against primOpSig/typePrimRep_maybe, without parsing printed Haskell types.
"""
import argparse
import json
import os
from pathlib import Path
import subprocess

ROOT = Path(__file__).resolve().parent.parent
SPEC = ROOT / 'scripts/simd-families.json'
# primitive scalar type, bit width, Java Vector type, Kotlin scalar accessor
LANES = {
    'Int8Rep': ('byte', 8, 'ByteVector', 'Long'),
    'Word8Rep': ('byte', 8, 'ByteVector', 'Long'),
    'Int16Rep': ('short', 16, 'ShortVector', 'Long'),
    'Word16Rep': ('short', 16, 'ShortVector', 'Long'),
    'Int32Rep': ('int', 32, 'IntVector', 'Long'),
    'Word32Rep': ('int', 32, 'IntVector', 'Long'),
    'Word64Rep': ('long', 64, 'LongVector', 'Long'),
    'Int64Rep': ('long', 64, 'LongVector', 'Long'),
    'FloatRep': ('float', 32, 'FloatVector', 'Float'),
    'DoubleRep': ('double', 64, 'DoubleVector', 'Double'),
}
UNSIGNED_MASK = {'Word8Rep': '0xffL', 'Word16Rep': '0xffffL', 'Word32Rep': '0xffff_ffffL'}
BINARY = {'plus': 'add', 'minus': 'subtract', 'times': 'multiply', 'divide': 'divide', 'min': 'min', 'max': 'max', 'quot': 'quot', 'rem': 'rem'}
VECTOR_METHOD = {'add': 'add', 'subtract': 'sub', 'multiply': 'mul', 'divide': 'div', 'min': 'min', 'max': 'max'}
LEGACY_INSERT = {'Int8X16', 'Word8X16', 'Int16X8', 'Word16X8', 'Int32X4', 'Word32X4', 'Int64X2', 'FloatX4', 'DoubleX2'}
OPS = {'pack', 'unpack', 'broadcast', 'negate', 'insert', 'shuffle'} | BINARY.keys()
HEADER = ('// SPDX-FileCopyrightText: 2026 Edward Kmett\n'
          '// SPDX-License-Identifier: UPL-1.0 AND BSD-3-Clause\n\n'
          '// Generated by scripts/generate-simd-families.py; edit the family table/generator.\n')
HASKELL_HEADER = ('-- SPDX-FileCopyrightText: 2026 Edward Kmett',
                  '-- SPDX-License-Identifier: UPL-1.0 AND BSD-3-Clause', '')
QUERY = r'''let reps t = fmap (map show) (GHC.Types.RepType.typePrimRep_maybe t); tuple t = case GHC.Core.Type.splitTyConApp_maybe t of { Just (tc,_) -> GHC.Core.TyCon.isUnboxedTupleTyCon tc; _ -> False }; emit op = let (_,args,res,arity,_) = GHC.Builtin.PrimOps.primOpSig op; name = GHC.Types.Name.Occurrence.occNameString (GHC.Builtin.PrimOps.primOpOcc op) in if name `notElem` NAMES then pure () else case traverse reps (args++[res]) of { Nothing -> pure (); Just rs -> putStrLn (GHC.Types.Name.Occurrence.occNameString (GHC.Builtin.PrimOps.primOpOcc op) ++ "\t" ++ show arity ++ "\t" ++ show rs ++ "\t" ++ show (map tuple (args++[res]))) } in mapM_ emit GHC.Builtin.PrimOps.allThePrimOps'''


def families():
    data = json.loads(SPEC.read_text())
    if data['schema'] != 1 or data['ghc'] != '9.14.1':
        raise ValueError('Expected pinned SIMD family schema')
    names = set()
    for f in data['families']:
        if f['laneRep'] not in LANES or type(f['lanes']) is not int or f['lanes'] <= 0:
            raise ValueError('Unsupported lane contract')
        scalar, width, _, _ = LANES[f['laneRep']]
        stem = f['laneRep'].removesuffix('Rep')
        if f['element'] != stem + 'ElemRep' or f['name'] != f'{stem}X{f["lanes"]}' or f['bits'] != width * f['lanes'] or f['bits'] not in (128, 256, 512):
            raise ValueError('Contradictory vector identity/layout')
        if (f['name'] in names or not f['operations'] or len(set(f['operations'])) != len(f['operations'])
                or not set(f['operations']) <= OPS or type(f['newCarrier']) is not bool
                or type(f.get('composite', False)) is not bool):
            raise ValueError('Malformed SIMD operation family')
        if f.get('composite') and (not f['newCarrier'] or not {'pack', 'unpack'} <= set(f['operations'])):
            raise ValueError('Composite fixture needs a generated foundation family and pack/unpack')
        if 'divide' in f['operations'] and scalar not in ('float', 'double'):
            raise ValueError('Integer vector division is a separate semantic family')
        if {'quot', 'rem'} & set(f['operations']) and scalar in ('float', 'double'):
            raise ValueError('Quotient/remainder require integer lanes')
        if 'negate' in f['operations'] and f['laneRep'].startswith('Word'):
            raise ValueError('No unsigned vector negation primop')
        if 'insert' in f['operations'] and not f['newCarrier'] and f['name'] not in LEGACY_INSERT:
            raise ValueError('Insert requires a known exact vector family')
        names.add(f['name'])
    return data['families']


def contracts(fs):
    result = {}
    for f in fs:
        vector = [f'VecRep {f["lanes"]} {f["element"]}']
        lane = [f['laneRep']]
        packed = lane * f['lanes']
        for op in f['operations']:
            args = [packed] if op == 'pack' else [lane] if op == 'broadcast' else [vector, lane, ['IntRep']] if op == 'insert' else [vector, vector, ['IntRep'] * f['lanes']] if op == 'shuffle' else [vector] * (2 if op in BINARY else 1)
            result[op + f['name'] + '#'] = {'arity':len(args), 'reps': args + [packed if op == 'unpack' else vector], 'tuples': ([False, False, True] if op == 'shuffle' else [op == 'pack'] * len(args)) + [op == 'unpack']}
    return result


def verify_ghc(fs):
    ghc = os.environ.get('GHC', 'ghc')
    if subprocess.check_output([ghc, '--numeric-version'], text=True).strip() != '9.14.1':
        raise ValueError('GHC 9.14.1 required')
    rows = subprocess.check_output([ghc, '-ignore-dot-ghci', '-package', 'ghc', '-e', QUERY.replace('NAMES', json.dumps(list(contracts(fs))))], text=True)
    actual = {}
    for line in rows.splitlines():
        name, arity, reps, tuples = line.split('\t')
        actual[name] = {'arity': int(arity), 'reps': json.loads(reps), 'tuples':json.loads(tuples.replace('True','true').replace('False','false'))}
    expected = contracts(fs)
    for name, proof in expected.items():
        if actual.get(name) != proof:
            raise ValueError(f'GHC machine contract disagrees for {name}: {actual.get(name)} != {proof}')
    print(f'Verified {len(expected)} exact SIMD contracts with pinned GHC APIs')


def vector_type(f):
    return LANES[f['laneRep']][2]


def species(f):
    return f'{vector_type(f)}.SPECIES_{f["bits"]}'


def packed(f, values):
    return f'{vector_type(f)}.broadcast({species(f)}, {values[0]})' + ''.join(f'.withLane({i}, {value})' for i, value in enumerate(values[1:], 1))


def checked(f, value):
    return f'CoreVectors.require{vector_type(f).removesuffix("Vector")}({value}, {species(f)})'


def operation_expression(f, op, args):
    if op == 'broadcast': return f'{vector_type(f)}.broadcast({species(f)}, {args[0]})'
    if op == 'insert':
        return f'{args[0]}.withLane(CoreVectors.laneIndex({args[2]}, {f["lanes"]}), {args[1]})'
    if op in ('quot', 'rem'):
        return f'VectorIntegerDivision.{op}{vector_type(f).removesuffix("Vector")}({args[0]}, {args[1]}, {str(f["laneRep"].startswith("Word")).lower()})'
    if op == 'negate': return f'{args[0]}.neg()'
    if f['laneRep'].startswith('Word') and op in ('min', 'max'):
        return f'{args[0]}.lanewise(VectorOperators.U{op.upper()}, {args[1]})'
    return f'{args[0]}.{VECTOR_METHOD[BINARY[op]]}({args[1]})'



def proof_code(fs):
    lines = [HEADER, 'package thc.runtime\n', 'internal object GeneratedVectors {',
             '    private val index = CoreRepresentation(CoreKind.LONG, true, true, listOf("IntRep"))']
    for f in fs:
        n=f['name']; kind=LANES[f['laneRep']][3].upper();count=f['lanes'];rep=f['laneRep']
        lines += [f'    val vector{n} = CoreVector({count}, "{f["element"]}")',
                  f'    val proof{n} = CoreRepresentation(CoreKind.VECTOR, true, true, listOf("VecRep {count} {f["element"]}"), vector = vector{n})',
                  f'    private val lane{n} = CoreRepresentation(CoreKind.{kind}, true, true, listOf("{rep}"))',
                  f'    val unpacked{n} = CoreRepresentation(CoreKind.UNKNOWN, true, true, List({count}) {{ "{rep}" }}, List({count}) {{ lane{n} }})',
                  f'    private val indices{n} = CoreRepresentation(CoreKind.UNKNOWN, true, true, List({count}) {{ "IntRep" }}, List({count}) {{ index }})']
    allops=list(contracts(fs))
    lines += ['    val operations = setOf('+', '.join('"'+name+'"' for name in allops)+')',
              '    fun supports(vector: CoreVector): Boolean = '+ ' || '.join(f'vector == vector{f["name"]}' for f in fs if f['newCarrier']),
              '    fun validate(name: String, arguments: List<CoreRepresentation>, result: CoreRepresentation) {',
              '        val contract = when (name) {']
    for f in fs:
        n=f['name']
        for op in f['operations']:
            args=f'unpacked{n}' if op=='pack' else f'lane{n}' if op=='broadcast' else f'proof{n}, lane{n}, index' if op=='insert' else f'proof{n}, proof{n}, indices{n}' if op=='shuffle' else ', '.join([f'proof{n}']*(2 if op in BINARY else 1))
            result=f'unpacked{n}' if op=='unpack' else f'proof{n}'
            lines.append(f'            "{op}{n}#" -> Pair(listOf({args}), {result})')
    lines += ['            else -> throw UnsupportedCore("Unsupported generated vector primitive $name")','        }',
              '        CoreVectors.validateSignature(name, arguments, result, contract.first, contract.second)', '    }',
              '    fun expression(name: String, arguments: Array<Expr>, shuffleIndices: IntArray? = null, allocate: (Int) -> IntArray): Expr = when (name) {']
    for f in fs:
        n=f['name']
        for op in f['operations']:
            expr=f'Generated{n}Pack(arguments[0], allocate({f["lanes"]}))' if op=='pack' else f'Generated{n}Unpack(arguments[0])' if op=='unpack' else f'Generated{n}Shuffle(arguments[0], arguments[1], shuffleIndices ?: fault("Missing shuffle indices"))' if op=='shuffle' else f'Generated{n}Operation(name, arguments)'
            lines.append(f'        "{op}{n}#" -> {expr}')
    lines += ['        else -> throw UnsupportedCore("Unsupported generated vector primitive $name")','    }','}']
    return '\n'.join(lines)+'\n'



def ast_code(fs):
    lines=[HEADER,'package thc.runtime\n','import jdk.incubator.vector.*','import com.oracle.truffle.api.CompilerDirectives.CompilationFinal','import com.oracle.truffle.api.frame.VirtualFrame\n']
    for f in fs:
        n=f['name'];count=f['lanes'];scalar,_,_,access=LANES[f['laneRep']]; cast=f'.to{scalar.capitalize()}()' if scalar in ('byte', 'short', 'int') else ''
        if 'pack' in f['operations']:
            lines += [f'internal class Generated{n}Pack(@field:Child private var argument: Expr,',
                      '    @field:CompilationFinal(dimensions = 1) private val slots: IntArray) : Expr() {',
                      f'    init {{ representation = GeneratedVectors.proof{n} }}',
                      f'    override fun execute(frame: VirtualFrame): {vector_type(f)} {{', '        argument.executeTuple(frame, slots)',
                      f'        return {packed(f, [f"frame.get{access}(slots[{i}]){cast}" for i in range(count)])}','    }','}']
        if 'unpack' in f['operations']:
            lines += [f'internal class Generated{n}Unpack(@field:Child private var argument: Expr) : Expr() {{',
                      f'    init {{ representation = GeneratedVectors.unpacked{n} }}',
                      '    override fun execute(frame: VirtualFrame): Nothing = fault("Vector unpack requires a tuple destination")',
                      '    override fun executeTuple(frame: VirtualFrame, slots: IntArray, offset: Int): Any? {',
                      f'        val value = {checked(f, "argument.execute(frame)")}']
            mask = UNSIGNED_MASK.get(f['laneRep'])
            for i in range(count):
                lane = (f'value.lane({i}).toLong() and {mask}' if mask
                        else f'value.lane({i}).toLong()' if cast else f'value.lane({i})')
                lines.append(f'        FrameAccess.write{access}(frame, slots[offset + {i}], {lane})')
            lines += ['        return null','    }','}']
        if 'shuffle' in f['operations']:
            lines += [f'internal class Generated{n}Shuffle(@field:Child private var left: Expr,',
                      '    @field:Child private var right: Expr, indices: IntArray) : Expr() {',
                      f'    @field:CompilationFinal private val shuffle = VectorShuffle.fromArray({species(f)}, indices, 0)',
                      f'    init {{ representation = GeneratedVectors.proof{n} }}',
                      f'    override fun execute(frame: VirtualFrame): {vector_type(f)} {{',
                      f'        val a = {checked(f, "left.execute(frame)")}',
                      f'        val b = {checked(f, "right.execute(frame)")}',
                      '        return a.rearrange(shuffle, b)', '    }', '}']
        ops=[op for op in f['operations'] if op not in ('pack','unpack','shuffle')]
        lines += [f'internal class Generated{n}Operation(name: String, @field:Children private var arguments: Array<Expr>) : Expr() {{',
                  '    private val operation = when (name) {']
        lines += [f'        "{op}{n}#" -> {i}' for i,op in enumerate(ops)]
        lines += [f'        else -> throw RuntimeFault("Invalid {n} operation")','    }',
                  f'    init {{ representation = GeneratedVectors.proof{n} }}',
                  f'    override fun execute(frame: VirtualFrame): {vector_type(f)} = when (operation) {{']
        for i,op in enumerate(ops):
            operands = [f'arguments[0].executeRequired{access}(frame){cast}'] if op == 'broadcast' else ['vector(frame, 0)', f'arguments[1].executeRequired{access}(frame){cast}', 'arguments[2].executeRequiredLong(frame)'] if op == 'insert' else ['vector(frame, 0)'] if op == 'negate' else ['vector(frame, 0)', 'vector(frame, 1)']
            if op == 'insert':
                # Evaluate Core operands in source order before withLane's index-first API.
                lines += [f'        {i} -> {{', f'            val value = {operands[0]}',
                          f'            val lane = {operands[1]}', f'            val index = {operands[2]}',
                          f'            {operation_expression(f, op, ["value", "lane", "index"])}', '        }']
            else:
                lines.append(f'        {i} -> {operation_expression(f, op, operands)}')
        lines += [f'        else -> fault("Invalid {n} operation")','    }',
                  f'    private fun vector(frame: VirtualFrame, index: Int): {vector_type(f)} = {checked(f, "arguments[index].execute(frame)")}','}\n']
    return '\n'.join(lines)+'\n'


def bytecode_nodes(fs):
    lines=[]
    for f in fs:
        n=f['name'];count=f['lanes'];scalar,_,_,access=LANES[f['laneRep']];prim=access.lower(); cast=f'({scalar}) ' if scalar in ('byte', 'short', 'int') else ''
        for op in f['operations']:
            title=op.capitalize(); node=f'Generated{n}{title}'
            # Keep the DSL's shared instruction metadata below the JVM method limit.
            if op in ('pack', 'unpack') and count > 8:
                lines += ['    @Operation', '    @ConstantOperand(type = BytecodeVectorLanes.class, name = "lanes")',
                          f'    public static final class {node} {{',
                          f'        @Specialization public static {vector_type(f) if op == "pack" else "void"} apply(VirtualFrame frame, BytecodeVectorLanes lanes' +
                          (f', {vector_type(f)} raw' if op == 'unpack' else '') + ', @Bind("$node") Node node) {',
                          '            BytecodeNode bytecode = ((BytecodeRoot) node.getRootNode()).getBytecodeNode();']
                if op == 'pack':
                    lines += ['            try {',
                              '                return ' + packed(f, [f'{cast}lanes.getSlots()[{i}].get{access}(bytecode, frame)' for i in range(count)]) + ';',
                              '            } catch (com.oracle.truffle.api.nodes.UnexpectedResultException invalid) {',
                              '                throw new RuntimeFault("Expected primitive vector lane");',
                              '            }']
                else:
                    lines.append(f'            {vector_type(f)} value = {checked(f, "raw")};')
                    mask = UNSIGNED_MASK.get(f['laneRep'])
                    for i in range(count):
                        lane = f'value.lane({i})' + (f' & {mask}' if mask else '')
                        lines.append(f'            lanes.getSlots()[{i}].set{access}(bytecode, frame, {lane});')
                lines += ['        }', '    }']
            elif op=='shuffle':
                lines += ['    @Operation', '    @ConstantOperand(type = VectorShuffle.class, name = "shuffle")',
                          f'    public static final class {node} {{',
                          f'        @Specialization public static {vector_type(f)} apply(VectorShuffle<?> shuffle, {vector_type(f)} left, {vector_type(f)} right) {{',
                          f'            return {checked(f, "left")}.rearrange(shuffle.check({species(f)}), {checked(f, "right")});',
                          '        }', '    }']
            elif op=='unpack':
                lines += ['    @Operation']+[f'    @ConstantOperand(type = LocalAccessor.class, name = "lane{i}")' for i in range(count)]
                lines += [f'    public static final class {node} {{',
                          '        @Specialization public static void apply(VirtualFrame frame, '+', '.join(f'LocalAccessor lane{i}' for i in range(count))+f', {vector_type(f)} raw, @Bind("$node") Node node) {{',
                          '            BytecodeNode bytecode = ((BytecodeRoot) node.getRootNode()).getBytecodeNode();',
                          f'            {vector_type(f)} value = {checked(f, "raw")};']
                mask = UNSIGNED_MASK.get(f['laneRep'])
                lane = (lambda i: f'value.lane({i}) & {mask}' if mask
                        else f'value.lane({i})')
                lines += [f'            lane{i}.set{access}(bytecode, frame, {lane(i)});' for i in range(count)]
                lines += ['        }','    }']
            else:
                if op=='pack':
                    params=', '.join(f'{prim} lane{i}' for i in range(count)); expr=packed(f, [cast+f'lane{i}' for i in range(count)])
                elif op=='broadcast':params=f'{prim} value';expr=operation_expression(f, op, [cast+'value'])
                elif op=='negate':params=f'{vector_type(f)} value';expr=operation_expression(f, op, [checked(f, 'value')])
                elif op=='insert':params=f'{vector_type(f)} vector, {prim} value, long index';expr=operation_expression(f, op, [checked(f, 'vector'), cast+'value', 'index'])
                else:params=f'{vector_type(f)} left, {vector_type(f)} right';expr=operation_expression(f, op, [checked(f, 'left'), checked(f, 'right')])
                lines += [f'    @Operation public static final class {node} {{',f'        @Specialization public static {vector_type(f)} apply({params}) {{ return {expr}; }}','    }']
    return '\n'.join(lines)+'\n'


def bytecode_emitter(fs):
    lines=['    private fun generatedVectorPrimitive(name: String, operands: List<Expression>, shuffleIndices: IntArray?): Expression = when (name) {']
    for f in fs:
        n=f['name'];count=f['lanes']
        for op in f['operations']:
            node=f'Generated{n}{op.capitalize()}'
            if op=='shuffle':
                lines += [f'        "{op}{n}#" -> run {{',
                          f'            val shuffle = jdk.incubator.vector.VectorShuffle.fromArray(jdk.incubator.vector.{species(f)}, shuffleIndices ?: fault("Missing shuffle indices"), 0)',
                          '            ProvenExpression(Expression { e ->',
                          f'                e.builder.begin{node}(shuffle)',
                          '                operands[0].emit(e); operands[1].emit(e)',
                          f'                e.builder.end{node}()',
                          f'            }}, GeneratedVectors.proof{n})', '        }']
            elif op=='unpack':
                lines += [f'        "{op}{n}#" -> tupleExpression(GeneratedVectors.unpacked{n}) {{ e, destination ->',
                          f'            e.builder.begin{node}(' +
                          ('BytecodeVectorLanes(destination.map(LocalAccessor::constantOf).toTypedArray())' if count > 8 else ', '.join(f'destination[{i}]' for i in range(count))) + ')',
                          '            operands[0].emit(e)',f'            e.builder.end{node}()','        }']
            else:
                lines += [f'        "{op}{n}#" -> ProvenExpression(Expression {{ e ->','            val b = e.builder']
                if op=='pack':
                    emit = (f'            b.emit{node}(BytecodeVectorLanes(lanes.map(LocalAccessor::constantOf).toTypedArray()))' if count > 8 else
                            f'            b.begin{node}(); lanes.forEach(b::emitLoadLocal); b.end{node}()')
                    lines += ['            b.beginBlock()',f'            val lanes = List({count}) {{ b.createLocal() }}','            operands[0].emitTuple(e, lanes)',emit,'            b.endBlock()']
                else:
                    lines += [f'            b.begin{node}(); operands.forEach {{ it.emit(e) }}; b.end{node}()']
                lines += [f'        }}, GeneratedVectors.proof{n})']
    lines += ['        else -> throw UnsupportedCore("Unsupported generated vector primitive $name")','    }']
    return '\n'.join(lines)+'\n'


def fixture_sources(fs):
    """Real scalar-entry Haskell; vectors never cross a function boundary."""
    extrema = [op + f['name'] + '#' for f in fs for op in f['operations'] if op in ('min', 'max', 'shuffle')]
    source = [*HASKELL_HEADER, '{-# LANGUAGE MagicHash, UnboxedTuples #-}', 'module GeneratedSimdFamilies where',
              'import GHC.Exts', *(['import GHC.Prim (' + ', '.join(extrema) + ')'] if extrema else []), '',
              '-- NaN payload selection is not part of arithmetic primop semantics.',
              '-- All non-NaNs are observed as exact bits, including signed zero.',
              '{-# INLINE bitsFloat #-}', 'bitsFloat :: Float# -> Int#',
              'bitsFloat value = case neFloat# value value of',
              '  1# -> 2143289344#',
              '  _ -> word2Int# (word32ToWord# (castFloatToWord32# value))',
              '{-# INLINE bitsDouble #-}', 'bitsDouble :: Double# -> Int#',
              'bitsDouble value = case value /=## value of',
              '  1# -> 9221120237041090560#',
              '  _ -> word2Int# (word64ToWord# (castDoubleToWord64# value))', '']
    convert = {
        'Int8Rep': lambda x: f'intToInt8# ({x})',
        'Word8Rep': lambda x: f'wordToWord8# (int2Word# ({x}))',
        'Int16Rep': lambda x: f'intToInt16# ({x})',
        'Word16Rep': lambda x: f'wordToWord16# (int2Word# ({x}))',
        'Int32Rep': lambda x: f'intToInt32# ({x})',
        'Word32Rep': lambda x: f'wordToWord32# (int2Word# ({x}))',
        'Int64Rep': lambda x: f'intToInt64# ({x})',
        'Word64Rep': lambda x: f'wordToWord64# (int2Word# ({x}))',
        'FloatRep': lambda x: f'castWord32ToFloat# (wordToWord32# (int2Word# ({x})))',
        'DoubleRep': lambda x: f'castWord64ToDouble# (wordToWord64# (int2Word# ({x})))',
    }
    observe = {'Int8Rep': 'int8ToInt#', 'Int16Rep': 'int16ToInt#', 'Int32Rep': 'int32ToInt#', 'Int64Rep': 'int64ToInt#',
               'Word64Rep': 'word2Int# . word64ToWord#', 'FloatRep': 'bitsFloat', 'DoubleRep': 'bitsDouble'}
    names = []
    for family in fs:
        n = family['name']; count = family['lanes']; rep = family['laneRep']
        operations = [op for op in family['operations'] if op not in ('pack', 'unpack')]
        def observe_lane(i):
            return (f'word2Int# (word{rep[4:-3]}ToWord# p{i})' if rep.startswith('Word') else f'{observe[rep]} p{i}')
        def selected_lane(op, lane):
            if op == 'broadcast':
                vector = f'broadcast{n}# ({convert[rep]("a")})'
            else:
                left = f'pack{n}# (# ' + ', '.join(convert[rep](f'a +# {i * 104729}#') for i in range(count)) + ' #)'
                right = f'pack{n}# (# ' + ', '.join(convert[rep](f'b -# {i * 7919}#') for i in range(count)) + ' #)'
                vector = f'{op}{n}# ({left})' + (f' ({right})' if op in BINARY or op == 'shuffle' else '')
                if op == 'shuffle':
                    vector += ' (# ' + ', '.join(f'{(count - 1 - i) + (count if i % 2 else 0)}#' for i in range(count)) + ' #)'
                if op == 'insert':
                    vector += f' ({convert[rep]("b")}) {lane}#'
            value = observe_lane(lane)
            return f'case unpack{n}# ({vector}) of {{ (# '+', '.join(f'p{i}' for i in range(count))+f' #) -> {value} }}'
        if family.get('composite'):
            name = n[0].lower() + n[1:] + 'Composite'; worker = name + 'Worker'; names.append(name)
            source += [f'{{-# OPAQUE {worker} #-}}', f'{worker} :: Int# -> Int# -> Int# -> Int#',
                       f'{worker} selector a b = case selector of']
            for op_index, op in enumerate(operations):
                for lane in range(count):
                    source.append(f'  {op_index * count + lane}# -> {selected_lane(op, lane)}')
            source += ['  _ -> 0#', f'{name} :: Int# -> Int# -> Int# -> Int#',
                       f'{name} selector a b = case {worker} selector a b of value -> value +# 17#', '']
            continue
        for op in operations:
            name = op + n; worker = name + 'Worker'; names.append(name)
            source += [f'{{-# OPAQUE {worker} #-}}', f'{worker} :: Int# -> Int# -> Int# -> Int#',
                       f'{worker} lane a b =']
            if op == 'broadcast':
                vector = f'broadcast{n}# ({convert[rep]("a")})'
            else:
                left = f'pack{n}# (# ' + ', '.join(convert[rep](f'a +# {i * 104729}#') for i in range(count)) + ' #)'
                right = f'pack{n}# (# ' + ', '.join(convert[rep](f'b -# {i * 7919}#') for i in range(count)) + ' #)'
                vector = f'{op}{n}# ({left})' + (f' ({right})' if op in BINARY or op == 'shuffle' else '')
                if op == 'insert':
                    vector += f' ({convert[rep]("b")}) lane'
                if op == 'shuffle':
                    vector += ' (# ' + ', '.join(f'{(count - 1 - i) + (count if i % 2 else 0)}#' for i in range(count)) + ' #)'
            source += [f'  case unpack{n}# ({vector}) of',
                       '    (# ' + ', '.join(f'p{i}' for i in range(count)) + ' #) -> case lane of']
            for i in range(count):
                value = observe_lane(i)
                source.append(f'      {str(i)+"#" if i < count-1 else "_"} -> {value}')
            source += [f'{name} :: Int# -> Int# -> Int# -> Int#',
                       f'{name} lane a b = case {worker} lane a b of value -> value +# 17#', '']
    native = [*HASKELL_HEADER, '{-# LANGUAGE MagicHash #-}', 'module Main where', 'import GHC.Exts',
              'import Data.Bits (finiteBitSize)', 'import GeneratedSimdFamilies', '',
              'emit :: String -> (Int# -> Int# -> Int# -> Int#) -> Int -> Int -> Int -> IO ()',
              'emit name f lane@(I# k) a@(I# x) b@(I# y) =',
              '  putStrLn (name ++ "\\t" ++ show lane ++ "\\t" ++ show a ++ "\\t" ++ show b ++ "\\t" ++ show (I# (f k x y)))',
              'dispatch :: [String] -> IO ()', 'dispatch [name, lane, a, b] = case name of']
    native += [f'  "{name}" -> emit name {name} (read lane) (read a) (read b)' for name in names]
    native += ['  _ -> error "unknown SIMD family entry"', 'dispatch _ = error "invalid input"',
               'main :: IO ()', 'main = if finiteBitSize (0 :: Int) /= 64 then error "Requires 64-bit Int"',
               '       else getContents >>= mapM_ (dispatch . words) . lines']
    return {'fixtures/GeneratedSimdFamilies.hs': '\n'.join(source)+'\n',
            'fixtures/GeneratedSimdFamiliesNative.hs': '\n'.join(native)+'\n'}


def smoke_entries(fs):
    return [(f, op) for f in fs for op in f['operations'] if op not in ('pack', 'unpack')]


def smoke_groups(fs):
    """Keep unrelated families separate and bound each driver's lane work."""
    groups = []
    legacy = []
    index = 0
    for family in fs:
        indices = []
        for operation in family['operations']:
            if operation in ('pack', 'unpack'):
                continue
            (legacy if operation == 'insert' and not family['newCarrier'] else indices).append(index)
            index += 1
        limit = 112 // family['lanes']
        for start in range(0, len(indices), limit):
            groups.append(indices[start:start + limit])
    if legacy:
        groups.append(legacy)
    return {f'simdSmoke{i}': indices for i, indices in enumerate(groups)}


def smoke_sources(fs):
    """Bounded composite drivers; the native scalar oracle needs no SIMD ISA."""
    convert = {
        'Int8Rep': lambda x: f'intToInt8# ({x})',
        'Word8Rep': lambda x: f'wordToWord8# (int2Word# ({x}))',
        'Int16Rep': lambda x: f'intToInt16# ({x})',
        'Word16Rep': lambda x: f'wordToWord16# (int2Word# ({x}))',
        'Int32Rep': lambda x: f'intToInt32# ({x})',
        'Word32Rep': lambda x: f'wordToWord32# (int2Word# ({x}))',
        'Int64Rep': lambda x: f'intToInt64# ({x})',
        'Word64Rep': lambda x: f'wordToWord64# (int2Word# ({x}))',
        'FloatRep': lambda x: f'castWord32ToFloat# (wordToWord32# (int2Word# ({x})))',
        'DoubleRep': lambda x: f'castWord64ToDouble# (wordToWord64# (int2Word# ({x})))',
    }
    def observe(rep, value, raw=False):
        if rep.startswith('Word'):
            return f'word2Int# (word{rep[4:-3]}ToWord# ({value}))'
        if rep.startswith('Int'):
            return f'int{rep[3:-3]}ToInt# ({value})'
        if raw:
            width = '32' if rep == 'FloatRep' else '64'
            stem = rep.removesuffix('Rep')
            return f'word2Int# (word{width}ToWord# (cast{stem}ToWord{width}# ({value})))'
        if rep == 'FloatRep':
            return f'case {value} of v -> case neFloat# v v of {{ 1# -> 2143289344#; _ -> word2Int# (word32ToWord# (castFloatToWord32# v)) }}'
        return f'case {value} of v -> case v /=## v of {{ 1# -> 9221120237041090560#; _ -> word2Int# (word64ToWord# (castDoubleToWord64# v)) }}'
    def header(name):
        extrema = [op + f['name'] + '#' for f in fs for op in f['operations'] if op in ('min', 'max', 'shuffle')]
        return [*HASKELL_HEADER, '{-# LANGUAGE MagicHash, UnboxedTuples #-}', f'module {name} where',
                'import GHC.Exts', *(['import GHC.Prim (' + ', '.join(extrema) + ')'] if name == 'GeneratedSimdSmoke' and extrema else []), '']
    def signature(entry):
        return [f'{entry} :: Int# -> Int# -> Int# -> Int#',
                f'{entry} selector a b = case quotInt# selector 4096# of']
    groups = smoke_groups(fs)
    owners = {index: name for name, indices in groups.items() for index in indices}
    drivers = {name: signature(name) for name in groups}
    scalar = header('GeneratedSimdSmokeScalar') + signature('scalarSmoke')
    for index, (f, op) in enumerate(smoke_entries(fs)):
        vector = drivers[owners[index]]
        n, count, rep = f['name'], f['lanes'], f['laneRep']
        lane = f'remInt# selector {count}#'
        left = f'pack{n}# (# ' + ', '.join(convert[rep](f'a +# {i * 104729}#') for i in range(count)) + ' #)'
        right = f'pack{n}# (# ' + ', '.join(convert[rep](f'b -# {i * 7919}#') for i in range(count)) + ' #)'
        value = (f'broadcast{n}# ({convert[rep]("a")})' if op == 'broadcast' else
                 f'{op}{n}# ({left})' + (f' ({right})' if op in BINARY or op == 'shuffle' else ''))
        inserted = f'remInt# (quotInt# selector 64#) {count}#'
        if op == 'shuffle':
            value += ' (# ' + ', '.join(f'{(count - 1 - i) + (count if i % 2 else 0)}#' for i in range(count)) + ' #)'
        if op == 'insert':
            value += f' ({convert[rep]("b")}) ({inserted})'
        vector += [f'  {index}# -> case unpack{n}# ({value}) of',
                   '    (# ' + ', '.join(f'p{i}' for i in range(count)) + f' #) -> case {lane} of']
        vector += [f'      {str(i) + "#" if i < count - 1 else "_"} -> {observe(rep, f"p{i}", op in ("insert", "shuffle"))}' for i in range(count)]
        left = convert[rep]('a' if op == 'broadcast' else f'a +# (({lane}) *# 104729#)')
        right = convert[rep](f'b -# (({lane}) *# 7919#)')
        stem = rep.removesuffix('Rep')
        primitive = (dict(plus='(+##)', minus='(-##)', times='(*##)', divide='(/##)', negate='negateDouble#').get(op)
                     if rep == 'DoubleRep' else
                     ('sub' if op == 'minus' and rep not in ('FloatRep', 'DoubleRep') else op) + stem + '#')
        if op == 'shuffle':
            selected = f'{count - 1}# -# ({lane})'
            a = convert[rep](f'a +# (({selected}) *# 104729#)')
            b = convert[rep](f'b -# (({selected}) *# 7919#)')
            scalar.append(f'  {index}# -> case remInt# ({lane}) 2# of {{ 0# -> {observe(rep, a, True)}; _ -> {observe(rep, b, True)} }}')
        elif op == 'insert':
            scalar.append(f'  {index}# -> case ({lane}) ==# ({inserted}) of {{ 1# -> {observe(rep, convert[rep]("b"), True)}; _ -> {observe(rep, left, True)} }}')
        elif op in ('min', 'max'):
            # The native oracle compares scalar lanes. Floating extrema requests
            # are finite and exclude ambiguous zero ties; Java-only edges are
            # tested separately by the Kotlin consumer of genuine vector Core.
            first, second = (left, right) if op == 'min' else (right, left)
            comparison = '(<##)' if rep == 'DoubleRep' else f'lt{stem}#'
            scalar.append(f'  {index}# -> case {comparison} ({left}) ({right}) of {{ 1# -> ({observe(rep, first)}); _ -> ({observe(rep, second)}) }}')
        else:
            value = left if op == 'broadcast' else f'{primitive} ({left})' + (f' ({right})' if op in BINARY or op == 'shuffle' else '')
            scalar.append(f'  {index}# -> {observe(rep, value)}')
    vector = header('GeneratedSimdSmoke')
    for driver in drivers.values():
        vector += driver + ['  _ -> 0#', '']
    scalar += ['  _ -> 0#']
    outputs = {'fixtures/GeneratedSimdSmoke.hs': '\n'.join(vector) + '\n',
               'fixtures/GeneratedSimdSmokeScalar.hs': '\n'.join(scalar) + '\n'}
    for compare_vector in (False, True):
        main = [*HASKELL_HEADER, '{-# LANGUAGE MagicHash #-}', 'module Main where',
                'import GHC.Exts', 'import Data.Bits (finiteBitSize)', 'import GeneratedSimdSmokeScalar']
        if compare_vector:
            main += ['import GeneratedSimdSmoke']
        main += ['emit :: [String] -> IO ()', 'emit [name, selector, left, right] =',
                 '  case (read selector, read left, read right) of',
                 '    (I# k, I# a, I# b) ->',
                 '      let answer = I# (scalarSmoke k a b)']
        if compare_vector:
            main += ['          actual = case name of']
            main += [f'            "{name}" -> I# ({name} k a b)' for name in groups]
            main += ['            _ -> error "Unknown SIMD smoke entry"', '      in',
                     '        if answer /= actual then error "Native SIMD/scalar mismatch" else']
        else:
            main += ['      in', f'        if name `notElem` {json.dumps(list(groups))} then error "Unknown SIMD smoke entry" else']
        main += ['          putStrLn (name ++ "\\t" ++ selector ++ "\\t" ++ left ++ "\\t" ++ right ++ "\\t" ++ show answer)',
                 'emit _ = error "Invalid SIMD smoke input"', 'main :: IO ()',
                 'main = if finiteBitSize (0 :: Int) /= 64 then error "Requires 64-bit Int"',
                 '       else getContents >>= mapM_ (emit . words) . lines']
        suffix = 'Vector' if compare_vector else 'Scalar'
        outputs[f'fixtures/GeneratedSimdSmoke{suffix}Native.hs'] = '\n'.join(main) + '\n'
    return outputs


def region(path, content, write):
    begin='    // BEGIN GENERATED SIMD FAMILIES\n';end='    // END GENERATED SIMD FAMILIES\n'
    source=path.read_text()
    if source.count(begin)!=1 or source.count(end)!=1:raise ValueError(f'Missing unique generated region in {path}')
    before,tail=source.split(begin);old,after=tail.split(end)
    if write:path.write_text(before+begin+content+end+after)
    elif old!=content:raise ValueError(f'Stale generated region: {path}; run generator --write')


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output',type=Path,default=ROOT/'build/generated/simd')
    mode=parser.add_mutually_exclusive_group();mode.add_argument('--write',action='store_true');mode.add_argument('--check',action='store_true')
    parser.add_argument('--verify-ghc',action='store_true')
    args=parser.parse_args();fs=families()
    if args.verify_ghc:verify_ghc(fs)
    region(ROOT/'src/main/java/thc/runtime/BytecodeRoot.java',bytecode_nodes(fs),args.write)
    region(ROOT/'src/main/kotlin/thc/runtime/BytecodeProgram.kt',bytecode_emitter(fs),args.write)
    outputs={'kotlin/thc/runtime/GeneratedVectorProofs.kt':proof_code(fs),'kotlin/thc/runtime/GeneratedVectorExpressions.kt':ast_code(fs)}
    outputs.update(fixture_sources(fs))
    outputs.update(smoke_sources(fs))
    # Remove only former generated carriers/helpers when switching an existing build.
    (args.output / 'kotlin/thc/runtime/GeneratedVectorInsert.kt').unlink(missing_ok=True)
    (args.output / 'kotlin/thc/runtime/GeneratedVectorTransport.kt').unlink(missing_ok=True)
    (args.output / 'kotlin/thc/runtime/RawVectors.kt').unlink(missing_ok=True)
    for f in fs:
        (args.output / f'kotlin/thc/runtime/{f["name"]}.kt').unlink(missing_ok=True)
        (args.output / f'java/thc/runtime/{f["name"]}.java').unlink(missing_ok=True)
    for name,body in outputs.items():
        p=args.output/name;p.parent.mkdir(parents=True,exist_ok=True)
        if not p.exists() or p.read_text()!=body:p.write_text(body)
    print(f'Generated {len(outputs)} files / {len(contracts(fs))} typed SIMD operations')

if __name__=='__main__':main()
