#!/usr/bin/env python3
"""Generate concrete SIMD nodes from a small, pinned semantic/layout table.

Gradle writes build/generated/simd. --write updates the two explicitly marked
bytecode regions; --check verifies them. --verify-ghc checks machine contracts
against primOpSig/typePrimRep_maybe, without parsing printed Haskell types.
"""
import argparse
import json
import os
from pathlib import Path
import subprocess

ROOT = Path(__file__).resolve().parent.parent
SPEC = ROOT / 'scripts/simd-families.json'
# primitive scalar type, bit width, Java Vector type, Kotlin carrier accessor
LANES = {
    'Int8Rep': ('byte', 8, 'ByteVector', 'Long'),
    'Int16Rep': ('short', 16, 'ShortVector', 'Long'),
    'Int32Rep': ('int', 32, 'IntVector', 'Long'),
    'Int64Rep': ('long', 64, 'LongVector', 'Long'),
    'Word8Rep': ('byte', 8, 'ByteVector', 'Long'),
    'Word16Rep': ('short', 16, 'ShortVector', 'Long'),
    'Word32Rep': ('int', 32, 'IntVector', 'Long'),
    'Word64Rep': ('long', 64, 'LongVector', 'Long'),
    'FloatRep': ('float', 32, 'FloatVector', 'Float'),
    'DoubleRep': ('double', 64, 'DoubleVector', 'Double'),
}
BINARY = {'plus': 'add', 'minus': 'subtract', 'times': 'multiply', 'divide': 'divide'}
VECTOR_METHOD = {'add': 'add', 'subtract': 'sub', 'multiply': 'mul', 'divide': 'div'}
OPS = {'pack', 'unpack', 'broadcast', 'negate'} | BINARY.keys()
HEADER = '// Generated by scripts/generate-simd-families.py; edit the family table/generator.\n'
QUERY = r'''let reps t = fmap (map show) (GHC.Types.RepType.typePrimRep_maybe t); tuple t = case GHC.Core.Type.splitTyConApp_maybe t of { Just (tc,_) -> GHC.Core.TyCon.isUnboxedTupleTyCon tc; _ -> False }; emit op = let (_,args,res,arity,_) = GHC.Builtin.PrimOps.primOpSig op; name = GHC.Types.Name.Occurrence.occNameString (GHC.Builtin.PrimOps.primOpOcc op) in if name `notElem` NAMES then pure () else case traverse reps (args++[res]) of { Nothing -> pure (); Just rs -> putStrLn (GHC.Types.Name.Occurrence.occNameString (GHC.Builtin.PrimOps.primOpOcc op) ++ "\t" ++ show arity ++ "\t" ++ show rs ++ "\t" ++ show (map tuple (args++[res]))) } in mapM_ emit GHC.Builtin.PrimOps.allThePrimOps'''


def families(path=None):
    data = json.loads((SPEC if path is None else Path(path)).read_text())
    if data['schema'] != 1 or data['ghc'] != '9.14.1':
        raise ValueError('Expected pinned SIMD family schema')
    names = set()
    for f in data['families']:
        if f['laneRep'] not in LANES or type(f['lanes']) is not int or f['lanes'] <= 0:
            raise ValueError('Unsupported lane contract')
        scalar, width, _, _ = LANES[f['laneRep']]
        stem = f['laneRep'].removesuffix('Rep')
        if f['element'] != stem + 'ElemRep' or f['name'] != f'{stem}X{f["lanes"]}' or f['bits'] != width * f['lanes'] or f['bits'] not in (128, 256, 512):
            raise ValueError('Contradictory vector identity/layout')
        if f['name'] in names or not f['operations'] or len(set(f['operations'])) != len(f['operations']) or not set(f['operations']) <= OPS or type(f['newCarrier']) is not bool:
            raise ValueError('Malformed SIMD operation family')
        if 'divide' in f['operations'] and scalar not in ('float', 'double'):
            raise ValueError('Integer vector division is a separate semantic family')
        if 'negate' in f['operations'] and f['laneRep'].startswith('Word'):
            raise ValueError('No unsigned vector negation primop')
        names.add(f['name'])
    return data['families']


def narrow_lane(rep, value, language):
    """Store the low lane bits from the runtime's long integer representation."""
    scalar = LANES[rep][0]
    if scalar not in ('byte', 'short', 'int'):
        return value
    if language == 'kotlin':
        return f'{value}.to{scalar.capitalize()}()'
    if language == 'java':
        return f'({scalar}) {value}'
    raise ValueError(f'Unsupported lane conversion language: {language}')


def widen_lane(rep, value, language):
    """Recover signed or unsigned lane values, preserving raw 64-bit words."""
    scalar, width, _, _ = LANES[rep]
    if scalar not in ('byte', 'short', 'int'):
        return value
    if language == 'kotlin':
        wide = f'{value}.toLong()'
        return f'{wide} and {(1 << width) - 1}L' if rep.startswith('Word') else wide
    if language == 'java':
        if rep.startswith('Word'):
            boxed = {'byte': 'Byte', 'short': 'Short', 'int': 'Integer'}[scalar]
            return f'{boxed}.toUnsignedLong({value})'
        return value  # Java sign-extends byte, short and int arguments to long.
    raise ValueError(f'Unsupported lane conversion language: {language}')


def haskell_narrow_lane(rep, value):
    if rep.startswith('Int'):
        return f'intTo{rep.removesuffix("Rep")}# ({value})'
    if rep.startswith('Word'):
        return f'wordTo{rep.removesuffix("Rep")}# (int2Word# ({value}))'
    if rep == 'FloatRep':
        return f'castWord32ToFloat# (wordToWord32# (int2Word# ({value})))'
    if rep == 'DoubleRep':
        return f'castWord64ToDouble# (wordToWord64# (int2Word# ({value})))'
    raise ValueError(f'Unsupported lane representation: {rep}')


def haskell_observe_lane(rep, value):
    if rep.startswith('Int'):
        return f'{rep.removesuffix("Rep").lower()}ToInt# {value}'
    if rep.startswith('Word'):
        return f'word2Int# ({rep.removesuffix("Rep").lower()}ToWord# {value})'
    if rep in ('FloatRep', 'DoubleRep'):
        return f'bits{rep.removesuffix("Rep")} {value}'
    raise ValueError(f'Unsupported lane representation: {rep}')


def contracts(fs):
    result = {}
    for f in fs:
        vector = [f'VecRep {f["lanes"]} {f["element"]}']
        lane = [f['laneRep']]
        packed = lane * f['lanes']
        for op in f['operations']:
            args = [packed] if op == 'pack' else [lane] if op == 'broadcast' else [vector] * (2 if op in BINARY else 1)
            result[op + f['name'] + '#'] = {'arity':len(args), 'reps': args + [packed if op == 'unpack' else vector], 'tuples': [op == 'pack'] * len(args) + [op == 'unpack']}
    return result


def verify_ghc(fs):
    ghc = os.environ.get('GHC', 'ghc')
    if subprocess.check_output([ghc, '--numeric-version'], text=True).strip() != '9.14.1':
        raise ValueError('GHC 9.14.1 required')
    rows = subprocess.check_output([ghc, '-ignore-dot-ghci', '-package', 'ghc', '-e', QUERY.replace('NAMES', json.dumps(list(contracts(fs))))], text=True)
    actual = {}
    for line in rows.splitlines():
        name, arity, reps, tuples = line.split('\t')
        actual[name] = {'arity': int(arity), 'reps': json.loads(reps), 'tuples':json.loads(tuples.replace('True','true').replace('False','false'))}
    expected = contracts(fs)
    for name, proof in expected.items():
        if actual.get(name) != proof:
            raise ValueError(f'GHC machine contract disagrees for {name}: {actual.get(name)} != {proof}')
    print(f'Verified {len(expected)} exact SIMD contracts with pinned GHC APIs')


def carrier(f):
    n = f['name']; count = f['lanes']; scalar, _, vector, _ = LANES[f['laneRep']]
    fields = ', '.join(f'{scalar} lane{i}' for i in range(count))
    init = '\n'.join(f'        this.lane{i} = lane{i};' for i in range(count))
    vec = f'{vector}.broadcast({vector}.SPECIES_{f["bits"]}, lane0)' + ''.join(f'.withLane({i}, lane{i})' for i in range(1,count))
    declarations = '\n'.join(f'    public final {scalar} lane{i};' for i in range(count))
    body = f'''package thc.runtime;
import jdk.incubator.vector.{vector};
/** Exact durable primitive lanes; transient Vector API storage never escapes here. */
public final class {n} {{
{declarations}
    public {n}({fields}) {{
{init}
    }}
    private {vector} vector() {{ return {vec}; }}
    private static {n} lanes({vector} v) {{ return new {n}({', '.join(f'v.lane({i})' for i in range(count))}); }}
    public static {n} broadcast({scalar} x) {{ return new {n}({', '.join('x' for _ in range(count))}); }}
'''
    for op in f['operations']:
        if op in BINARY:
            method = BINARY[op]
            body += f'    public static {n} {method}({n} a, {n} b) {{ return lanes(a.vector().{VECTOR_METHOD[method]}(b.vector())); }}\n'
        elif op == 'negate':
            body += f'    public static {n} negate({n} a) {{ return lanes(a.vector().neg()); }}\n'
    return HEADER + body + '}\n'


def proof_code(fs):
    lines = [HEADER, 'package thc.runtime\n', 'internal object GeneratedVectors {']
    for f in fs:
        n=f['name']; kind=LANES[f['laneRep']][3].upper();count=f['lanes'];rep=f['laneRep']
        lines += [f'    val vector{n} = CoreVector({count}, "{f["element"]}")',
                  f'    val proof{n} = CoreRepresentation(CoreKind.VECTOR, true, true, listOf("VecRep {count} {f["element"]}"), vector = vector{n})',
                  f'    private val lane{n} = CoreRepresentation(CoreKind.{kind}, true, true, listOf("{rep}"))',
                  f'    val unpacked{n} = CoreRepresentation(CoreKind.UNKNOWN, true, true, List({count}) {{ "{rep}" }}, List({count}) {{ lane{n} }})']
    allops=list(contracts(fs))
    lines += ['    val operations = setOf('+', '.join('"'+name+'"' for name in allops)+')',
              '    fun supports(vector: CoreVector): Boolean = '+ ' || '.join(f'vector == vector{f["name"]}' for f in fs if f['newCarrier']),
              '    fun validate(name: String, arguments: List<CoreRepresentation>, result: CoreRepresentation) {',
              '        val contract = when (name) {']
    for f in fs:
        n=f['name']
        for op in f['operations']:
            args=f'unpacked{n}' if op=='pack' else f'lane{n}' if op=='broadcast' else ', '.join([f'proof{n}']*(2 if op in BINARY else 1))
            result=f'unpacked{n}' if op=='unpack' else f'proof{n}'
            lines.append(f'            "{op}{n}#" -> Pair(listOf({args}), {result})')
    lines += ['            else -> throw UnsupportedCore("Unsupported generated vector primitive $name")','        }',
              '        CoreVectors.validateSignature(name, arguments, result, contract.first, contract.second)', '    }',
              '    fun expression(name: String, arguments: Array<Expr>, allocate: (Int) -> IntArray): Expr = when (name) {']
    for f in fs:
        n=f['name']
        for op in f['operations']:
            expr=f'Generated{n}Pack(arguments[0], allocate({f["lanes"]}))' if op=='pack' else f'Generated{n}Unpack(arguments[0])' if op=='unpack' else f'Generated{n}Operation(name, arguments)'
            lines.append(f'        "{op}{n}#" -> {expr}')
    lines += ['        else -> throw UnsupportedCore("Unsupported generated vector primitive $name")','    }','}']
    return '\n'.join(lines)+'\n'


def ast_code(fs):
    lines=[HEADER,'package thc.runtime\n','import com.oracle.truffle.api.CompilerDirectives.CompilationFinal','import com.oracle.truffle.api.frame.VirtualFrame\n']
    for f in fs:
        n=f['name'];count=f['lanes'];rep=f['laneRep'];_,_,_,access=LANES[rep]
        if 'pack' in f['operations']:
            lines += [f'internal class Generated{n}Pack(@field:Child private var argument: Expr,',
                      '    @field:CompilationFinal(dimensions = 1) private val slots: IntArray) : Expr() {',
                      f'    init {{ representation = GeneratedVectors.proof{n} }}',
                      f'    override fun execute(frame: VirtualFrame): {n} {{', '        argument.executeTuple(frame, slots)',
                      f'        return {n}('+', '.join(narrow_lane(rep, f'frame.get{access}(slots[{i}])', 'kotlin') for i in range(count))+')','    }','}']
        if 'unpack' in f['operations']:
            lines += [f'internal class Generated{n}Unpack(@field:Child private var argument: Expr) : Expr() {{',
                      f'    init {{ representation = GeneratedVectors.unpacked{n} }}',
                      '    override fun execute(frame: VirtualFrame): Nothing = fault("Vector unpack requires a tuple destination")',
                      '    override fun executeTuple(frame: VirtualFrame, slots: IntArray, offset: Int): Any? {',
                      f'        val value = argument.execute(frame) as? {n} ?: fault("Expected {n}#")']
            for i in range(count):
                wide=widen_lane(rep, f'value.lane{i}', 'kotlin')
                lines.append(f'        FrameAccess.write{access}(frame, slots[offset + {i}], {wide})')
            lines += ['        return null','    }','}']
        ops=[op for op in f['operations'] if op not in ('pack','unpack')]
        lines += [f'internal class Generated{n}Operation(name: String, @field:Children private var arguments: Array<Expr>) : Expr() {{',
                  '    private val operation = when (name) {']
        lines += [f'        "{op}{n}#" -> {i}' for i,op in enumerate(ops)]
        lines += [f'        else -> throw RuntimeFault("Invalid {n} operation")','    }',
                  f'    init {{ representation = GeneratedVectors.proof{n} }}',
                  f'    override fun execute(frame: VirtualFrame): {n} = when (operation) {{']
        for i,op in enumerate(ops):
            argument=narrow_lane(rep, f'arguments[0].executeRequired{access}(frame)', 'kotlin')
            expr=f'{n}.broadcast({argument})' if op=='broadcast' else f'{n}.negate(vector(frame, 0))' if op=='negate' else f'{n}.{BINARY[op]}(vector(frame, 0), vector(frame, 1))'
            lines.append(f'        {i} -> {expr}')
        lines += [f'        else -> fault("Invalid {n} operation")','    }',
                  f'    private fun vector(frame: VirtualFrame, index: Int): {n} = arguments[index].execute(frame) as? {n} ?: fault("Expected {n}#")','}\n']
    return '\n'.join(lines)+'\n'


def bytecode_nodes(fs):
    lines=[]
    for f in fs:
        n=f['name'];count=f['lanes'];rep=f['laneRep'];_,_,_,access=LANES[rep];prim=access.lower()
        for op in f['operations']:
            title=op.capitalize(); node=f'Generated{n}{title}'
            if op=='unpack':
                lines += ['    @Operation']+[f'    @ConstantOperand(type = LocalAccessor.class, name = "lane{i}")' for i in range(count)]
                lines += [f'    public static final class {node} {{',
                          '        @Specialization public static void apply(VirtualFrame frame, '+', '.join(f'LocalAccessor lane{i}' for i in range(count))+f', {n} value, @Bind("$node") Node node) {{',
                          '            BytecodeNode bytecode = ((BytecodeRoot) node.getRootNode()).getBytecodeNode();']
                lines += [f'            lane{i}.set{access}(bytecode, frame, {widen_lane(rep, f"value.lane{i}", "java")});' for i in range(count)]
                lines += ['        }','    }']
            else:
                if op=='pack':
                    params=', '.join(f'{prim} lane{i}' for i in range(count)); expr=f'new {n}('+', '.join(narrow_lane(rep, f'lane{i}', 'java') for i in range(count))+')'
                elif op=='broadcast':params=f'{prim} value';expr=f'{n}.broadcast({narrow_lane(rep, "value", "java")})'
                elif op=='negate':params=f'{n} value';expr=f'{n}.negate(value)'
                else:params=f'{n} left, {n} right';expr=f'{n}.{BINARY[op]}(left, right)'
                lines += [f'    @Operation public static final class {node} {{',f'        @Specialization public static {n} apply({params}) {{ return {expr}; }}','    }']
    return '\n'.join(lines)+'\n'


def bytecode_emitter(fs):
    lines=['    private fun generatedVectorPrimitive(name: String, operands: List<Expression>): Expression = when (name) {']
    for f in fs:
        n=f['name'];count=f['lanes']
        for op in f['operations']:
            node=f'Generated{n}{op.capitalize()}'
            if op=='unpack':
                lines += [f'        "{op}{n}#" -> tupleExpression(GeneratedVectors.unpacked{n}) {{ e, destination ->',
                          f'            e.builder.begin{node}('+', '.join(f'destination[{i}]' for i in range(count))+')',
                          '            operands[0].emit(e)',f'            e.builder.end{node}()','        }']
            else:
                lines += [f'        "{op}{n}#" -> ProvenExpression(Expression {{ e ->','            val b = e.builder']
                if op=='pack':
                    lines += ['            b.beginBlock()',f'            val lanes = List({count}) {{ b.createLocal() }}','            operands[0].emitTuple(e, lanes)',f'            b.begin{node}(); lanes.forEach(b::emitLoadLocal); b.end{node}()','            b.endBlock()']
                else:
                    lines += [f'            b.begin{node}(); operands.forEach {{ it.emit(e) }}; b.end{node}()']
                lines += [f'        }}, GeneratedVectors.proof{n})']
    lines += ['        else -> throw UnsupportedCore("Unsupported generated vector primitive $name")','    }']
    return '\n'.join(lines)+'\n'


def fixture_sources(fs):
    """Real scalar-entry Haskell; vectors never cross a function boundary."""
    source = ['{-# LANGUAGE MagicHash, UnboxedTuples #-}', 'module GeneratedSimdFamilies where',
              'import GHC.Exts', '',
              '-- NaN payload selection is not part of arithmetic primop semantics.',
              '-- All non-NaNs are observed as exact bits, including signed zero.',
              '{-# INLINE bitsFloat #-}', 'bitsFloat :: Float# -> Int#',
              'bitsFloat value = case neFloat# value value of',
              '  1# -> 2143289344#',
              '  _ -> word2Int# (word32ToWord# (castFloatToWord32# value))',
              '{-# INLINE bitsDouble #-}', 'bitsDouble :: Double# -> Int#',
              'bitsDouble value = case value /=## value of',
              '  1# -> 9221120237041090560#',
              '  _ -> word2Int# (word64ToWord# (castDoubleToWord64# value))', '']
    names = []
    for family in fs:
        n = family['name']; count = family['lanes']; rep = family['laneRep']
        for op in family['operations']:
            if op in ('pack', 'unpack'):
                continue
            name = op + n; worker = name + 'Worker'; names.append(name)
            source += [f'{{-# OPAQUE {worker} #-}}', f'{worker} :: Int# -> Int# -> Int# -> Int#',
                       f'{worker} lane a b =']
            if op == 'broadcast':
                vector = f'broadcast{n}# ({haskell_narrow_lane(rep, "a")})'
            else:
                left = f'pack{n}# (# ' + ', '.join(haskell_narrow_lane(rep, f'a +# {i * 104729}#') for i in range(count)) + ' #)'
                right = f'pack{n}# (# ' + ', '.join(haskell_narrow_lane(rep, f'b -# {i * 7919}#') for i in range(count)) + ' #)'
                vector = f'{op}{n}# ({left})' + (f' ({right})' if op in BINARY else '')
            source += [f'  case unpack{n}# ({vector}) of',
                       '    (# ' + ', '.join(f'p{i}' for i in range(count)) + ' #) -> case lane of']
            for i in range(count):
                value = haskell_observe_lane(rep, f'p{i}')
                source.append(f'      {str(i)+"#" if i < count-1 else "_"} -> {value}')
            source += [f'{name} :: Int# -> Int# -> Int# -> Int#',
                       f'{name} lane a b = case {worker} lane a b of value -> value +# 17#', '']
    native = ['{-# LANGUAGE MagicHash #-}', 'module Main where', 'import GHC.Exts',
              'import Data.Bits (finiteBitSize)', 'import GeneratedSimdFamilies', '',
              'emit :: String -> (Int# -> Int# -> Int# -> Int#) -> Int -> Int -> Int -> IO ()',
              'emit name f lane@(I# k) a@(I# x) b@(I# y) =',
              '  putStrLn (name ++ "\\t" ++ show lane ++ "\\t" ++ show a ++ "\\t" ++ show b ++ "\\t" ++ show (I# (f k x y)))',
              'dispatch :: [String] -> IO ()', 'dispatch [name, lane, a, b] = case name of']
    native += [f'  "{name}" -> emit name {name} (read lane) (read a) (read b)' for name in names]
    native += ['  _ -> error "unknown SIMD family entry"', 'dispatch _ = error "invalid input"',
               'main :: IO ()', 'main = if finiteBitSize (0 :: Int) /= 64 then error "Requires 64-bit Int"',
               '       else getContents >>= mapM_ (dispatch . words) . lines']
    return {'fixtures/GeneratedSimdFamilies.hs': '\n'.join(source)+'\n',
            'fixtures/GeneratedSimdFamiliesNative.hs': '\n'.join(native)+'\n'}


def region(path, content, write):
    begin='    // BEGIN GENERATED SIMD FAMILIES\n';end='    // END GENERATED SIMD FAMILIES\n'
    source=path.read_text()
    if source.count(begin)!=1 or source.count(end)!=1:raise ValueError(f'Missing unique generated region in {path}')
    before,tail=source.split(begin);old,after=tail.split(end)
    if write:path.write_text(before+begin+content+end+after)
    elif old!=content:raise ValueError(f'Stale generated region: {path}; run generator --write')


def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output',type=Path,default=ROOT/'build/generated/simd')
    mode=parser.add_mutually_exclusive_group();mode.add_argument('--write',action='store_true');mode.add_argument('--check',action='store_true')
    parser.add_argument('--verify-ghc',action='store_true')
    args=parser.parse_args();fs=families()
    if args.verify_ghc:verify_ghc(fs)
    region(ROOT/'src/main/java/thc/runtime/BytecodeRoot.java',bytecode_nodes(fs),args.write)
    region(ROOT/'src/main/kotlin/thc/runtime/BytecodeProgram.kt',bytecode_emitter(fs),args.write)
    outputs={'kotlin/thc/runtime/GeneratedVectorProofs.kt':proof_code(fs),'kotlin/thc/runtime/GeneratedVectorExpressions.kt':ast_code(fs)}
    outputs.update({f'java/thc/runtime/{f["name"]}.java':carrier(f) for f in fs if f['newCarrier']})
    outputs.update(fixture_sources(fs))
    for name,body in outputs.items():
        p=args.output/name;p.parent.mkdir(parents=True,exist_ok=True)
        if not p.exists() or p.read_text()!=body:p.write_text(body)
    print(f'Generated {len(outputs)} files / {len(contracts(fs))} typed SIMD operations')

if __name__=='__main__':main()
