// SPDX-FileCopyrightText: 2026 Edward Kmett
// SPDX-License-Identifier: UPL-1.0 AND BSD-3-Clause
package thc.runtime;

import com.oracle.truffle.api.*;
import com.oracle.truffle.api.frame.VirtualFrame;
import com.oracle.truffle.api.nodes.*;
import org.graalvm.polyglot.Context;
import org.graalvm.polyglot.proxy.ProxyExecutable;
import org.junit.jupiter.api.*;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;
import thc.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.concurrent.atomic.*;
import java.util.function.*;
import static org.junit.jupiter.api.Assertions.*;

/** The optional JS dependency is loaded only by Gradle's polyglotTest task. */
@SuppressWarnings("unchecked")
public class PolyglotFFITest {
    private Map<String, Object> map(Object... items) { var result = new LinkedHashMap<String, Object>(); for (int i = 0; i < items.length; i += 2) result.put((String) items[i], items[i + 1]); return result; }
    private Map<String, Object> proof(String rep) { return map("kind", switch (rep) { case "AddrRep" -> "address"; case "IntRep", "Int8Rep", "Int16Rep", "Int32Rep", "Int64Rep", "WordRep", "Word16Rep" -> "long"; case "FloatRep" -> "float"; case "DoubleRep" -> "double"; case "State# RealWorld" -> "void"; default -> "object"; }, "primReps", rep.equals("State# RealWorld") ? List.of() : List.of(rep), "evaluated", !rep.equals("BoxedRep (Just Lifted)")); }
    private Map<String, Object> tuple(String rep) { return map("kind", "unknown", "primReps", List.of(rep), "evaluated", false, "aggregate", "unboxed-tuple", "components", List.of(proof("State# RealWorld"), proof(rep))); }
    List<Object> call(PolyglotOp op) {
        var arguments = new ArrayList<List<Object>>(); var reps = new ArrayList<Map<String, Object>>(); var flags = new ArrayList<Boolean>();
        for (int i = 0; i < op.getArguments().size(); i++) { String rep = op.getArguments().get(i); arguments.add(List.of("var", "argument" + i, map("rep", proof(rep)))); reps.add(proof(rep)); flags.add(rep.equals("BoxedRep (Just Lifted)")); }
        var result = op.scalarResult() ? proof(op.getResult()) : tuple(op.getResult());
        var descriptor = map("schema", 1, "target", map("kind", "static", "symbol", op.getSymbol(), "isFunction", true), "convention", "prim", "safety", "safe", "arity", arguments.size(), "suppliedArity", arguments.size(), "argumentReps", reps, "resultRep", result);
        if (op.getArgumentTypes() != null) { descriptor.put("schema", 2); descriptor.put("argumentTypes", op.getArgumentTypes()); }
        return List.of("app", List.of("var", "foreign-id"), arguments, flags, false, false, map("rep", result, "foreignCall", descriptor));
    }
    private List<Object> changed(List<Object> call, Consumer<Map<String, Object>> transform) { var result = new ArrayList<>(call); var metadata = new LinkedHashMap<>((Map<String, Object>) result.get(6)); var descriptor = new LinkedHashMap<>((Map<String, Object>) metadata.get("foreignCall")); transform.accept(descriptor); metadata.put("foreignCall", descriptor); result.set(6, metadata); return result; }
    private List<Object> javascriptCall(String source, List<String> input, String output, String safety) {
        var registers = new ArrayList<>(input); registers.add("State# RealWorld"); var arguments = new ArrayList<List<Object>>(); var reps = new ArrayList<Map<String, Object>>();
        for (int i = 0; i < registers.size(); i++) { String rep = registers.get(i); arguments.add(List.of("var", "argument" + i, map("rep", proof(rep)))); reps.add(proof(rep)); }
        var result = output.equals("void") ? map("kind", "unknown", "primReps", List.of(), "evaluated", false, "aggregate", "unboxed-tuple", "components", List.of(proof("State# RealWorld"))) : tuple(output);
        String symbol = "thc_javascript_v1_" + HexFormat.of().formatHex(source.getBytes(StandardCharsets.UTF_8)); var descriptor = map("schema", 1, "intrinsic", "javascript-v1", "javascriptSource", source, "target", map("kind", "static", "symbol", symbol, "isFunction", true), "convention", "ccall", "safety", safety, "arity", registers.size(), "suppliedArity", registers.size(), "argumentReps", reps, "resultRep", result);
        return List.of("app", List.of("var", "javascript-id"), arguments, Collections.nCopies(arguments.size(), false), false, false, map("rep", result, "foreignCall", descriptor));
    }
    private List<Object> javascriptCall() { return javascriptCall("((x) => x + 7)", List.of("IntRep"), "IntRep", "unsafe"); }
    private record Signature(List<String> arguments, String result, String safety) {}
    @Test public void javascriptIntrinsicRequiresExactSourceAndScalarStateSignature() {
        for (var signature : List.of(new Signature(List.of(), "void", "safe"), new Signature(List.of("IntRep"), "IntRep", "unsafe"), new Signature(List.of("DoubleRep"), "DoubleRep", "safe"), new Signature(List.of("IntRep", "DoubleRep"), "DoubleRep", "unsafe"))) {
            String source = "((x, y) => x + y)"; var validated = CoreJavaScript.validate(javascriptCall(source, signature.arguments, signature.result, signature.safety), false); assertNotNull(validated); assertEquals(source, validated.getSource()); assertEquals(ForeignSafety.synchronous(signature.safety), validated.getSafety()); var expected = new ArrayList<CoreKind>(); for (var rep : signature.arguments) expected.add(rep.equals("IntRep") ? CoreKind.LONG : CoreKind.DOUBLE); assertEquals(expected, Arrays.asList(validated.getArguments())); assertEquals(switch (signature.result) { case "IntRep" -> CoreKind.LONG; case "DoubleRep" -> CoreKind.DOUBLE; default -> CoreKind.VOID; }, validated.getResult());
        }
    }
    @Test public void javascriptIntrinsicRejectsSpoofedMarkersAndIncorrectRepresentations() {
        var valid = javascriptCall(); var forged = List.of(changed(valid, d -> d.remove("intrinsic")), changed(valid, d -> d.put("intrinsic", "javascript-v2")), changed(valid, d -> d.put("javascriptSource", "((x) => x + 8)")), changed(valid, d -> { var target = new LinkedHashMap<>((Map<String, Object>) d.get("target")); target.put("symbol", "thc_javascript_v1_00"); d.put("target", target); }), changed(valid, d -> d.put("convention", "javascript")), changed(valid, d -> d.put("safety", "interruptible")), changed(valid, d -> d.put("arity", 1)), changed(valid, d -> d.put("resultRep", proof("IntRep"))));
        for (int i = 0; i < forged.size(); i++) { var candidate = forged.get(i); var error = assertThrows(RuntimeFault.class, () -> CoreJavaScript.validate(candidate, false)); assertTrue(message(error).contains("JavaScript"), "javascript variant " + i + ": " + error.getMessage()); } assertThrows(RuntimeFault.class, () -> CoreJavaScript.validate(valid, true));
        var wrongActual = new ArrayList<>(valid); var args = new ArrayList<>((List<List<Object>>) wrongActual.get(2)); args.set(0, List.of("var", "argument0", map("rep", proof("DoubleRep")))); wrongActual.set(2, args); assertThrows(RuntimeFault.class, () -> CoreJavaScript.validate(wrongActual, false)); var wrongFlags = new ArrayList<>(valid); wrongFlags.set(3, List.of(true, false)); assertThrows(RuntimeFault.class, () -> CoreJavaScript.validate(wrongFlags, false)); var spoofed = new ArrayList<>(valid); spoofed.set(1, List.of("prim", "javascript-id")); assertThrows(RuntimeFault.class, () -> CoreJavaScript.validate(spoofed, false));
    }
    private String message(Throwable failure) { return failure.getMessage() == null ? "" : failure.getMessage(); }
    @Test public void exactVersionedForeignDeclarationIsRequired() {
        for (var op : PolyglotOp.values()) { var valid = call(op); assertEquals(op, CorePolyglot.validate(valid, false), op.getSymbol()); var bad = List.of(changed(valid, d -> d.put("schema", op.getArgumentTypes() == null ? 2 : 1)), changed(valid, d -> d.put("convention", "ccall")), changed(valid, d -> d.put("safety", "unsafe")), changed(valid, d -> d.put("arity", op.getArguments().size() - 1)), changed(valid, d -> d.put("suppliedArity", op.getArguments().size() - 1)), changed(valid, d -> d.put("target", map("kind", "dynamic", "symbol", op.getSymbol(), "isFunction", true))), changed(valid, d -> d.put("target", map("kind", "static", "symbol", op.getSymbol(), "isFunction", false))));
            for (int i = 0; i < bad.size(); i++) { var candidate = bad.get(i); var error = assertThrows(RuntimeFault.class, () -> CorePolyglot.validate(candidate, false)); assertTrue(message(error).contains("Invalid polyglot foreign call"), op + " declaration variant " + i + ": " + error.getMessage()); } assertThrows(RuntimeFault.class, () -> CorePolyglot.validate(valid, true)); var spoofed = new ArrayList<>(valid); spoofed.set(1, List.of("prim", "foreign-id")); assertThrows(RuntimeFault.class, () -> CorePolyglot.validate(spoofed, false));
        }
    }
    @Test public void exactActualArgumentsAndStateTupleAreRequired() {
        for (var op : PolyglotOp.values()) {
            var valid = call(op); var badDeclared = changed(valid, d -> { var declared = new ArrayList<>((List<Object>) d.get("argumentReps")); declared.set(0, proof(op.getArguments().getFirst().equals("IntRep") ? "AddrRep" : "IntRep")); d.put("argumentReps", declared); }); assertThrows(RuntimeFault.class, () -> CorePolyglot.validate(badDeclared, false));
            var badActual = new ArrayList<>(valid); var args = new ArrayList<>((List<List<Object>>) badActual.get(2)); args.set(0, List.of("var", "argument0", map("rep", proof("WordRep")))); badActual.set(2, args); assertThrows(RuntimeFault.class, () -> CorePolyglot.validate(badActual, false));
            int boxed = op.getArguments().indexOf("BoxedRep (Just Lifted)"); if (boxed >= 0) { var wrong = new ArrayList<>(valid); var arguments = new ArrayList<>((List<List<Object>>) wrong.get(2)); arguments.set(boxed, List.of("var", "argument" + boxed, map("rep", proof("BoxedRep (Just Unlifted)")))); wrong.set(2, arguments); assertThrows(RuntimeFault.class, () -> CorePolyglot.validate(wrong, false)); }
            var missing = new ArrayList<>(valid); var originalArgs = (List<?>) missing.get(2); missing.set(2, originalArgs.subList(0, originalArgs.size() - 1)); assertThrows(RuntimeFault.class, () -> CorePolyglot.validate(missing, false)); var badFlags = new ArrayList<>(valid); var flags = new ArrayList<>((List<Boolean>) badFlags.get(3)); flags.set(0, !flags.getFirst()); badFlags.set(3, flags); assertThrows(RuntimeFault.class, () -> CorePolyglot.validate(badFlags, false));
            var badTuple = changed(valid, d -> d.put("resultRep", op.scalarResult() ? tuple(op.getResult()) : proof(op.getResult()))); assertThrows(RuntimeFault.class, () -> CorePolyglot.validate(badTuple, false)); var actualTuple = new ArrayList<>(valid); var metadata = new LinkedHashMap<>((Map<String, Object>) actualTuple.get(6)); metadata.put("rep", tuple("WordRep")); actualTuple.set(6, metadata); assertThrows(RuntimeFault.class, () -> CorePolyglot.validate(actualTuple, false)); var badState = changed(valid, d -> d.put("resultRep", map("kind", "unknown", "primReps", List.of("IntRep", op.getResult()), "evaluated", false, "aggregate", "unboxed-tuple", "components", List.of(proof("IntRep"), proof(op.getResult()))))); assertThrows(RuntimeFault.class, () -> CorePolyglot.validate(badState, false));
        }
    }
    @Test public void byteArrayMutabilityRequiresItsExactNominalDeclaration() {
        for (var op : List.of(PolyglotOp.BUFFER_VIEW, PolyglotOp.BUFFER_MUTABLE_VIEW, PolyglotOp.BUFFER_COPY_INTO)) {
            var valid = call(op);
            assertThrows(RuntimeFault.class, () -> CorePolyglot.validate(changed(valid, d -> d.remove("argumentTypes")), false));
            var swapped = new ArrayList<>(op.getArgumentTypes());
            for (int i = 0; i < swapped.size(); i++) if (swapped.get(i) != null)
                swapped.set(i, swapped.get(i).equals("ByteArray#") ? "MutableByteArray#" : "ByteArray#");
            assertThrows(RuntimeFault.class, () -> CorePolyglot.validate(changed(valid, d -> d.put("argumentTypes", swapped)), false));
        }
    }
    @Test public void unversionedOrSpoofedHeadsCannotEnterTheAbi() { var valid = call(PolyglotOp.EVAL); assertNull(CorePolyglot.validate(List.of("var", "ordinary"), false)); var wrong = changed(valid, d -> d.put("target", map("kind", "static", "symbol", "thc_polyglot_eval", "isFunction", true))); assertThrows(UnsupportedCore.class, () -> CorePolyglot.validate(wrong, false)); var spoofed = List.of("prim", "fake", valid.get(6)); assertThrows(RuntimeFault.class, () -> CorePolyglot.validate(spoofed, false)); }
    private ManagedAddress address(String text) { return ManagedAddress.fromHex(HexFormat.of().formatHex(text.getBytes(StandardCharsets.UTF_8))); }
    private final class AccessRoot extends RootNode {
        @Child PolyglotAccess access = new PolyglotAccess(); AccessRoot(Language language) { super(language); }
        @Override public Object execute(VirtualFrame frame) { var args = frame.getArguments(); return switch ((String) args[0]) { case "eval" -> access.eval(address("js"), address((String) args[1]), address("ffi-test.js"), thc.runtime.Unit.INSTANCE); case "evalBadState" -> access.eval(address("js"), address((String) args[1]), address("ffi-test.js"), 0L); case "read" -> access.readMember(frame, args[1], address((String) args[2]), thc.runtime.Unit.INSTANCE); case "execute" -> access.executeInt(frame, args[1], (Long) args[2], thc.runtime.Unit.INSTANCE); default -> throw new IllegalStateException("Unknown test operation"); }; }
    }
    private static final class JavaScriptRoot extends RootNode {
        final JavaScriptImport declaration; @Child JavaScriptAccess access;
        JavaScriptRoot(Language language, JavaScriptImport declaration) { super(language); this.declaration = declaration; access = new JavaScriptAccess(declaration); }
        @Override public Object execute(VirtualFrame frame) { var supplied = frame.getArguments(); var arguments = Arrays.copyOfRange(supplied, 0, supplied.length - 1); var state = supplied[supplied.length - 1]; return switch (declaration.getResult()) { case LONG -> access.executeLong(arguments, state); case DOUBLE -> access.executeDouble(arguments, state); case VOID -> { access.executeVoid(arguments, state); yield thc.runtime.Unit.INSTANCE; } default -> throw new IllegalStateException("Unsupported test result kind"); }; }
    }
    private Context context() { return Context.newBuilder("thc", "js").allowExperimentalOptions(true).allowPolyglotAccess(org.graalvm.polyglot.PolyglotAccess.ALL).build(); }
    private AccessRoot root() { return new AccessRoot(TruffleLanguage.LanguageReference.create(Language.class).get(null)); }
    private JavaScriptRoot javascriptRoot(String source, List<String> input, String output) { return javascriptRoot(source, input, output, "unsafe"); }
    private JavaScriptRoot javascriptRoot(String source, List<String> input, String output, String safety) { return new JavaScriptRoot(TruffleLanguage.LanguageReference.create(Language.class).get(null), Objects.requireNonNull(CoreJavaScript.validate(javascriptCall(source, input, output, safety), false))); }
    /** A public entry exercises the actual interop entry/exit delimiter. */
    private EntryValue publicEntry(Language language, Function<VirtualFrame, Object> action) {
        var target = new RootNode(language) { @Override public Object execute(VirtualFrame frame) { return action.apply(frame); } }.getCallTarget();
        var program = new ExecutableProgram() { @Override public boolean getAsynchronousExceptions() { return true; } @Override public RootCallTarget hostEntryTarget(int arity) { return target; } @Override public Object entryValue(String name) { return thc.runtime.Unit.INSTANCE; } @Override public RootCallTarget entryTarget(String name) { return target; } @Override public DataLayout constructorLayout(String id) { throw new IllegalStateException("Unexpected constructor layout request in callback test: " + id); } @Override public Map<String, Object> diagnostics() { return Map.of(); } };
        return new EntryValue(program, "callback", 0);
    }
    @Test public void javascriptImportExecutesScalarAndVoidResults() { try (var context = context()) { context.initialize("thc"); context.enter(); try { var integer = javascriptRoot("((x) => x + 7)", List.of("IntRep"), "IntRep").getCallTarget(); assertEquals(48L, (Long) Calls.target(integer, new Object[] {41L, thc.runtime.Unit.INSTANCE})); var floating = javascriptRoot("((x) => x * 0.5)", List.of("DoubleRep"), "DoubleRep").getCallTarget(); assertEquals(1.5, (Double) Calls.target(floating, new Object[] {3.0, thc.runtime.Unit.INSTANCE})); var effect = javascriptRoot("(() => { globalThis.thcCount = (globalThis.thcCount || 0) + 1; })", List.of(), "void").getCallTarget(); Calls.target(effect, new Object[] {thc.runtime.Unit.INSTANCE}); Calls.target(effect, new Object[] {thc.runtime.Unit.INSTANCE}); assertEquals(2, context.eval("js", "globalThis.thcCount").asInt()); } finally { context.leave(); } } }
    @Test public void safeJavascriptCallbackKeepsCallerDeliveryAndStartsFreshUnmasked() { try (var context = context()) { context.initialize("thc"); context.enter(); try {
        var state = Language.currentState(null); var threads = state.getThreads(); var node = new Node() {}; long callerId = threads.enterCurrent(MaskingState.MASKED_UNINTERRUPTIBLE, false, true, null); var caller = threads.currentIdentity(); long javaId = Thread.currentThread().threadId();
        try { var request = threads.send(callerId, "callback payload"); var language = TruffleLanguage.LanguageReference.create(Language.class).get(null); var callback = context.asValue(publicEntry(language, frame -> {
            assertEquals(javaId, Thread.currentThread().threadId()); assertEquals(MaskingState.UNMASKED, state.getMaskingState().get()); assertNotSame(caller, threads.currentIdentity()); assertTrue(threads.isCurrentBound()); var nested = threads.enterForeign(ForeignSafety.UNSAFE); try { assertNull(threads.poll(node, false)); } finally { threads.leaveForeign(nested); } assertNull(threads.poll(node, false), "A callback cannot claim the suspended caller request"); var own = threads.send(threads.currentIdentity(), "callback self"); assertSame(own, threads.poll(node, false)); own.acknowledge(); return 42L;
        })); context.getBindings("js").putMember("thcReentry", (ProxyExecutable) args -> { assertEquals(javaId, Thread.currentThread().threadId()); assertNull(threads.poll(node, false), "The JavaScript call has no guest continuation cut"); long answer = callback.execute().asLong(); assertNull(threads.poll(node, false), "Callback exit restores JavaScript execution"); return answer; }); var target = javascriptRoot("globalThis.thcReentry", List.of(), "IntRep", "safe").getCallTarget(); assertEquals(42L, (Long) Calls.target(target, new Object[] {thc.runtime.Unit.INSTANCE})); assertEquals(AsyncRequestState.PENDING, request.getState()); assertSame(request, threads.poll(node, false)); request.acknowledge(); assertEquals(MaskingState.MASKED_UNINTERRUPTIBLE, state.getMaskingState().get()); var after = threads.send(callerId, "after foreign return"); assertSame(after, threads.poll(node, false), "The outer guest cut is restored after JavaScript returns"); after.acknowledge(); } finally { threads.leaveCurrent(GuestThreadStatus.FINISHED); }
    } finally { context.leave(); } } }
    @Test public void uncaughtCallbackCannotMemoizeOrReplayItsOpaqueForeignCaller() { try (var context = context()) { context.initialize("thc"); context.enter(); try {
        var language = TruffleLanguage.LanguageReference.create(Language.class).get(null); var outerThreads = Language.currentState(null).getThreads(); var node = new Node() {}; var payload = new Object(); var effects = new AtomicInteger(); var request = new AtomicReference<AsyncRequest>(); outerThreads.enterCurrent(null, false, true, null); var outerId = outerThreads.currentIdentity();
        try { try (var guest = Context.newBuilder("thc").allowExperimentalOptions(true).build()) { guest.initialize("thc"); guest.enter(); final org.graalvm.polyglot.Value callback;
            try { var innerLanguage = TruffleLanguage.LanguageReference.create(Language.class).get(null); var innerThreads = Language.currentState(null).getThreads(); var abandoned = new Thunk(new RootNode(innerLanguage) { @Override public Object execute(VirtualFrame frame) { return thc.runtime.Unit.INSTANCE; } }.getCallTarget(), null); callback = guest.asValue(publicEntry(innerLanguage, frame -> { long innerId = innerThreads.currentId(); assertNotEquals(outerId, innerThreads.currentIdentity()); assertEquals(outerId.getJavaId(), innerThreads.currentIdentity().getJavaId()); assertTrue(innerThreads.isCurrentBound()); var pending = innerThreads.send(innerId, payload); request.set(pending); var claimed = Objects.requireNonNull(innerThreads.poll(node, false)); assertSame(pending, claimed); throw new ThunkSuspended(abandoned, claimed); })); } finally { guest.leave(); }
            context.getBindings("js").putMember("thcUncaught", (ProxyExecutable) args -> { assertNull(outerThreads.poll(node, false), "Opaque JavaScript is not a delivery cut"); return callback.execute().asLong(); }); var declaration = Objects.requireNonNull(CoreJavaScript.validate(javascriptCall("globalThis.thcUncaught", List.of(), "IntRep", "safe"), false));
            var body = new RootNode(language) { @Child JavaScriptAccess access = new JavaScriptAccess(declaration); @Override public Object execute(VirtualFrame frame) { effects.incrementAndGet(); return access.executeLong(new Object[0], thc.runtime.Unit.INSTANCE); } }.getCallTarget(); var thunk = new Thunk(body, null); var driver = new RootNode(language) { @Child Force force = new Force(new Metrics(false)); @Override public Object execute(VirtualFrame frame) { return force.execute(frame, frame.getArguments()[0]); } }.getCallTarget();
            var escaped = assertThrows(Throwable.class, () -> Calls.target(driver, new Object[] {thunk})); assertFalse(escaped instanceof GuestException || escaped instanceof ThunkSuspended || escaped instanceof AsyncDelivery, "No synchronous guest failure or internal capture signal may escape JavaScript"); assertEquals(AsyncRequestState.ACKNOWLEDGED, request.get().getState()); assertSame(payload, request.get().getPayload()); assertEquals(4, thunk.getState(), "An opaque foreign caller has no saved continuation"); assertThrows(RuntimeFault.class, () -> Calls.target(driver, new Object[] {thunk})); assertEquals(1, effects.get(), "The abandoned foreign call must not run twice");
        } } finally { outerThreads.leaveCurrent(GuestThreadStatus.FINISHED); }
    } finally { context.leave(); } } }
    @Test public void cachedJavascriptCodeRetainsEachCallSitesCallbackAuthority() { try (var context = context()) { context.initialize("thc"); context.enter(); try {
        var language = TruffleLanguage.LanguageReference.create(Language.class).get(null); var owner = Language.currentState(null); var callbacks = new AtomicInteger(); var callback = context.asValue(publicEntry(language, frame -> { assertTrue(owner.getThreads().isCurrentBound()); callbacks.incrementAndGet(); return 42L; })); context.getBindings("js").putMember("thcAuthority", (ProxyExecutable) args -> callback.execute().asLong());
        // Cached source/arity identifies code, not a call site's authority.
        var unsafe = javascriptRoot("globalThis.thcAuthority", List.of(), "IntRep", "unsafe").getCallTarget(); var safe = javascriptRoot("globalThis.thcAuthority", List.of(), "IntRep", "safe").getCallTarget(); owner.getThreads().enterCurrent(MaskingState.MASKED_UNINTERRUPTIBLE, false, true, null); var caller = owner.getThreads().currentIdentity();
        try { for (int expectedCallbacks = 0; expectedCallbacks <= 1; expectedCallbacks++) { var denied = assertThrows(RuntimeException.class, () -> Calls.target(unsafe, new Object[] {thc.runtime.Unit.INSTANCE})); assertTrue(message(denied).contains("Unsafe foreign call"), denied.getMessage()); assertEquals(expectedCallbacks, callbacks.get()); assertSame(caller, owner.getThreads().currentIdentity()); assertFalse(caller.getAllocationSuspended()); assertEquals(MaskingState.MASKED_UNINTERRUPTIBLE, owner.getMaskingState().get()); if (expectedCallbacks == 0) assertEquals(42L, Calls.target(safe, new Object[] {thc.runtime.Unit.INSTANCE})); } } finally { owner.getThreads().leaveCurrent(GuestThreadStatus.FINISHED); }
    } finally { context.leave(); } } }
    Map<String, Object> foreignModule(List<Object> expression) { var parameters = new ArrayList<Map<String, Object>>(); for (var value : (List<List<Object>>) expression.get(2)) { var rep = (Map<?, ?>) ((Map<?, ?>) value.getLast()).get("rep"); parameters.add(map("id", value.get(1), "name", value.get(1), "lifted", Objects.equals(rep.get("primReps"), List.of("BoxedRep (Just Lifted)")), "coercion", false, "rep", rep)); } var result = ((Map<?, ?>) expression.getLast()).get("rep"); return map("bindings", List.of(map("id", "call", "name", "call", "lifted", true, "expr", List.of("lam", parameters, expression, map("resultRep", result)))), "instrument", true); }
    private long result(TupleShape shape, Object value) { return shape.getLayout().getLong(TupleResults.ownedTupleResult(value, shape), 0); }
    private long count(ExecutableProgram program) { return ((Number) program.diagnostics().get("compiledEntries")).longValue(); }
    @Tag("foreign-exceptions-full-core") @ParameterizedTest(name = "{0}") @ValueSource(strings = {"ast/js-safe", "ast/js-unsafe", "ast/polyglot", "bytecode/js-safe", "bytecode/js-unsafe", "bytecode/polyglot"})
    public void safeManagedCallsSaveTheirFirstCompiledResultBeforeAsyncDeliveryWithoutReplay(String mode) throws Exception {
        var parts = mode.split("/"); String backend = parts[0], kind = parts[1]; try (var context = Context.newBuilder("thc", "js").allowExperimentalOptions(true).allowPolyglotAccess(org.graalvm.polyglot.PolyglotAccess.ALL).allowNativeAccess(true).option("engine.BackgroundCompilation", "false").option("engine.MultiTier", "false").option("engine.SingleTierCompilationThreshold", "10000000").option("engine.CompilationFailureAction", "Throw").option("compiler.Inlining", "false").build()) { context.initialize("thc"); context.enter(); try {
            var language = TruffleLanguage.LanguageReference.create(Language.class).get(null); var owner = Language.currentState(null); var effects = new AtomicInteger(); var pending = new AtomicReference<AsyncRequest>(); boolean[] deliver = {false};
            context.getBindings("js").putMember("thcCompleted", (ProxyExecutable) args -> { effects.incrementAndGet(); if (deliver[0]) pending.set(owner.getThreads().send(owner.getThreads().currentIdentity(), "completed")); assertNull(owner.getThreads().poll(new Node() {}, false), "No delivery inside foreign execution"); return args[0].asLong() + 7L; }); boolean polyglot = kind.equals("polyglot"); var expression = polyglot ? call(PolyglotOp.EXECUTE_INT) : javascriptCall("globalThis.thcCompleted", List.of("IntRep"), "IntRep", kind.equals("js-safe") ? "safe" : "unsafe"); var module = ForeignExceptionFixtureSupport.link(foreignModule(expression), "call"); ExecutableProgram program = backend.equals("ast") ? new Program(language, module, true) : new BytecodeProgram(language, module, true); var target = program.entryTarget("call"); var shape = Objects.requireNonNull(((GuestRoot) target.getRootNode()).getTupleResult()); var handle = polyglot ? Calls.target(root().getCallTarget(), new Object[] {"eval", "(x => globalThis.thcCompleted(x))"}) : null; var arguments = polyglot ? new Object[] {0L, handle, 35L, thc.runtime.Unit.INSTANCE} : new Object[] {0L, 35L, thc.runtime.Unit.INSTANCE}; owner.getThreads().enterCurrent(null, false, true, null);
            try { for (int i = 0; i < 3; i++) assertEquals(42L, result(shape, Calls.target(target, arguments))); target.getClass().getMethod("compile", boolean.class).invoke(target, true); var targetClass = Class.forName("com.oracle.truffle.runtime.OptimizedCallTarget"); var runtime = Truffle.getRuntime(); runtime.getClass().getMethod("bypassedInstalledCode", targetClass).invoke(runtime, target); assertEquals(true, target.getClass().getMethod("isValidLastTier").invoke(target)); long before = count(program); var interpreted = target.getClass().getMethod("getCallCount").invoke(target); effects.set(0); deliver[0] = true; var answer = Calls.target(target, arguments); var retained = target.getClass().getMethod("isValidLastTier").invoke(target);
                assertEquals(before + 1L, count(program), backend + "/" + kind + " exact first installed entry"); assertEquals(interpreted, target.getClass().getMethod("getCallCount").invoke(target)); assertEquals(1, effects.get());
                if (kind.equals("js-unsafe")) { assertEquals(42L, result(shape, answer)); assertEquals(AsyncRequestState.PENDING, pending.get().getState()); assertSame(pending.get(), owner.getThreads().poll(target.getRootNode(), false)); pending.get().acknowledge(); }
                else { var saved = Objects.requireNonNull(SavedGuestContinuations.savedGuestContinuation(answer)); assertSame(target.getRootNode(), saved.getSourceRoot()); assertSame(pending.get(), saved.asyncRequest()); assertTrue(pending.get().compiledCapture); pending.get().acknowledge(); assertEquals(42L, result(shape, saved.continueWith(thc.runtime.Unit.INSTANCE))); }
                assertEquals(1, effects.get(), "Resuming a completed call never repeats the foreign effect");
                assertSame(target, program.entryTarget("call"), "Async delivery preserves the original logical target");
                // Stock bytecode branch profiles may invalidate on the first true async poll.
                // Compiled arrival/capture and once-only completion above remain mandatory.
                if (backend.equals("ast") || kind.equals("js-unsafe"))
                    assertEquals(true, retained, "The exact first installed call retains its target");
            } finally { owner.getThreads().leaveCurrent(GuestThreadStatus.FINISHED); }
        } finally { context.leave(); } }
    }
    @Test public void javascriptImportRebindsGlobalFunctionAndKeepsContextCachePrivate() { for (long increment : new long[] {1L, 100L}) try (var context = context()) { context.initialize("thc"); context.enter(); try { context.eval("js", "globalThis.thcAdd = x => x + " + increment); var target = javascriptRoot("globalThis.thcAdd", List.of("IntRep"), "IntRep").getCallTarget(); assertEquals(increment == 1L ? 11L : 110L, (Long) Calls.target(target, new Object[] {10L, thc.runtime.Unit.INSTANCE})); context.eval("js", "globalThis.thcAdd = x => x + 3"); assertEquals(13L, (Long) Calls.target(target, new Object[] {10L, thc.runtime.Unit.INSTANCE})); } finally { context.leave(); } } }
    @Test public void javascriptImportDoesNotCaptureBareGlobalsOrLoseMethodReceiver() { try (var context = context()) { context.initialize("thc"); context.enter(); try { context.eval("js", "globalThis.a0 = x => x + 7"); for (var source : List.of("a0", "\\u0061\\u0030")) { var target = javascriptRoot(source, List.of("IntRep"), "IntRep").getCallTarget(); assertEquals(18L, (Long) Calls.target(target, new Object[] {11L, thc.runtime.Unit.INSTANCE}), "import source " + source + " must resolve the global function"); } context.eval("js", "globalThis.obj = { base: 40, add(x) { return this.base + x; } }"); var method = javascriptRoot("globalThis.obj.add", List.of("IntRep"), "IntRep").getCallTarget(); assertEquals(51L, (Long) Calls.target(method, new Object[] {11L, thc.runtime.Unit.INSTANCE}), "method import must retain its JavaScript receiver"); } finally { context.leave(); } } }
    private record Invalid(Object[] arguments, String message) {}
    @Test public void javascriptImportRejectsMalformedInputsAndResults() { try (var context = context()) { context.initialize("thc"); context.enter(); try {
        var integer = javascriptRoot("((x) => x + 7)", List.of("IntRep"), "IntRep").getCallTarget(); for (var invalid : List.of(new Invalid(new Object[] {9007199254740992L, thc.runtime.Unit.INSTANCE}, "exact Number integer range"), new Invalid(new Object[] {3.0, thc.runtime.Unit.INSTANCE}, "expected Int#"), new Invalid(new Object[] {3L, 0L}, "zero-width scalar carrier"), new Invalid(new Object[] {thc.runtime.Unit.INSTANCE}, "argument count mismatch"))) { var error = assertThrows(RuntimeFault.class, () -> Calls.target(integer, invalid.arguments)); assertTrue(message(error).contains(invalid.message), error.getMessage()); }
        var string = javascriptRoot("((x) => 'not a number')", List.of("IntRep"), "IntRep").getCallTarget(); var nonnumeric = assertThrows(RuntimeFault.class, () -> Calls.target(string, new Object[] {1L, thc.runtime.Unit.INSTANCE})); assertTrue(message(nonnumeric).contains("not an exact Int#"), nonnumeric.getMessage()); var representable = javascriptRoot("(() => 9007199254740992)", List.of(), "IntRep").getCallTarget(); assertEquals(9007199254740992L, (Long) Calls.target(representable, new Object[] {thc.runtime.Unit.INSTANCE}));
        for (var source : List.of("(() => 1.5)", "(() => 9223372036854775808)")) { var invalid = javascriptRoot(source, List.of(), "IntRep").getCallTarget(); var error = assertThrows(RuntimeFault.class, () -> Calls.target(invalid, new Object[] {thc.runtime.Unit.INSTANCE})); assertTrue(message(error).contains("not an exact Int#"), error.getMessage()); } var throwing = javascriptRoot("((x) => { throw new Error('javascript import boom'); })", List.of("IntRep"), "IntRep").getCallTarget(); var foreign = assertThrows(RuntimeException.class, () -> Calls.target(throwing, new Object[] {1L, thc.runtime.Unit.INSTANCE})); assertTrue(message(foreign).contains("javascript import boom"), foreign.getMessage());
    } finally { context.leave(); } } }
    @Test public void javascriptParsingRequiresExplicitCrossLanguageAccess() { try (var context = Context.newBuilder("thc", "js").build()) { context.initialize("thc"); context.enter(); try { var denied = assertThrows(IllegalStateException.class, () -> Calls.target(root().getCallTarget(), new Object[] {"eval", "1"})); assertTrue(message(denied).contains("No language for id js"), denied.getMessage()); } finally { context.leave(); } } }
    @Test public void javascriptEvaluationMemberReadAndIntegerCallHonorTheContextBoundary() { try (var first = context()) { first.initialize("thc"); first.enter(); final ForeignValue value; try {
        var target = root().getCallTarget(); var state = assertThrows(RuntimeFault.class, () -> Calls.target(target, new Object[] {"evalBadState", "1"})); assertTrue(message(state).contains("zero-width scalar carrier"), state.getMessage()); value = (ForeignValue) Calls.target(target, new Object[] {"eval", "({twice: x => x * 2})"}); var function = (ForeignValue) Calls.target(target, new Object[] {"read", value, "twice"}); assertEquals(42L, (Long) Calls.target(target, new Object[] {"execute", function, 21L})); var missing = assertThrows(RuntimeFault.class, () -> Calls.target(target, new Object[] {"read", value, "absent"})); assertTrue(message(missing).contains("readMember"), missing.getMessage()); var fake = assertThrows(RuntimeFault.class, () -> Calls.target(target, new Object[] {"read", 42L, "twice"})); assertTrue(message(fake).contains("THC.Polyglot.Value"), fake.getMessage()); var range = assertThrows(RuntimeFault.class, () -> Calls.target(target, new Object[] {"execute", function, 9007199254740992L})); assertTrue(message(range).contains("exact Number integer range"), range.getMessage());
    } finally { first.leave(); } try (var second = context()) { second.initialize("thc"); second.enter(); try { var foreign = assertThrows(RuntimeFault.class, () -> Calls.target(root().getCallTarget(), new Object[] {"read", value, "twice"})); assertTrue(message(foreign).contains("different context"), foreign.getMessage()); } finally { second.leave(); } } } }
    @Test public void nonnumericResultsAndForeignExceptionsStayVisible() { try (var context = context()) { context.initialize("thc"); context.enter(); try { var target = root().getCallTarget(); var value = Calls.target(target, new Object[] {"eval", "({text: x => 'no', fractional: x => x + 0.5, boom: x => { throw new Error('boom from JS') }})"}); for (var name : List.of("text", "fractional")) { var function = Calls.target(target, new Object[] {"read", value, name}); var error = assertThrows(RuntimeFault.class, () -> Calls.target(target, new Object[] {"execute", function, 1L})); assertTrue(message(error).contains("not an exact Int#"), name + ": " + error.getMessage()); } var boom = Calls.target(target, new Object[] {"read", value, "boom"}); var error = assertThrows(RuntimeException.class, () -> Calls.target(target, new Object[] {"execute", boom, 1L})); assertTrue(message(error).contains("boom from JS"), error.getMessage()); } finally { context.leave(); } } }
}
